(define-library (adorn)
  (export adorn! reverse+simplify-kinds!)
  (import (scheme base)
          (scheme case-lambda)
          (scheme char)
          (scheme cxr))
  (include "matching.scm")
  (include "constants.scm")
  (include "adornment-helpers.scm")
  (include "symmetric-mesg-handlers.scm")
  (include "comment-mesg-handlers.scm")
  (include "binding-mesg-handlers.scm")
  (include "char-mesg-handlers.scm")
  (include "other-mesg-handlers.scm")
  (include "context-handlers.scm")
  (include "numeric-mesg-handlers.scm")
  (include "adornment.scm"))
