;==============================================================================
(define (^handle~bind-pm! sym ~sym ident-sym)
  (lambda (ac-list nc pac)
    (cond ((memc nc whitespace-chars) (adorn-char nc 'whitespace ~sym))
          ((char=? nc #\|) (begin-symmetric ac-list nc ident-sym))
          ((memc nc abbrev-chars) (adorn-char nc 'abbrev ~sym))
          ((and (char=? nc #\@) (char=? (get-char pac)) #\,)
           (adorn-char nc 'abbrev ~sym))
          ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (adorn-char nc sym sym)))))

(define ^handle~sv-define-pm!
  (^handle~bind-pm! 'sv-define '~sv-define 'sv-define-ident))

(define (handle~sv-define-pm! ac-list nc pac)
  (cond ((memc nc compound-begin-chars) (begin-compound! ac-list nc 'defun))
        (else (^handle~sv-define-pm! ac-list nc pac))))

(define ^handle~named/sv-let-pm!
  (^handle~bind-pm! 'named-let '~named/sv-let 'named-let-ident))

(define (handle~named/sv-let-pm! ac-list nc pac)
  (cond ((memc nc compound-begin-chars)
         (begin-compound! ac-list nc 'let-sv-outer))
        (else (^handle~named/sv-let-pm! ac-list nc pac))))

(define ^handle~~lambda-bind-pm!
  (^handle~bind-pm! 'lambda-rest '~lambda-bind 'lambda-rest-ident))

(define (handle~~lambda-bind-pm! ac-list nc pac)
  (cond ((memc nc compound-begin-chars)
         (begin-compound! ac-list nc 'lambda-bind-list))
        (else (^handle~~lambda-bind-pm! ac-list nc pac))))

(define handle~lambda-bind-pm!
  (^handle~bind-pm! 'lambda-bind '~lambda-bind 'lambda-bind-ident))

(define handle~defun-proc-pm!
  (^handle~bind-pm! 'defun-proc '~defun-proc 'defun-proc-ident))

(define handle~defun-param-pm!
  (^handle~bind-pm! 'defun-param '~defun-param 'defun-param-ident))

(define handle~sv-let-pm! (^handle~bind-pm! 'sv-let '~sv-let 'sv-let-ident))
(define handle~mv-let-pm! (^handle~bind-pm! 'mv-let '~mv-let 'mv-let-ident))

(define ^handle~~mv-define-pm!
  (^handle~bind-pm! 'mv-define-rest '~~mv-define 'mv-define-rest-ident))

(define (handle~~mv-define-pm! ac-list nc pac)
  (cond ((memc nc compound-begin-chars)
         (begin-compound! ac-list nc 'define-mv-list))
        (else (^handle~~mv-define-pm! ac-list nc pac))))

(define handle~mv-define-pm!
  (^handle~bind-pm! 'mv-define '~mv-define 'mv-define-ident))

(define handle~case-lambda-pm!
  (^handle~bind-pm! 'case-lambda-bind '~case-lambda 'case-lambda-bind-ident))

(define (^handle~outer-pm! next-compound-sym mesg)
  (lambda (ac-list nc pac)
    (cond ((memc nc compound-begin-chars)
           (begin-compound! ac-list nc next-compound-sym))
          ((memc nc whitespace-chars) (adorn-char nc 'whitespace mesg))
          ((memc nc abbrev-chars) (adorn-char nc 'abbrev mesg))
          ((and (char=? nc #\@) (char=? (get-char pac)) #\,)
           (adorn-char nc 'abbrev mesg))
          (else (try-nc! ac-list nc)))))

(define handle~~~let-sv-pm! (^handle~outer-pm! 'let-sv-outer '~~~let-sv))
(define handle~~let-sv-pm! (^handle~outer-pm! 'let-sv-inner '~~let-sv))

(define handle~~~~let-mv-pm! (^handle~outer-pm! 'let-mv-outermost '~~~~let-mv))
(define handle~~~let-mv-pm! (^handle~outer-pm! 'let-mv-outer '~~~let-mv))

(define ^handle~~let-mv-pm! (^handle~outer-pm! 'let-mv-inner '~~let-mv))

(define (handle~~let-mv-pm! ac-list nc pac)
  (cond ((char=? nc #\|) (begin-symmetric ac-list nc 'mv-let-rest-ident))
        ((memc nc delim-chars) (^handle~~let-mv-pm! ac-list nc pac))
        ((and (char=? nc #\@) (char=? (get-char pac) #\,))
         (^handle~~let-mv-pm! ac-list nc pac))
        (else (adorn-char nc 'mv-let-rest 'mv-let-rest))))

(define handle~~~case-lambda-pm!
  (^handle~outer-pm! 'case-lambda-outer '~~~case-lambda))
(define handle~~case-lambda-pm!
  (^handle~outer-pm! 'case-lambda-inner '~~case-lambda))
;==============================================================================
(define (^handle:bind-pm! sym ~next-mesg)
  (lambda (ac-list nc)
    (cond ((memc nc whitespace-chars) (adorn-char nc 'whitespace ~next-mesg))
          ((memc nc abbrev-chars) (adorn-char nc 'abbrev ~next-mesg))
          ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (adorn-char nc sym sym)))))

(define handle:sv-define-pm!   (^handle:bind-pm! 'sv-define #f))
(define handle:defun-proc-pm!  (^handle:bind-pm! 'defun-proc '~defun-param))
(define handle:defun-param-pm! (^handle:bind-pm! 'defun-param '~defun-param))
(define handle:named-let-pm!   (^handle:bind-pm! 'named-let '~~~let-sv))
(define handle:sv-let-pm!      (^handle:bind-pm! 'sv-let #f))
(define handle:lambda-bind-pm! (^handle:bind-pm! 'lambda-bind '~lambda-bind))
(define handle:lambda-rest-pm! (^handle:bind-pm! 'lambda-rest #f))
(define handle:mv-let-pm!      (^handle:bind-pm! 'mv-let '~mv-let))
(define handle:mv-let-rest-pm! (^handle:bind-pm! 'mv-let-rest #f))
(define handle:mv-define-pm!   (^handle:bind-pm! 'mv-define '~mv-define))
(define handle:mv-define-rest-pm! (^handle:bind-pm! 'mv-define-rest #f))
(define handle:case-lambda-bind-pm!
  (^handle:bind-pm! 'case-lambda-bind '~case-lambda))
;==============================================================================
(define (try-bind-pm! ac-list nc pac pm)
  (cond ((eq? pm 'sv-define)        (handle:sv-define-pm! ac-list nc))
        ((eq? pm 'lambda-bind)      (handle:lambda-bind-pm! ac-list nc))
        ((eq? pm 'lambda-rest)      (handle:lambda-rest-pm! ac-list nc))
        ((eq? pm 'sv-let)           (handle:sv-let-pm! ac-list nc))
        ((eq? pm 'named-let)        (handle:named-let-pm! ac-list nc))
        ((eq? pm 'defun-proc)       (handle:defun-proc-pm! ac-list nc))
        ((eq? pm 'defun-param)      (handle:defun-param-pm! ac-list nc))
        ((eq? pm '~~lambda-bind)    (handle~~lambda-bind-pm! ac-list nc pac))
        ((eq? pm 'mv-let)           (handle:mv-let-pm! ac-list nc))
        ((eq? pm 'mv-let-rest)      (handle:mv-let-rest-pm! ac-list nc))
        ((eq? pm 'mv-define)        (handle:mv-define-pm! ac-list nc))
        ((eq? pm 'mv-define-rest)   (handle:mv-define-rest-pm! ac-list nc))
        ((eq? pm '~~~let-sv)        (handle~~~let-sv-pm! ac-list nc pac))
        ((eq? pm '~sv-define)       (handle~sv-define-pm! ac-list nc pac))
        ((eq? pm '~named/sv-let)    (handle~named/sv-let-pm! ac-list nc pac))
        ((eq? pm '~defun-param)     (handle~defun-param-pm! ac-list nc pac))
        ((eq? pm '~~~~let-mv)       (handle~~~~let-mv-pm! ac-list nc pac))
        ((eq? pm '~~mv-define)      (handle~~mv-define-pm! ac-list nc pac))
        ((eq? pm 'case-lambda-bind)
         (handle:case-lambda-bind-pm! ac-list nc))
        ((memq pm '(~lambda-bind sublambda-bind-list-unmatched))
         (handle~lambda-bind-pm! ac-list nc pac))
        ((memq pm '(~defun-proc subdefun-unmatched))
         (handle~defun-proc-pm! ac-list nc pac))
        ((memq pm '(~sv-let sublet-sv-inner-unmatched))
         (handle~sv-let-pm! ac-list nc pac))
        ((memq pm '(~~let-sv sublet-sv-outer-unmatched sublet-sv-inner-end))
         (handle~~let-sv-pm! ac-list nc pac))
        ((memq pm '(~mv-let sublet-mv-inner-unmatched))
         (handle~mv-let-pm! ac-list nc pac))
        ((memq pm '(~~let-mv sublet-mv-outer-unmatched))
         (handle~~let-mv-pm! ac-list nc pac))
        ((memq pm '(~~~let-mv sublet-mv-outermost-unmatched
                              sublet-mv-outer-end))
         (handle~~~let-mv-pm! ac-list nc pac))
        ((memq pm '(~mv-define subdefine-mv-list-unmatched))
         (handle~mv-define-pm! ac-list nc pac))
        ((memq pm '(~mv-define subdefine-mv-list-unmatched))
         (handle~mv-define-pm! ac-list nc pac))
        ((memq pm '(~case-lambda subcase-lambda-inner-unmatched))
         (handle~case-lambda-pm! ac-list nc pac))
        ((memq pm '(~~case-lambda subcase-lambda-outer-unmatched))
         (handle~~case-lambda-pm! ac-list nc pac))
        ((memq pm '(~~~case-lambda subcase-lambda-outer-end))
         (handle~~~case-lambda-pm! ac-list nc pac))
        (else #f)))

;; (define (^try-key/opt-pm! ~mesg ~compound compound kind init-sym)
;;   ;; for #!key/#!optional objects (DSSSL extensions)
;;   (let ((ident-kind ((append-to-symbol "-ident") kind))
;;         (subcompound (->sub compound)))
;;     (let ((end-sub (->end subcompound))
;;           (ident-end (->end ident-kind))
;;           (ident-unmatched (->unmatched ident-kind))
;;           (unmatched-sub (->unmatched subcompound)))
;;       (let ((non-init-mesgs (list ~mesg end-sub ident-end))
;;             (maybe-init-mesgs (list unmatched-sub ~compound)))
;;         (lambda (ac-list nc pac pm)
;;           (cond ((memq pm non-init-mesgs)
;;                  (cond ((memc nc compound-begin-chars)
;;                         (begin-compound! ac-list nc compound))
;;                        ((memc nc whitespace-chars)
;;                         (cond ((char=? (get-char pac) #\.)
;;                                (let* ((rest (cdr ac-list))
;;                                       (ppac (car rest)))
;;                                  (cond ((atmosphere? ppac)
;;                                         (set-kind! pac 'dot)
;;                                         (adorn-char nc 'whitespace
;;                                                     '~rest))
;;                                        (else (adorn-char nc 'whitespace
;;                                                          ~mesg)))))
;;                               (else
;;                                (adorn-char nc 'whitespace ~mesg))))
;;                        ((and (not (char=? nc #\|))
;;                              (memc nc delim-chars))
;;                         (try-nc! ac-list nc))
;;                        ((char=? nc #\#)
;;                         (adorn-char nc kind '~~new-sharp))
;;                        (else ((^begin-bind kind) ac-list nc))))
;;                 ((memq pm maybe-init-mesgs)
;;                  (cond ((memc nc whitespace-chars)
;;                         (adorn-char nc 'whitespace ~mesg))
;;                        ((and (not (char=? nc #\|))
;;                              (memc nc delim-chars))
;;                         (try-nc! ac-list nc))
;;                        (else ((^begin-bind init-sym) ac-list nc))))
;;                 ((eq? pm kind)
;;                  (cond ((memc nc whitespace-chars)
;;                         (cond ((char=? (get-char pac) #\.)
;;                                (let* ((rest (cdr ac-list))
;;                                       (ppac (car rest)))
;;                                  (cond ((atmosphere? ppac)
;;                                         (set-kind! pac 'dot)
;;                                         (adorn-char nc 'whitespace
;;                                                     '~rest))
;;                                        (else (adorn-char nc 'whitespace
;;                                                          ~mesg)))))
;;                               (else
;;                                (adorn-char nc 'whitespace ~mesg))))
;;                        ((memc nc delim-chars) (try-nc! ac-list nc))
;;                        (else (adorn-char nc kind kind))))
;;                 ((eq? pm init-sym)
;;                  (cond ((memc nc delim-chars) (try-nc! ac-list nc))
;;                        (else (adorn-char nc init-sym init-sym))))
;;                 (else #f)))))))

;; (define try-key-pm!
;;   (^try-key/opt-pm!
;;    '~key '~key-compound 'key-compound 'key-param 'key-init-param))

;; (define try-opt-pm!
;;   (^try-key/opt-pm!
;;    '~opt '~opt-compound 'opt-compound 'opt-param 'opt-init-param))

;; (define (try-to-match-dsssl! ac-list nc pac pm)
;;   (let ((tested (chars-until ac-list '~~new-sharp)))
;;     (cond ((matches? "#!key" tested)
;;            (revise-until! ac-list 'sharp (length tested))
;;            (cond ((memc nc whitespace-chars)
;;                   (adorn-char nc 'whitespace '~key))
;;                  ((memc nc compound-begin-chars)
;;                   (begin-compound! ac-list nc 'key-compound))
;;                  (else (try-nc! ac-list nc))))
;;           ((matches? "#!optional" tested)
;;            (revise-until! ac-list 'sharp (length tested))
;;            (cond ((memc nc whitespace-chars)
;;                   (adorn-char nc 'whitespace '~opt))
;;                  ((memc nc compound-begin-chars)
;;                   (begin-compound! ac-list nc 'opt-compound))
;;                  (else (try-nc! ac-list nc))))
;;           ((matches? "#!rest" tested)
;;            (revise-until! ac-list 'sharp (length tested))
;;            (cond ((memc nc whitespace-chars)
;;                   (adorn-char nc 'whitespace '~rest))
;;                  (else (try-nc! ac-list nc))))
;;           (else #f))))

;; (define (handle~new-sharp! ac-list nc pac pm)
;;   (and (memq pm '(~new-sharp ~~new-sharp))
;;        (let* ((recents (chars-until ac-list '~~new-sharp))
;;               (tested (append recents (list nc))))
;;          (or (try-to-match-dsssl! ac-list nc pac pm)
;;              (cond ((char=? nc #\<)
;;                     (set-mesg! pac 'octothorpe)
;;                     (adorn-char nc 'default '~hs-begin))
;;                    ((could-match-one-of? dsssl-sharp-objects tested)
;;                     (adorn-char nc (get-kind pac) '~new-sharp))
;;                    ((memc nc delim-chars) (try-nc! ac-list nc))
;;                    (else (let ((prev-kind (get-kind pac)))
;;                            (adorn-char nc prev-kind prev-kind))))))))

;; (define (try-bind-pm! ac-list nc pac pm)
;;   (or (handle~new-sharp! ac-list nc pac pm)
;;       (try-key-pm! ac-list nc pac pm)
;;       (try-opt-pm! ac-list nc pac pm)
;;       (cond ((eq? pm '~rest)
;;              (cond ((memc nc whitespace-chars)
;;                     (adorn-char nc 'whitespace '~rest))
;;                    ((and (not (char=? nc #\|)) (memc nc delim-chars))
;;                     (try-nc! ac-list nc))
;;                    ((char=? nc #\#)
;;                     (adorn-char nc 'default '~~new-sharp))
;;                    (else ((^begin-bind 'rest-param) ac-list nc))))
;;             ((eq? pm 'rest-param)
;;              (cond ((memc nc whitespace-chars)
;;                     (adorn-char nc 'whitespace 'no-more-rest))
;;                    ((memc nc delim-chars)
;;                     (try-nc! ac-list nc))
;;                    (else (adorn-char nc 'rest-param 'rest-param))))
;;             ((memq pm '(no-more-rest rest-param-ident-end))
;;              (cond ((char=? nc #\#)
;;                     (adorn-char nc 'default '~~rest-sharp))
;;                    ((memc nc compound-end-chars)
;;                     (try-nc! ac-list nc))
;;                    ((memc nc whitespace-chars)
;;                     (adorn-char nc 'whitespace 'no-more-rest))
;;                    ((not (memc nc delim-chars))
;;                     (adorn-char nc 'invalid 'no-more-rest))
;;                    (else (try-nc! ac-list nc))))
;;             ((memq pm '(~rest-sharp ~~rest-sharp))
;;              (let ((tested (chars-until ac-list '~~rest-sharp)))
;;                (cond ((matches? "#!key" tested)
;;                       (revise-until! ac-list 'sharp (length tested))
;;                       (cond ((memc nc whitespace-chars)
;;                              (adorn-char nc 'whitespace '~key))
;;                             ((memc nc compound-begin-chars)
;;                              (begin-compound! ac-list nc 'key-compound))
;;                             (else (try-nc! ac-list nc))))
;;                      ((matches? "#!optional" tested)
;;                       (revise-until! ac-list 'sharp (length tested))
;;                       (cond ((memc nc whitespace-chars)
;;                              (adorn-char nc 'whitespace '~opt))
;;                             ((memc nc compound-begin-chars)
;;                              (begin-compound! ac-list nc 'opt-compound))
;;                             (else (try-nc! ac-list nc))))
;;                      ((could-match-one-of?
;;                        '("#!key" "#!optional") tested)
;;                       (adorn-char nc 'default '~rest-sharp))
;;                      ((memc nc delim-chars) (try-nc! ac-list nc))
;;                      (else (adorn-char nc 'invalid 'invalid)))))
;;             ((and (char=? nc #\#) (not (get-mesg pac))
;;                   (let ((looking (looking-at ac-list bind-mesgs)))
;;                     (and looking
;;                          (not (memq (car looking) '(case-lambda-rest
;;                                                     lambda-rest
;;                                                     named-let
;;                                                     sv-let
;;                                                     sv-define))))))
;;              (adorn-char nc 'default '~~new-sharp))
;;             ((not (memq pm bind-mesgs)) #f)
;;             ((and (memc nc whitespace-chars) (char=? (get-char pac) #\.))
;;              (let ((rest (cdr ac-list)))
;;                (when (and (not (null? rest))
;;                           (memq (get-kind (car rest)) atmosphere-kinds))
;;                  (set-kind! pac 'dot))
;;                (try-nc! ac-list nc)))
;;             ((memc nc delim-chars)
;;              (or (try-to-match-dsssl! ac-list nc pac pm)
;;                  (try-nc! ac-list nc)))
;;             (else (adorn-char nc pm pm)))))
