(define (^begin-bind kind)
  (let ((ident-kind ((append-to-symbol "-ident") kind)))
    (lambda (ac-list nc)
      (cond ((char=? nc #\|) (begin-symmetric ac-list nc ident-kind))
            ((memc nc '(#\' #\` #\,)) (try-nc! ac-list nc))
            (else (adorn-char nc kind kind))))))

(define begin-defun-proc       (^begin-bind 'defun-proc))
(define begin-defun-param      (^begin-bind 'defun-param))
(define begin-sv-define        (^begin-bind 'sv-define))
(define begin-mv-define        (^begin-bind 'mv-define))
(define begin-named-let        (^begin-bind 'named-let))
(define begin-optional-param   (^begin-bind 'optional-param))
(define begin-sv-let           (^begin-bind 'sv-let))
(define begin-mv-let           (^begin-bind 'mv-let))
(define begin-lambda-bind      (^begin-bind 'lambda-bind))
(define begin-lambda-rest      (^begin-bind 'lambda-rest))
(define begin-key-compound     (^begin-bind 'key-compound))
(define begin-opt-compound     (^begin-bind 'opt-compound))
(define begin-case-lambda-bind (^begin-bind 'case-lambda-bind))
(define begin-case-lambda-rest (^begin-bind 'case-lambda-rest))

(define (^try-key/opt-pm! ~mesg ~compound compound kind init-sym)
  ;; for #!key/#!optional objects (DSSSL extensions)
  (let ((ident-kind ((append-to-symbol "-ident") kind))
        (subcompound (->sub compound)))
    (let ((end-sub (->end subcompound))
          (ident-end (->end ident-kind))
          (ident-unmatched (->unmatched ident-kind))
          (unmatched-sub (->unmatched subcompound)))
      (let ((non-init-mesgs (list ~mesg end-sub ident-end))
            (maybe-init-mesgs (list unmatched-sub ~compound)))
        (lambda (ac-list nc pac pm)
          (cond ((memq pm non-init-mesgs)
                 (cond ((memc nc compound-begin-chars)
                        (begin-compound! ac-list nc compound))
                       ((memc nc whitespace-chars)
                        (cond ((char=? (get-char pac) #\.)
                               (let* ((rest (cdr ac-list))
                                      (ppac (car rest)))
                                 (cond ((atmosphere? ppac)
                                        (set-kind! pac 'dot)
                                        (adorn-char nc 'whitespace
                                                    '~rest))
                                       (else (adorn-char nc 'whitespace
                                                         ~mesg)))))
                              (else
                               (adorn-char nc 'whitespace ~mesg))))
                       ((and (not (char=? nc #\|))
                             (memc nc delim-chars))
                        (try-nc! ac-list nc))
                       ((char=? nc #\#)
                        (adorn-char nc kind '~~new-sharp))
                       (else ((^begin-bind kind) ac-list nc))))
                ((memq pm maybe-init-mesgs)
                 (cond ((memc nc whitespace-chars)
                        (adorn-char nc 'whitespace ~mesg))
                       ((and (not (char=? nc #\|))
                             (memc nc delim-chars))
                        (try-nc! ac-list nc))
                       (else ((^begin-bind init-sym) ac-list nc))))
                ((eq? pm kind)
                 (cond ((memc nc whitespace-chars)
                        (cond ((char=? (get-char pac) #\.)
                               (let* ((rest (cdr ac-list))
                                      (ppac (car rest)))
                                 (cond ((atmosphere? ppac)
                                        (set-kind! pac 'dot)
                                        (adorn-char nc 'whitespace
                                                    '~rest))
                                       (else (adorn-char nc 'whitespace
                                                         ~mesg)))))
                              (else
                               (adorn-char nc 'whitespace ~mesg))))
                       ((memc nc delim-chars) (try-nc! ac-list nc))
                       (else (adorn-char nc kind kind))))
                ((eq? pm init-sym)
                 (cond ((memc nc delim-chars) (try-nc! ac-list nc))
                       (else (adorn-char nc init-sym init-sym))))
                (else #f)))))))

(define try-key-pm!
  (^try-key/opt-pm!
   '~key '~key-compound 'key-compound 'key-param 'key-init-param))

(define try-opt-pm!
  (^try-key/opt-pm!
   '~opt '~opt-compound 'opt-compound 'opt-param 'opt-init-param))

(define (try-to-match-dsssl! ac-list nc pac pm)
  (let ((tested (chars-until ac-list '~~new-sharp)))
    (cond ((matches? "#!key" tested)
           (revise-until! ac-list 'sharp (length tested))
           (cond ((memc nc whitespace-chars)
                  (adorn-char nc 'whitespace '~key))
                 ((memc nc compound-begin-chars)
                  (begin-compound! ac-list nc 'key-compound))
                 (else (try-nc! ac-list nc))))
          ((matches? "#!optional" tested)
           (revise-until! ac-list 'sharp (length tested))
           (cond ((memc nc whitespace-chars)
                  (adorn-char nc 'whitespace '~opt))
                 ((memc nc compound-begin-chars)
                  (begin-compound! ac-list nc 'opt-compound))
                 (else (try-nc! ac-list nc))))
          ((matches? "#!rest" tested)
           (revise-until! ac-list 'sharp (length tested))
           (cond ((memc nc whitespace-chars)
                  (adorn-char nc 'whitespace '~rest))
                 (else (try-nc! ac-list nc))))
          (else #f))))

(define (handle~new-sharp! ac-list nc pac pm)
  (and (memq pm '(~new-sharp ~~new-sharp))
       (let* ((recents (chars-until ac-list '~~new-sharp))
              (tested (append recents (list nc))))
         (or (try-to-match-dsssl! ac-list nc pac pm)
             (cond ((char=? nc #\<)
                    (set-mesg! pac 'octothorpe)
                    (adorn-char nc 'default '~hs-begin))
                   ((could-match-one-of? dsssl-sharp-objects tested)
                    (adorn-char nc (get-kind pac) '~new-sharp))
                   ((memc nc delim-chars) (try-nc! ac-list nc))
                   (else (let ((prev-kind (get-kind pac)))
                           (adorn-char nc prev-kind prev-kind))))))))

(define (try-bind-pm! ac-list nc pac pm)
  (or (handle~new-sharp! ac-list nc pac pm)
      (try-key-pm! ac-list nc pac pm)
      (try-opt-pm! ac-list nc pac pm)
      (cond ((eq? pm '~rest)
             (cond ((memc nc whitespace-chars)
                    (adorn-char nc 'whitespace '~rest))
                   ((and (not (char=? nc #\|)) (memc nc delim-chars))
                    (try-nc! ac-list nc))
                   ((char=? nc #\#)
                    (adorn-char nc 'default '~~new-sharp))
                   (else ((^begin-bind 'rest-param) ac-list nc))))
            ((eq? pm 'rest-param)
             (cond ((memc nc whitespace-chars)
                    (adorn-char nc 'whitespace 'no-more-rest))
                   ((memc nc delim-chars)
                    (try-nc! ac-list nc))
                   (else (adorn-char nc 'rest-param 'rest-param))))
            ((memq pm '(no-more-rest rest-param-ident-end))
             (cond ((char=? nc #\#)
                    (adorn-char nc 'default '~~rest-sharp))
                   ((memc nc compound-end-chars)
                    (try-nc! ac-list nc))
                   ((memc nc whitespace-chars)
                    (adorn-char nc 'whitespace 'no-more-rest))
                   ((not (memc nc delim-chars))
                    (adorn-char nc 'invalid 'no-more-rest))
                   (else (try-nc! ac-list nc))))
            ((memq pm '(~rest-sharp ~~rest-sharp))
             (let ((tested (chars-until ac-list '~~rest-sharp)))
               (cond ((matches? "#!key" tested)
                      (revise-until! ac-list 'sharp (length tested))
                      (cond ((memc nc whitespace-chars)
                             (adorn-char nc 'whitespace '~key))
                            ((memc nc compound-begin-chars)
                             (begin-compound! ac-list nc 'key-compound))
                            (else (try-nc! ac-list nc))))
                     ((matches? "#!optional" tested)
                      (revise-until! ac-list 'sharp (length tested))
                      (cond ((memc nc whitespace-chars)
                             (adorn-char nc 'whitespace '~opt))
                            ((memc nc compound-begin-chars)
                             (begin-compound! ac-list nc 'opt-compound))
                            (else (try-nc! ac-list nc))))
                     ((could-match-one-of?
                       '("#!key" "#!optional") tested)
                      (adorn-char nc 'default '~rest-sharp))
                     ((memc nc delim-chars) (try-nc! ac-list nc))
                     (else (adorn-char nc 'invalid 'invalid)))))
            ((and (char=? nc #\#) (not (get-mesg pac))
                  (let ((looking (looking-at ac-list bind-mesgs)))
                    (and looking
                         (not (memq (car looking) '(case-lambda-rest
                                                    lambda-rest
                                                    named-let
                                                    sv-let
                                                    sv-define))))))
             (adorn-char nc 'default '~~new-sharp))
            ((not (memq pm bind-mesgs)) #f)
            ((and (memc nc whitespace-chars) (char=? (get-char pac) #\.))
             (let ((rest (cdr ac-list)))
               (when (and (not (null? rest))
                          (memq (get-kind (car rest)) atmosphere-kinds))
                 (set-kind! pac 'dot))
               (try-nc! ac-list nc)))
            ((memc nc delim-chars)
             (or (try-to-match-dsssl! ac-list nc pac pm)
                 (try-nc! ac-list nc)))
            (else (adorn-char nc pm pm)))))
