(define (rt-syntax? ac) (eq? (get-kind ac) 'rt-syntax))

(define (handle:else-pm! ac-list nc)
  (cond ((memc nc delim-chars) (try-nc! ac-list nc))
        (else (let* ((recents (chars-until ac-list '~~rt-syntax))
                     (tested (append recents (list nc))))
                (cond ((matches-one-of? runtime-syntax tested)
                       (revise-until! ac-list 'rt-syntax 4)
                       (adorn-char nc 'rt-syntax '~rt-syntax))
                      ((could-match-one-of? runtime-syntax tested)
                       (revise-until! ac-list 'default 4)
                       (adorn-char nc 'default '~rt-syntax))
                      (else (revise-until! ac-list 'default 4)
                            (try-nc! ac-list nc)))))))

(define (handle~rt-syntax! ac-list nc pac)
  (let* ((recents (chars-until ac-list '~~rt-syntax))
         (tested (append recents (list nc))))
    (cond ((matches? '(#\e #\l #\s #\e) tested)
           (let ((operator (rt-syntax-operator (up-list ac-list))))
             (cond ((matches-one-of? else-is-syntax-syntax operator)
                    (revise-until! ac-list 'aux-syntax 3)
                    (adorn-char nc 'aux-syntax 'else))
                   (else (adorn-char nc 'default '~rt-syntax)))))
          ((matches-one-of? runtime-syntax tested)
           (revise-until! ac-list 'rt-syntax '~~rt-syntax)
           (adorn-char nc 'rt-syntax '~rt-syntax))
          ((could-match-one-of? runtime-syntax tested)
           (revise-while! ac-list 'default rt-syntax?)
           (adorn-char nc 'default '~rt-syntax))
          ((and (char=? nc #\#) (= (length recents) 2))
           (set-mesg! pac '~repl-ref)
           (set-mesg! (cadr ac-list) 'octothorpe)
           (revise-until! ac-list 'repl-ref 'octothorpe)
           (adorn-char nc 'repl-ref '~repl-ref))
          ((memc nc whitespace-chars)
           (if (matches? recents '(#\# #\#))
               (begin (revise-until! ac-list 'repl-ref 2)
                      (adorn-char nc 'whitespace #f))
               (let* ((operator (rt-syntax-operator ac-list))
                      (mesg (cond
                             ((matches-one-of? sv-define-syntax operator)
                              '~sv-define)
                             ((matches? '(#\l #\e #\t) operator)
                              '~named/sv-let)
                             ((matches-one-of? sv-let-syntax operator)
                              '~~~let-sv)
                             ((matches-one-of? lambda-syntax operator)
                              '~~lambda-bind)
                             ((matches-one-of? mv-let-syntax operator)
                              '~~~~let-mv)
                             ((matches-one-of? mv-define-syntax operator)
                              '~~mv-define)
                             ((matches-one-of? case-lambda-syntax operator)
                              '~~~case-lambda)
                             ((matches-one-of? define-proc-syntax operator)
                              '~defproc-defun)
                             (else #f))))
                 (adorn-char nc 'whitespace mesg))))
          ((memc nc delim-chars)
           (when (and (char=? (get-char pac) #\#) (= (length recents) 2))
             (revise-until! ac-list 'repl-ref '2))
           (try-nc! ac-list nc))
          (else (revise-while! ac-list 'default rt-syntax?)
                (adorn-char nc 'default #f)))))

(define (~~rt-syntax? ac-list nc)
  (and (not (char=? nc #\#))
       (operator-position? ac-list)
       (could-match-one-of? runtime-syntax (list nc))))

(define (try-rt-syntax-pm! ac-list nc pac pm)
  (and (memq pm '(~rt-syntax ~~rt-syntax))
       (handle~rt-syntax! ac-list nc pac)))

(define (default+no-mesg/rt-syntax? ac)
  (and (eq? (get-kind ac) 'default)
       (let ((mesg (get-mesg ac)))
         (or (not mesg) (memq mesg '(~rt-syntax ~~rt-syntax))))))

(define (valid-keyword? ac-list nc pc)
  (and (char=? pc #\:) (memc nc delim-chars)
       (let ((rest (cdr ac-list)))
         (and (not (null? rest))
              (not (memc (get-char (car rest)) delim-chars))))))

(define (try-context! ac-list nc pac)
  (let ((pc (get-char pac)))
    (cond ((not pc) #f)
          ((and (char=? pc #\.) (memc nc whitespace-chars))
           (let ((rest (cdr ac-list)))
             (unless (null? rest)
               (when (memq (get-kind (car rest)) atmosphere-kinds)
                 (set-kind! pac 'dot))))
           (try-nc! ac-list nc))
          ((valid-keyword? ac-list nc pc)
           (revise-while! ac-list 'keyword default+no-mesg/rt-syntax?)
           (try-nc! ac-list nc))
          ((and (not (char=? nc #\|)) (memc nc delim-chars))
           (try-nc! ac-list nc))
          ((~~rt-syntax? ac-list nc)
           (if (matches-one-of? runtime-syntax (list nc))
               (adorn-char nc 'rt-syntax '~~rt-syntax)
               (adorn-char nc 'default '~~rt-syntax)))
          (else #f))))
