(define (rt-syntax? ac) (eq? (get-kind ac) 'rt-syntax))

(define (handle~rt-syntax! ac-list nc pac)
  (let* ((recents (chars-until ac-list '~~rt-syntax))
         (tested (append recents (list nc))))
    (cond ((matches-one-of? runtime-syntax tested)
           (revise-until! ac-list 'rt-syntax '~~rt-syntax)
           (adorn-char nc 'rt-syntax '~rt-syntax))
          ((could-match-one-of? runtime-syntax tested)
           (revise-while! ac-list 'default rt-syntax?)
           (adorn-char nc 'default '~rt-syntax))
          ((and (char=? nc #\#) (= (length recents) 2))
           (set-mesg! pac '~repl-ref)
           (set-mesg! (cadr ac-list) 'octothorpe)
           (revise-until! ac-list 'repl-ref 'octothorpe)
           (adorn-char nc 'repl-ref '~repl-ref))
          ((memc nc whitespace-chars)
           (let* ((operator (rt-syntax-operator ac-list))
                  (mesg (cond ((matches-one-of? sv-define-syntax operator)
                               '~sv-define)
                              ((matches? '(#\l #\e #\t) operator)
                               '~named/sv-let)
                              ((matches-one-of? sv-let-syntax operator)
                               '~~~let-sv)
                              ((matches-one-of? lambda-syntax operator)
                               '~lambda-bind/rest)
                              ((matches-one-of? mv-let-syntax operator)
                               '~~~~let-mv)
                              ((matches-one-of? mv-define-syntax operator)
                               '~~mv-define)
                              ((matches-one-of? case-lambda-syntax operator)
                               '~~~case-lambda)
                              (else #f))))
             (adorn-char nc 'whitespace mesg)))
          ((memc nc delim-chars)
           (when (and (char=? (get-char pac) #\#) (= (length recents) 2))
             (revise-until! ac-list 'repl-ref '2))
           (try-nc! ac-list nc))
          (else (revise-while! ac-list 'default rt-syntax?)
                (adorn-char nc 'default #f)))))

(define (try-rt-syntax-pm! ac-list nc pac pm)
  (and (memq pm '(~rt-syntax ~~rt-syntax))
       (handle~rt-syntax! ac-list nc pac)))

(define (try-else-pm! ac-list nc pm)
  (cond ((memq pm '(~else ~~else))
         (let ((tested (append (chars-until ac-list '~~else) (list nc))))
           (cond ((matches? '(#\e #\l #\s #\e) tested)
                  (revise-until! ac-list 'aux-syntax 3)
                  (adorn-char nc 'aux-syntax 'else))
                 ((could-match? '(#\e #\l #\s #\e) tested)
                  (adorn-char nc 'default '~else))
                 (else (try-nc! ac-list nc)))))
        ((eq? pm 'else)
         (unless (memc nc delim-chars)
           (revise-until! ac-list 'default 4))
         (try-nc! ac-list nc))
        (else #f)))

(define (default+no-mesg-or-rt-syntax? ac)
  (and (eq? (get-kind ac) 'default)
       (let ((mesg (get-mesg ac)))
         (or (not mesg) (memq mesg '(~rt-syntax ~~rt-syntax))))))

(define (try-context! ac-list nc pac)
  (let ((pc (get-char pac)))
    (cond ((not pc) #f)
          ((and (char=? pc #\.) (memc nc whitespace-chars))
           (let ((rest (cdr ac-list)))
             (unless (null? rest)
               (when (memq (get-kind (car rest)) atmosphere-kinds)
                 (set-kind! pac 'dot))))
           (try-nc! ac-list nc))
          ((and (char=? pc #\=) (char=? nc #\>) (not (get-mesg pac))
                (not (operator-position? ac-list))
                (matches-one-of? else-is-syntax-syntax
                                 (rt-syntax-operator (up-list ac-list))))
           (let ((rest (cdr ac-list)))
             (cond ((and (not (null? rest))
                         (memq (get-kind (car rest)) atmosphere-kinds))
                    (set-kind! pac 'aux-syntax)
                    (adorn-char nc 'aux-syntax #f))
                   (else (try-nc! ac-list nc)))))
          ((valid-keyword? ac-list nc pc)
           (revise-while! ac-list 'keyword default+no-mesg-or-rt-syntax?)
           (try-nc! ac-list nc))
          ((and (not (char=? nc #\|)) (memc nc delim-chars))
           (try-nc! ac-list nc))
          ;; ((define-variable-bind? ac-list) (begin-sv-define ac-list nc))
          ;; ((defun-param-bind? ac-list) (begin-defun-param ac-list nc))
          ;; ((defun-proc-bind? ac-list) (begin-defun-proc ac-list nc))
          ;; ((sv-let-bind? ac-list) (begin-sv-let ac-list nc))
          ;; ((named-let-var? ac-list) (begin-named-let ac-list nc))
          ;; ((lambda-bind? ac-list) (begin-lambda-bind ac-list nc))
          ;; ((lambda-rest? ac-list) (begin-lambda-rest ac-list nc))
          ;; ((mv-let-bind? ac-list) (begin-mv-let ac-list nc))
          ;; ((define-values-bind? ac-list) (begin-mv-define ac-list nc))
          ;; ((case-lambda-bind? ac-list) (begin-case-lambda-bind ac-list nc))
          ;; ((case-lambda-rest? ac-list) (begin-case-lambda-rest ac-list nc))
          ((~~rt-syntax? ac-list nc)
           (if (matches-one-of? runtime-syntax (list nc))
               (adorn-char nc 'rt-syntax '~~rt-syntax)
               (adorn-char nc 'default '~~rt-syntax)))
          ((~~else? ac-list nc) (adorn-char nc 'default '~~else))
          (else #f))))
