;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define (revise-numeric/maybe-invalidate! ac-list nc)
  (let loop ((rest ac-list) (previous-ac #f))
    (if (null? rest)
        (cond ((and previous-ac (char=? (get-char previous-ac) #\#))
               (if (memc nc delim-chars)
                   (try-nc! ac-list nc)
                   (adorn-char nc 'invalid 'invalid)))
              ((memc nc delim-chars) (try-nc! ac-list nc))
              (else (adorn-char nc 'default #f)))
        (let ((ac (car rest)))
          (cond ((eq? (get-kind ac) 'number)
                 (set-kind! ac 'default)
                 (loop (cdr rest) ac))
                (else (loop '() previous-ac)))))))

(define (^try-radix-pm! radix-chars mesg# +/-mesg mesg)
  (lambda (ac-list nc)
    (cond ((memc-ci nc radix-chars) (adorn-char nc 'number mesg))
          ((char=? nc #\#) (adorn-char nc 'number mesg#))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number +/-mesg))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-bin-pm! (^try-radix-pm! binary-chars 'bin# 'bin-real+/- 'bin/real))
(define try-oct-pm! (^try-radix-pm! octal-chars 'oct# 'oct-real+/- 'oct/real))
(define try-hex-pm!
  (^try-radix-pm! hexadecimal-chars 'hex# 'hex-real+/- 'hex/real))

(define (try-dec-pm! ac-list nc)
  (cond ((char=? nc #\.) (adorn-char nc 'number 'dec-real))
        (else ((^try-radix-pm! decimal-chars 'dec# 'dec.real+/- 'dec.real)
               ac-list nc))))

(define (^try-radix#pm! ~mesg i~mesg)
  (lambda (ac-list nc)
    (cond ((char-ci=? nc #\e) (adorn-char nc 'number ~mesg))
          ((char-ci=? nc #\i) (adorn-char nc 'number i~mesg))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-bin#pm! (^try-radix#pm! '~bin-real 'i~bin-real))
(define try-dec#pm! (^try-radix#pm! '~dec.real 'i~dec.real))
(define try-oct#pm! (^try-radix#pm! '~oct-real 'i~oct-real))
(define try-hex#pm! (^try-radix#pm! '~hex-real 'i~hex-real))

(define (^try-real-pm! radix-chars real-mesg)
  (lambda (ac-list nc)
    (cond ((memc-ci nc radix-chars) (adorn-char nc 'number real-mesg))
          ((memc nc delim-chars)
           (if (rectangular? ac-list)
               (revise-numeric/maybe-invalidate! ac-list nc)
               (try-nc! ac-list nc)))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
          ((char-ci=? nc #\i) (adorn-char nc 'number 'rectangular-end))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-bin-real-pm! (^try-real-pm! binary-chars 'bin-real))
(define try-oct-real-pm! (^try-real-pm! octal-chars 'oct-real))
(define try-hex-real-pm! (^try-real-pm! hexadecimal-chars 'hex-real))
(define try~bin-real-pm!
  (^try-real-pm! (append '(#\+ #\-) binary-chars) 'bin-real))
(define try~oct-real-pm!
  (^try-real-pm! (append '(#\+ #\-) octal-chars) 'oct-real))
(define try~hex-real-pm!
  (^try-real-pm! (append '(#\+ #\-) hexadecimal-chars) 'hex-real))

(define (try~dec.real-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec.real))
        ((memc nc '(#\+ #\-)) (adorn-char nc 'number 'dec.real+/-))
        ((char=? nc #\.) (adorn-char nc 'number '~dec-real))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

;==============================================================================
(define (^try-radix+/-pm! radix-chars next/sym /sym)
  (lambda (ac-list nc)
    (cond ((memc-ci nc radix-chars) (adorn-char nc 'number next/sym))
          ((memc nc delim-chars) (try-nc! ac-list nc))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
          ((char=? nc #\/) (adorn-char nc 'number /sym))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-hex+/-pm! (^try-radix+/-pm! hexadecimal-chars 'hex/real 'hex/))
(define try-oct+/-pm! (^try-radix+/-pm! octal-chars 'oct/real 'oct/))
(define try-bin+/-pm! (^try-radix+/-pm! binary-chars 'bin/real 'bin/))
;==============================================================================
(define (^try-radix/pm! radix-chars sym)
  (lambda (ac-list nc)
    (cond ((memc-ci nc radix-chars) (adorn-char nc 'number sym))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
          ((memc nc delim-chars) (revise-numeric/maybe-invalidate! ac-list nc))
          (else (let ((ac (revise-numeric/maybe-invalidate! ac-list nc)))
                  (set-kind! ac 'invalid)
                  (set-mesg! ac 'invalid)
                  ac)))))

(define try-hex/pm! (^try-radix/pm! hexadecimal-chars 'hex-real))
(define try-oct/pm! (^try-radix/pm! octal-chars 'oct-real))
(define try-bin/pm! (^try-radix/pm! binary-chars 'bin-real))
;==============================================================================
(define (try-dec.real+/-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec.real))
        ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
        ((char=? nc #\.) (adorn-char nc 'number '~dec-real))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (^try-exactness-pm! mesg# +/-mesg)
  (lambda (ac-list nc)
    (cond ((char=? nc #\#) (adorn-char nc 'number mesg#))
          ((char=? nc #\.) (adorn-char nc 'number 'dec-real))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number +/-mesg))
          ((memc nc decimal-chars) (adorn-char nc 'number 'dec.real))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-exact-pm! (^try-exactness-pm! 'exact# '~dec.real))
(define try-inexact-pm! (^try-exactness-pm! 'inexact# '~inf/nan/dec.real))

(define (try-exact#pm! ac-list nc)
  (cond ((char-ci=? nc #\b) (adorn-char nc 'number '~bin-real))
        ((char-ci=? nc #\d) (adorn-char nc 'number '~dec.real))
        ((char-ci=? nc #\o) (adorn-char nc 'number '~oct-real))
        ((char-ci=? nc #\x) (adorn-char nc 'number '~hex-real))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (try-inexact#pm! ac-list nc)
  (cond ((char-ci=? nc #\b) (adorn-char nc 'number 'i~bin-real))
        ((char-ci=? nc #\d) (adorn-char nc 'number 'i~dec.real))
        ((char-ci=? nc #\o) (adorn-char nc 'number 'i~oct-real))
        ((char-ci=? nc #\x) (adorn-char nc 'number 'i~hex-real))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (^try-i~real-pm! radix-chars real-mesg +/-mesg)
  (lambda (ac-list nc)
    (cond ((memc-ci nc radix-chars) (adorn-char nc 'number real-mesg))
          ((memc nc '(#\+ #\-)) (adorn-char nc 'number +/-mesg))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try-i~bin-real-pm!
  (^try-i~real-pm! binary-chars 'bin-real '~inf/nan/bin-real))
(define try-i~oct-real-pm!
  (^try-i~real-pm! octal-chars 'oct-real '~inf/nan/oct-real))
(define try-i~hex-real-pm!
  (^try-i~real-pm! hexadecimal-chars 'hex-real '~inf/nan/hex-real))

(define (try-i~dec.real-pm! ac-list nc)
  (if (char=? nc #\.)
      (adorn-char nc 'number '~dec-real)
      ((^try-i~real-pm! decimal-chars 'dec.real '~inf/nan/dec.real)
       ac-list nc)))

(define (^try~inf/nan/real-pm! radix-chars real-mesg)
  (lambda (ac-list nc)
    (cond ((char-ci=? nc #\i)
           (revise-until! ac-list 'number 1)
           (adorn-char nc 'number '~inf/rectangular-end))
          ((char-ci=? nc #\n)
           (revise-until! ac-list 'number 1)
           (adorn-char nc 'number '~nan))
          ((memc-ci nc radix-chars)
           (revise-until! ac-list 'number 1)
           (adorn-char nc 'number real-mesg))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define try~inf/nan/bin-pm! (^try~inf/nan/real-pm! binary-chars 'bin-real))
(define try~inf/nan/oct-pm! (^try~inf/nan/real-pm! octal-chars 'oct-real))
(define try~inf/nan/hex-pm!
  (^try~inf/nan/real-pm! hexadecimal-chars 'hex-real))

(define (try~inf/nan/dec-pm! ac-list nc)
  (cond ((char=? nc #\.)
         (revise-until! ac-list 'number 1)
         (adorn-char nc 'number '~dec-real))
        (else ((^try~inf/nan/real-pm! decimal-chars 'dec.real) ac-list nc))))

(define (try~dec-real-pm! ac-list nc)
  (cond ((memc nc decimal-chars)
         (revise-until! ac-list 'number 1)
         (adorn-char nc 'number 'dec-real))
        ((memc nc whitespace-chars)
         (let ((rest (cdr ac-list)))
           (if (null? rest)
               (revise-numeric/maybe-invalidate! ac-list nc)
               (cond ((atmosphere? (car rest))
                      (revise-until! ac-list 'dot 1)
                      (try-nc! ac-list nc))
                     (else (revise-numeric/maybe-invalidate! ac-list nc))))))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (^try~inf/nan-pm! ~mesg mesg goal-string)
  (lambda (ac-list nc)
    (let* ((recents (chars-while ac-list ~mesg))
           (tested (map char-downcase (append recents (list nc)))))
      (cond ((matches? goal-string tested) (adorn-char nc 'number mesg))
            ((could-match? goal-string tested) (adorn-char nc 'number ~mesg))
            (else (revise-numeric/maybe-invalidate! ac-list nc))))))

(define try~inf-pm! (^try~inf/nan-pm! '~inf 'inf "inf.0"))
(define try~nan-pm! (^try~inf/nan-pm! '~nan 'nan "nan.0"))

(define (try~inf-pm! ac-list nc)
  (let* ((recents (chars-while ac-list '~inf))
         (tested (map char-downcase (append recents (list nc)))))
    (cond ((matches? "inf.0" tested) (adorn-char nc 'number 'inf))
          ((could-match? "inf.0" tested) (adorn-char nc 'number '~inf))
          (else (revise-numeric/maybe-invalidate! ac-list nc)))))

(define (try-dec.real-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec.real))
        ((memc nc delim-chars)
         (if (rectangular? ac-list)
             (revise-numeric/maybe-invalidate! ac-list nc)
             (try-nc! ac-list nc)))        
        ((memc-ci nc '(#\e #\s #\f #\d #\l)) (adorn-char nc 'number '~dec-end))
        ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
        ((memc nc '(#\. #\/)) (adorn-char nc 'number 'dec-real))
        ((char-ci=? nc #\i) (adorn-char nc 'number 'rectangular-end))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (try-dec-real-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec-real))
        ((memc nc delim-chars)
         (if (rectangular? ac-list)
             (revise-numeric/maybe-invalidate! ac-list nc)
             (try-nc! ac-list nc)))
        ((memc-ci nc '(#\e #\s #\f #\d #\l)) (adorn-char nc 'number '~dec-end))
        ((memc nc '(#\+ #\-)) (adorn-char nc 'number '~rectangular))
        ((char-ci=? nc #\i) (adorn-char nc 'number 'rectangular-end))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (try~dec-end-pm! ac-list nc)
  (cond ((memc nc '(#\+ #\-)) (adorn-char nc 'number 'dec-end+/-))
        ((memc nc decimal-chars) (adorn-char nc 'number 'dec-end))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (try-dec-end+/-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec-end))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (try-dec-end-pm! ac-list nc)
  (cond ((memc nc decimal-chars) (adorn-char nc 'number 'dec-end))
        ((memc nc delim-chars)
         (if (rectangular? ac-list)
             (revise-numeric/maybe-invalidate! ac-list nc)
             (try-nc! ac-list nc)))
        ((char-ci=? nc #\i) (adorn-char nc 'number 'rectangular-end))
        (else (revise-numeric/maybe-invalidate! ac-list nc))))

(define (rectangular? ac-list)
  (let loop ((rest ac-list))
    (and (not (null? rest))
         (let ((ac (car rest)))
           (and (eq? (get-kind ac) 'number)
                (or (eq? (get-mesg ac) '~rectangular)
                    (loop (cdr rest))))))))

(define (get-constraint-mesg ac-list)
  (guard (signal ((eq? signal 'invalid) 'invalid))
    (let ((numeric-chars (let loop ((rest (cdr ac-list)) (numerics '()))
                           (if (null? rest)
                               numerics
                               (let ((ac (car rest)))
                                 (if (eq? (get-kind ac) 'number)
                                     (if (eq? (get-mesg ac) '~rectangular)
                                         (raise 'invalid)
                                         (loop (cdr rest) (cons ac numerics)))
                                     numerics))))))
      (let loop ((numerics numeric-chars))
        (let ((mesg (get-mesg (car numerics))))
          (cond ((memq mesg '(dec.real dec-real ~inf ~nan)) '~inf/nan/dec.real)
                ((eq? mesg 'hex-real) '~inf/nan/hex-real)
                ((eq? mesg 'oct-real) '~inf/nan/oct-real)
                ((eq? mesg 'bin-real) '~inf/nan/bin-real)
                (else (loop (cdr numerics)))))))))

(define (try~inf/rectangular-end-pm! ac-list nc)
  (cond ((memc nc delim-chars) (try-nc! ac-list nc))
        ((char-ci=? nc #\n)
         (set-mesg! (car ac-list) '~inf)
         (adorn-char nc 'number '~inf))
        (else (let ((ac (revise-numeric/maybe-invalidate! ac-list nc)))
                (set-kind! ac 'invalid)
                (set-mesg! ac 'invalid)
                ac))))

(define (try~rectangular-pm! ac-list nc pm)
  (let ((constraint (get-constraint-mesg ac-list)) (pac (car ac-list)))
    (cond ((eq? constraint '~inf/nan/dec.real)
           (set-mesg! pac '~inf/nan/dec.real)
           (let ((ac (car (adorn! nc ac-list))))
             (set-mesg! pac '~rectangular)
             (when (eq? (get-mesg ac) '~inf)
               (set-mesg! ac '~inf/rectangular-end))
             ac))
          ((eq? constraint '~inf/nan/hex-real)
           (cond ((char-ci=? nc '#\i) (adorn-char nc 'number '~inf))
                 ((char-ci=? nc '#\n) (adorn-char nc 'number '~nan))
                 ((memc nc delim-chars)
                  (revise-numeric/maybe-invalidate! ac-list nc))
                 (else (set-mesg! pac 'hex)
                       (let ((ac (car (adorn! nc ac-list))))
                         (set-mesg! pac '~rectangular)
                         ac))))
          ((eq? constraint '~inf/nan/oct-real)
           (cond ((char-ci=? nc '#\i) (adorn-char nc 'number '~inf))
                 ((char-ci=? nc '#\n) (adorn-char nc 'number '~nan))
                 ((memc nc delim-chars)
                  (revise-numeric/maybe-invalidate! ac-list nc))
                 (else (set-mesg! pac 'oct)
                       (let ((ac (car (adorn! nc ac-list))))
                         (set-mesg! pac '~rectangular)
                         ac))))
          ((eq? constraint '~inf/nan/bin-real)
           (cond ((char-ci=? nc '#\i) (adorn-char nc 'number '~inf))
                 ((char-ci=? nc '#\n) (adorn-char nc 'number '~nan))
                 ((memc nc delim-chars)
                  (revise-numeric/maybe-invalidate! ac-list nc))
                 (else (set-mesg! pac 'bin)
                       (let ((ac (car (adorn! nc ac-list))))
                         (set-mesg! pac '~rectangular)
                         ac))))
          ((eq? constraint 'invalid) (adorn-char nc 'invalid 'invalid))
          (else (error "Unexpected constraint mesg" constraint)))))

(define (try-numeric-pm! ac-list nc pm)
  (cond ((eq? pm 'exact) (try-exact-pm! ac-list nc))
        ((eq? pm 'exact#) (try-exact#pm! ac-list nc))
        ((eq? pm 'inexact) (try-inexact-pm! ac-list nc))
        ((eq? pm 'inexact#) (try-inexact#pm! ac-list nc))
        ((eq? pm 'bin) (try-bin-pm! ac-list nc))
        ((eq? pm 'bin#) (try-bin#pm! ac-list nc))
        ((eq? pm '~bin-real) (try~bin-real-pm! ac-list nc))
        ((eq? pm 'bin-real) (try-bin-real-pm! ac-list nc))
        ((memq pm '(bin/real bin-real+/-)) (try-bin+/-pm! ac-list nc))
        ((eq? pm 'bin/) (try-bin/pm! ac-list nc))
        ((eq? pm 'i~bin-real) (try-i~bin-real-pm! ac-list nc))
        ((eq? pm '~inf/nan/bin-real) (try~inf/nan/bin-pm! ac-list nc))
        ((eq? pm 'oct) (try-oct-pm! ac-list nc))
        ((eq? pm 'oct#) (try-oct#pm! ac-list nc))
        ((eq? pm '~oct-real) (try~oct-real-pm! ac-list nc))
        ((eq? pm 'oct-real) (try-oct-real-pm! ac-list nc))
        ((memq pm '(oct/real oct-real+/-)) (try-oct+/-pm! ac-list nc))
        ((eq? pm 'oct/) (try-oct/pm! ac-list nc))
        ((eq? pm 'i~oct-real) (try-i~oct-real-pm! ac-list nc))
        ((eq? pm '~inf/nan/oct-real) (try~inf/nan/oct-pm! ac-list nc))
        ((eq? pm 'dec) (try-dec-pm! ac-list nc))
        ((eq? pm 'dec#) (try-dec#pm! ac-list nc))
        ((eq? pm '~dec.real) (try~dec.real-pm! ac-list nc))
        ((eq? pm 'dec.real+/-) (try-dec.real+/-pm! ac-list nc))
        ((eq? pm '~dec-real) (try~dec-real-pm! ac-list nc))
        ((eq? pm 'dec.real) (try-dec.real-pm! ac-list nc))
        ((eq? pm 'dec-real) (try-dec-real-pm! ac-list nc))
        ((eq? pm '~dec-end) (try~dec-end-pm! ac-list nc))
        ((eq? pm 'dec-end+/-) (try-dec-end+/-pm! ac-list nc))
        ((eq? pm 'dec-end) (try-dec-end-pm! ac-list nc))
        ((eq? pm 'i~dec.real) (try-i~dec.real-pm! ac-list nc))
        ((eq? pm '~inf/nan/dec.real) (try~inf/nan/dec-pm! ac-list nc))
        ((eq? pm 'hex) (try-hex-pm! ac-list nc))
        ((eq? pm 'hex#) (try-hex#pm! ac-list nc))
        ((eq? pm '~hex-real) (try~hex-real-pm! ac-list nc))
        ((eq? pm 'hex-real) (try-hex-real-pm! ac-list nc))
        ((memq pm '(hex/real hex-real+/-)) (try-hex+/-pm! ac-list nc))
        ((eq? pm 'hex/) (try-hex/pm! ac-list nc))
        ((eq? pm 'i~hex-real) (try-i~hex-real-pm! ac-list nc))
        ((eq? pm '~inf/nan/hex-real) (try~inf/nan/hex-pm! ac-list nc))
        ((eq? pm '~inf) (try~inf-pm! ac-list nc))
        ((eq? pm '~nan) (try~nan-pm! ac-list nc))
        ((eq? pm '~rectangular) (try~rectangular-pm! ac-list nc pm))
        ((eq? pm '~inf/rectangular-end)
         (try~inf/rectangular-end-pm! ac-list nc))
        ((eq? pm 'rectangular-end)
         (cond ((memc nc delim-chars) (try-nc! ac-list nc))
               (else (let ((ac (revise-numeric/maybe-invalidate! ac-list nc)))
                       (set-kind! ac 'invalid)
                       (set-mesg! ac 'invalid)
                       ac))))
        ((memq pm '(inf nan))
         (cond ((memc nc delim-chars)
                (if (rectangular? ac-list)
                    (revise-numeric/maybe-invalidate! ac-list nc)
                    (try-nc! ac-list nc)))
               ((char-ci=? nc #\i) (adorn-char nc 'number 'rectangular-end))
               ((memc nc '(#\+ #\-))
                (if (rectangular? ac-list)
                    (let ((ac (revise-numeric/maybe-invalidate! ac-list nc)))
                      (set-kind! ac 'invalid)
                      (set-mesg! ac 'invalid)
                      ac)
                    (adorn-char nc 'number '~rectangular)))
               (else (revise-numeric/maybe-invalidate! ac-list nc))))
        (else #f)))
