(define (^revise-if-complete kind ~mesg strings)
  (lambda (ac-list nc)
    (let* ((tested (append (chars-until ac-list 'octothorpe) (list nc)))
           (matched (backmatch-one-of strings tested)))
      (cond (matched (revise-until! ac-list kind (- (length matched) 1))
                     (adorn-char nc kind kind))
            ((could-match-one-of? strings tested)
             (adorn-char nc 'default ~mesg))
            ((memc nc delim-chars) (try-nc! ac-list nc))
            (else (adorn-char nc 'invalid 'invalid))))))

(define (try-boolean/hvector-pm! ac-list nc pm)
  (define (handle~f/false/fvector! ac-list nc)
    (cond ((memc nc delim-chars) (try-nc! ac-list nc))
          ((char=? nc #\a)
           (revise-until! ac-list 'default 2)
           (handle~false! ac-list nc))
          (else (let* ((recents (chars-until ac-list 2))
                       (tested (append recents (list nc))))
                  (cond ((could-match-one-of? fvector-strings tested)
                         (revise-until! ac-list 'default 2)
                         (handle~fvector! ac-list nc))
                        (else (adorn-char nc 'invalid 'invalid)))))))
  (define (^handle~hvector! ~mesg prefix-strings)
    (define (hvector-char-list->symbol cl)
      (string->symbol (list->string (append
                                     (reverse (cdr (reverse (cdr cl))))
                                     '(#\v #\e #\c #\t #\o #\r)))))
    (lambda (ac-list nc)
      (let* ((recents (chars-until ac-list 'octothorpe))
             (tested (append recents (list nc)))
             (matched (backmatch-one-of prefix-strings tested)))
        (cond (matched (let ((distance (- (length matched) 1))
                             (kind (hvector-char-list->symbol matched)))
                         (revise-until! ac-list kind distance)
                         (begin-compound! ac-list nc kind)))
              ((could-match-one-of? prefix-strings tested)
               (adorn-char nc 'default ~mesg))
              ((memc nc delim-chars) (try-nc! ac-list nc))
              (else (adorn-char nc 'invalid 'invalid))))))
  (define handle~false! (^revise-if-complete 'false '~false '("#false")))
  (define handle~true! (^revise-if-complete 'true '~true '("#true")))
  (define handle~fvector! (^handle~hvector! '~fvector fvector-strings))
  (define handle~svector! (^handle~hvector! '~svector svector-strings))
  (define handle~uvector! (^handle~hvector! '~uvector uvector-strings))
  (define (handle~t! ac-list nc)
    (cond ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (revise-until! ac-list 'default 2)
                (handle~true! ac-list nc))))
  (cond ((eq? pm '~f/false/fvector) (handle~f/false/fvector! ac-list nc))
        ((eq? pm '~false)           (handle~false! ac-list nc))
        ((eq? pm '~fvector)         (handle~fvector! ac-list nc))
        ((eq? pm '~svector)         (handle~svector! ac-list nc))
        ((eq? pm '~t)               (handle~t! ac-list nc))
        ((eq? pm '~true)            (handle~true! ac-list nc))
        ((eq? pm '~uvector)         (handle~uvector! ac-list nc))
        ((memq pm '(false true))    (need-delim! ac-list nc 'octothorpe))
        (else #f)))

(define (try-box-pm! ac-list nc pm) (and (eq? pm 'box) (try-nc! ac-list nc)))

(define (try-char-pm! ac-list nc pac pm)
  (define (handle~char-1! ac-list nc)
    (adorn-char nc 'char-body (cond ((char=? nc #\x) '~char-x)
                                    ((char=? nc #\U) '~char-U)
                                    ((char=? nc #\u) '~char-u)
                                    (else '~char-2))))
  (define (handle~char-x! ac-list nc)
    (define (~char-x-mesg? ac) (eq? (get-mesg ac) '~char-x))
    (cond ((memc nc delim-chars) (try-nc! ac-list nc))
          ((memc-ci nc hexadecimal-chars)
           (adorn-char nc 'char-body '~char-x))
          (else (revise-while! ac-list 'char ~char-x-mesg?)
                (adorn-char nc 'invalid 'invalid))))
  (define (^handle~char-Uu! ~mesg mesg)
    (define target (if (eq? mesg 'char-U) 8 4))
    (lambda (ac-list nc)
      (cond ((memc nc delim-chars) (try-nc! ac-list nc))
            ((memc-ci nc hexadecimal-chars)
             (let ((dist (distance-until ac-list '~char-1)))
               (cond ((= dist 1)
                      (revise-until! ac-list 'char 1)
                      (adorn-char nc 'char ~mesg))
                     ((> target dist) (adorn-char nc 'char ~mesg))
                     ((= target dist)
                      (revise-until! ac-list 'char-body dist)
                      (adorn-char nc 'char-body mesg))
                     (else (revise-until! ac-list 'char (+ target 1))
                           (adorn-char nc 'invalid 'invalid)))))
            (else (adorn-char nc 'invalid 'invalid)))))
  (define handle~char-U! (^handle~char-Uu! '~char-U 'char-U))
  (define handle~char-u! (^handle~char-Uu! '~char-u 'char-u))
  (define (handle~char-2! ac-list nc)
    (cond ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (set-kind! pac 'char)
                (let* ((recents (chars-until ac-list 3))
                       (tested (append recents (list nc))))
                  (if (could-match-one-of? long-named-chars tested)
                      (adorn-char nc 'char '~char-3)
                      (adorn-char nc 'invalid 'invalid))))))
  (define (handle~char-3! ac-list nc)
    (if (memc nc delim-chars)
        (try-nc! ac-list nc)
        (let* ((recents (append (chars-until ac-list 4)))
               (tested (append recents (list nc))))
          (cond ((matches? "#\\tab" tested)
                 (revise-until! ac-list 'char-body '~char-2)
                 (adorn-char nc 'char-body 'named-char))
                ((matches-one-of? short-named-chars tested)
                 (revise-until! ac-list 'char-body '~char-2)
                 (adorn-char nc 'char-body '~char-4))
                ((could-match-one-of? long-named-chars tested)
                 (adorn-char nc 'char '~named-char))
                (else (adorn-char nc 'invalid 'invalid))))))
  (define (handle~char-4! ac-list nc)
    (cond ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (revise-until! ac-list 'char 4)
                (handle~named-char! ac-list nc))))
  (define (handle~named-char! ac-list nc)
    (if (memc nc delim-chars)
        (try-nc! ac-list nc)
        (let* ((recents (append (chars-until ac-list 'octothorpe)))
               (tested (append recents (list nc)))
               (matched (backmatch-one-of long-named-chars tested)))
          (cond (matched (revise-until! ac-list 'char-body '~char-2)
                         (adorn-char nc 'char-body 'named-char))
                ((could-match-one-of? long-named-chars tested)
                 (adorn-char nc 'char '~named-char))
                (else (adorn-char nc 'invalid 'invalid))))))
  (cond ((eq? pm '~char-1) (handle~char-1! ac-list nc))
        ((eq? pm '~char-2) (handle~char-2! ac-list nc))
        ((eq? pm '~char-3) (handle~char-3! ac-list nc))
        ((eq? pm '~char-4) (handle~char-4! ac-list nc))
        ((eq? pm '~char-x) (handle~char-x! ac-list nc))
        ((eq? pm '~char-u) (handle~char-u! ac-list nc))
        ((eq? pm '~char-U) (handle~char-U! ac-list nc))
        ((eq? pm '~named-char) (handle~named-char! ac-list nc))
        ((memq pm '(char-u char-U named-char))
         (cond ((memc nc delim-chars) (try-nc! ac-list nc))
               (else (revise-until! ac-list 'char '~char-1)
                     (adorn-char nc 'invalid 'invalid))))
        (else #f)))

(define (try-directive/sharp-pm! ac-list nc pm)
  (define handle~directive!
    (^revise-if-complete 'directive '~directive directives))
  (define handle~sharp!
    (^revise-if-complete 'sharp '~sharp sharp-objects))
  (define (handle~directive/sharp! ac-list nc)
    (let ((tested (append (chars-until ac-list 'octothorpe) (list nc))))
      (cond ((could-match-one-of? sharp-objects tested)
             (handle~sharp! ac-list nc))
            ((could-match-one-of? directives tested)
             (handle~directive! ac-list nc))
            (else (adorn-char nc 'invalid 'invalid)))))
  (cond ((eq? pm '~directive) (handle~directive! ac-list nc))
        ((eq? pm '~directive/sharp) (handle~directive/sharp! ac-list nc))
        ((eq? pm '~sharp) (handle~sharp! ac-list nc))
        ((memq pm '(directive sharp))
         (need-delim! ac-list nc 'octothorpe))
        (else #f)))

(define (try-else-pm! ac-list nc pm)
  (cond ((memq pm '(~else ~~else))
         (let ((tested (append (chars-until ac-list '~~else) (list nc))))
           (cond ((matches? '(#\e #\l #\s #\e) tested)
                  (revise-until! ac-list 'aux-syntax 3)
                  (adorn-char nc 'aux-syntax 'else))
                 ((could-match? '(#\e #\l #\s #\e) tested)
                  (adorn-char nc 'default '~else))
                 (else (try-nc! ac-list nc)))))
        ((eq? pm 'else)
         (unless (memc nc delim-chars)
           (revise-until! ac-list 'default 4))
         (try-nc! ac-list nc))
        (else #f)))

(define (try-hs-pm! ac-list nc pm)
  (define (handle~hs-begin! ac-list nc)
    (cond ((char=? nc #\<)
           (revise-until! ac-list 'hs-begin 2)
           (adorn-char nc 'hs-begin '~hs-key-begin))
          ((memc nc delim-chars) (try-nc! ac-list nc))
          (else (adorn-char nc 'invalid 'invalid))))
  (define (handle:hs-key ac-list nc)
    (cond ((char=? nc #\newline)
           (adorn-char nc 'hs-key 'hs-key-end #f ac-list))
          (else (adorn-char nc 'hs-key 'hs-key))))
  (define (handle:hs-body! ac-list nc)
    (if (char=? nc #\newline)
        (let ((line/from-key (let seek ((rest ac-list) (chars '()))
                               (let* ((ac (car rest))
                                      (char (get-char ac)))
                                 (if (char=? char #\newline)
                                     (let ((stack (get-stack ac)))
                                       (set-stack! ac '())
                                       (list chars stack))
                                     (seek (cdr rest)
                                           (cons char chars)))))))
          (let ((previous-line (car line/from-key))
                (from-key (cadr line/from-key)))
            (let* ((hs-key (cdr (chars-until from-key '~hs-key-begin)))
                   (hs-key-length (length hs-key)))
              (if (or (equal? hs-key previous-line) (= hs-key-length 0))
                  (begin (revise-until! ac-list 'hs-key hs-key-length)
                         (adorn-char nc 'hs-key #f))
                  (adorn-char nc 'hs-body 'hs-body #f from-key)))))
        (adorn-char nc 'hs-body 'hs-body)))
  (cond ((memq pm '(hs-body hs-key-end)) (handle:hs-body! ac-list nc))
        ((memq pm '(hs-key ~hs-key-begin)) (handle:hs-key ac-list nc))
        ((eq? pm '~hs-begin) (handle~hs-begin! ac-list nc))
        (else #f)))

(define (try-label/ref-pm! ac-list nc pm)
  (define (handle~label/ref! ac-list nc)
    (cond ((char=? nc #\=)
           (revise-until! ac-list 'datum-label 'octothorpe)
           (adorn-char nc 'datum-label #f))
          ((char=? nc #\#)
           (revise-until! ac-list 'datum-ref 'octothorpe)
           (adorn-char nc 'datum-ref #f))
          ((memc nc delim-chars)
           (revise-until! ac-list 'serial-ref 'octothorpe)
           (try-nc! ac-list nc))
          ((memc nc decimal-chars) (adorn-char nc 'default '~label/ref))
          (else (adorn-char nc 'invalid 'invalid))))
  (and (eq? pm '~label/ref) (handle~label/ref! ac-list nc)))

(define (try-invalid-pm! ac-list nc pm)
  (and (eq? pm 'invalid)
       (cond ((memc nc delim-chars) (try-nc! ac-list nc))
             (else (adorn-char nc 'invalid 'invalid)))))

(define (try-linec-pm! ac-list nc pm)
  (and (eq? pm 'linec) (cond ((char=? nc #\newline) (try-nc! ac-list nc))
                             (else (adorn-char nc 'linec 'linec)))))

(define (try-numeric-pm! ac-list nc pac pm)
  (define (numeric-kind? ac) (eq? (get-kind ac) 'number))
  (define (^try~exactness-pm! ~mesg ~mesg# mesg#dec)
    (lambda (ac-list nc pm)
      (and (eq? pm ~mesg)
           (cond ((char=? nc #\#) (adorn-char nc 'number ~mesg#))
                 ((memc nc (append '(#\. #\+ #\-) decimal-chars))
                  (adorn-char nc 'number mesg#dec))
                 ((memc nc delim-chars) (try-nc! ac-list nc))
                 (else (revise-until! ac-list 'default 'octothorpe)
                       (adorn-char nc 'invalid 'invalid))))))
  (define (^try~radix-pm! ~mesg ~mesg# mesg#radix radix-chars)
    (lambda (ac-list nc pm)
      (and (eq? pm ~mesg)
           (cond ((char=? nc #\#) (adorn-char nc 'number ~mesg#))
                 ((memc-ci nc radix-chars)
                  (adorn-char nc 'number mesg#radix))
                 ((memc nc '(#\+ #\-))
                  (adorn-char nc 'number mesg#radix))
                 ((memc nc delim-chars) (try-nc! ac-list nc))
                 (else (revise-until! ac-list 'default 'octothorpe)
                       (adorn-char nc 'invalid 'invalid))))))
  (define (^try~exactness#-pm! ~mesg#)
    (lambda (ac-list nc pm)
      (and (eq? pm ~mesg#)
           (cond ((char-ci=? nc #\b) (adorn-char nc 'number '~bin#num))
                 ((char-ci=? nc #\o) (adorn-char nc 'number '~oct#num))
                 ((char-ci=? nc #\d) (adorn-char nc 'number 'dec#num))
                 ((char-ci=? nc #\x) (adorn-char nc 'number '~hex#num))
                 ((memc nc delim-chars) (try-nc! ac-list nc))
                 (else (revise-until! ac-list 'default 'octothorpe)
                       (adorn-char nc 'invalid 'invalid))))))
  (define (^try~radix#-pm! ~mesg# mesg#num)
    (lambda (ac-list nc pm)
      (and (eq? pm ~mesg#)
           (cond ((memc-ci nc '(#\e #\i))
                  (adorn-char nc 'number mesg#num))
                 ((memc nc delim-chars) (try-nc! ac-list nc))
                 (else (revise-until! ac-list 'default 'octothorpe)
                       (adorn-char nc 'invalid 'invalid))))))
  (define (^try-non-dec#num-pm! mesg#num radix-chars)
    (lambda (ac-list nc pm)
      (and (eq? pm mesg#num)
           (cond ((memc-ci nc radix-chars)
                  (adorn-char nc 'number pm))
                 ((memc nc delim-chars) (try-nc! ac-list nc))
                 (else (revise-until! ac-list 'default 'octothorpe)
                       (adorn-char nc 'invalid 'invalid))))))
  (define (^try~inf/nan-pm! ~mesg mesg strings)
    (lambda (ac-list nc pm)
      (and (eq? pm ~mesg)
           (let* ((recents (chars-until ac-list '~dec/inf/nan))
                  (tested (map char-downcase
                               (append recents (list nc)))))
             (cond ((matches-one-of? strings tested)
                    (adorn-char nc 'number mesg))
                   ((could-match-one-of? strings tested)
                    (adorn-char nc 'number ~mesg))
                   (else (revise-until! ac-list 'default '~dec/inf/nan)
                         (try-nc! ac-list nc)))))))
  (define try~inf-pm! (^try~inf/nan-pm! '~inf 'inf '("+inf.0" "-inf.0")))
  (define try~nan-pm! (^try~inf/nan-pm! '~nan 'nan '("+nan.0" "-nan.0")))
  (define (try~dec/inf/nan-pm! ac-list nc pac pm)
    (and (eq? pm '~dec/inf/nan)
         (cond ((char-ci=? nc #\i)
                (set-kind! pac 'number)
                (adorn-char nc 'number '~inf))
               ((char-ci=? nc #\n)
                (set-kind! pac 'number)
                (adorn-char nc 'number '~nan))
               ((memc nc decimal-chars)
                (set-kind! pac 'number)
                (adorn-char nc 'number 'dec.num))
               ((char=? nc #\.)
                (set-kind! pac 'number)
                (adorn-char nc 'number 'dec-num))
               ((memc nc delim-chars) (try-nc! ac-list nc))
               (else (adorn-char nc 'default '#f)))))
  (define (try?dec?num-pm! ac-list nc pac pm)
    (and (memq pm '(~dec.num dec.num ~dec-num dec-num))
         (cond ((char=? nc #\.)
                (cond ((memq pm '(dec-num ~dec-num))
                       (revise-while! ac-list 'default numeric-kind?)
                       (adorn-char nc 'default #f))
                      (else (adorn-char nc 'number 'dec-num))))
               ((memc nc decimal-chars)
                (cond ((eq? pm '~dec.num)
                       (adorn-char nc 'number 'dec.num))
                      ((eq? pm '~dec-num)
                       (set-kind! pac 'number)
                       (adorn-char nc 'number 'dec-num))
                      (else (adorn-char nc 'number pm))))
               ((memc nc delim-chars)
                (when (and (not (null? ac-list)) (memq pm '(dec-num ~dec-num)))
                  (let ((rest (cdr ac-list)))
                    (when (not (null? rest))
                      (cond ((memc-ci (get-char (car rest)) '(#\d #\e #\i))
                             (revise-while! ac-list 'default numeric-kind?))
                            ((atmosphere? (car rest))
                             (set-kind! pac 'dot))))))
                (try-nc! ac-list nc))
               ((memc-ci nc '(#\e #\s #\f #\d #\l))
                (adorn-char nc 'number 'dec-precision))
               (else (revise-while! ac-list 'default numeric-kind?)
                     (adorn-char nc 'default #f)))))
  (define (try-dec-precision-pm! ac-list nc pm)
    (and (eq? pm 'dec-precision)
         (cond ((memc nc decimal-chars) (adorn-char nc 'number pm))
               ((memc nc delim-chars) (try-nc! ac-list nc))
               (else (revise-while! ac-list 'default numeric-kind?)
                     (adorn-char nc 'default #f)))))         
  (define try~exact-pm! (^try~exactness-pm! '~exact '~exact# 'dec#num))
  (define try~inexact-pm! (^try~exactness-pm! '~inexact '~inexact# 'dec#num))
  (define try~exact#-pm! (^try~exactness#-pm! '~exact#))
  (define try~inexact#-pm! (^try~exactness#-pm! '~inexact#))
  (define try~bin#num-pm!
    (^try~radix-pm! '~bin#num '~bin-num# 'bin#num binary-chars))
  (define try~oct#num-pm!
    (^try~radix-pm! '~oct#num '~oct-num# 'oct#num octal-chars))
  (define try~hex#num-pm!
    (^try~radix-pm! '~hex#num '~hex-num# 'hex#num hexadecimal-chars))
  (define try~bin-num#-pm! (^try~radix#-pm! '~bin-num# 'bin#num))
  (define try~oct-num#-pm! (^try~radix#-pm! '~oct-num# 'oct#num))
  (define try~hex-num#-pm! (^try~radix#-pm! '~hex-num# 'hex#num))
  (define try-bin#num-pm! (^try-non-dec#num-pm! 'bin#num binary-chars))
  (define try-oct#num-pm! (^try-non-dec#num-pm! 'oct#num octal-chars))
  (define try-hex#num-pm!
    (^try-non-dec#num-pm! 'hex#num hexadecimal-chars))
  (define (try~dec-num#-pm! ac-list nc pm)
    (and (eq? pm '~dec#num)
         (cond ((char=? nc #\#) (adorn-char nc 'number 'dec#exactness))
               ((char=? nc #\.) (adorn-char nc 'number 'dec-num))
               ((memc nc (append '(#\+ #\-) decimal-chars))
                (adorn-char nc 'number 'dec.num))
               ((memc nc delim-chars)
                (revise-while! ac-list 'default numeric-kind?)
                (try-nc! ac-list nc))
               (else (revise-while! ac-list 'default numeric-kind?)
                     (adorn-char nc 'default #f)))))
  (define (try-dec#exactness-pm! ac-list nc pm)
    (and (eq? pm 'dec#exactness)
         (cond ((memc-ci nc '(#\e #\i)) (adorn-char nc 'number 'dec#num))
               ((memc nc delim-chars)
                (revise-while! ac-list 'default numeric-kind?)
                (try-nc! ac-list nc))
               (else (revise-while! ac-list 'default numeric-kind?)
                     (adorn-char nc 'default #f)))))
  (define (try-dec#num-pm! ac-list nc pm)
    (and (eq? pm 'dec#num)
         (cond ((char=? nc #\.) (adorn-char nc 'number 'dec-num))
               ((memc nc '(#\+ #\-)) (adorn-char nc 'number 'dec.num))
               ((memc nc decimal-chars) (adorn-char nc 'number 'dec.num))
               ((memc nc delim-chars)
                (revise-while! ac-list 'default numeric-kind?)
                (try-nc! ac-list nc))
               (else (revise-while! ac-list 'default numeric-kind?)
                     (adorn-char nc 'default #f)))))
  (or (try~dec/inf/nan-pm! ac-list nc pac pm)
      (try?dec?num-pm! ac-list nc pac pm)
      (try-dec-precision-pm! ac-list nc pm)
      (try~dec-num#-pm! ac-list nc pm)
      (try-dec#num-pm! ac-list nc pm)
      (try-dec#exactness-pm! ac-list nc pm)
      (try~exact-pm! ac-list nc pm)
      (try~exact#-pm! ac-list nc pm)
      (try~inexact-pm! ac-list nc pm)
      (try~inexact#-pm! ac-list nc pm)
      (try~bin#num-pm! ac-list nc pm)
      (try~bin-num#-pm! ac-list nc pm)
      (try~oct#num-pm! ac-list nc pm)
      (try~oct-num#-pm! ac-list nc pm)
      (try~hex#num-pm! ac-list nc pm)
      (try~hex-num#-pm! ac-list nc pm)
      (try-bin#num-pm! ac-list nc pm)
      (try-oct#num-pm! ac-list nc pm)
      (try-hex#num-pm! ac-list nc pm)
      (try~inf-pm! ac-list nc pm)
      (try~nan-pm! ac-list nc pm)
      (cond ((memq pm '(inf nan))
             (cond ((memc nc delim-chars) (try-nc! ac-list nc))
                   (else (revise-until! ac-list 'default '~dec/inf/nan)
                         (try-nc! ac-list nc))))
            (else #f))))

(define (try-octothorpe-pm! ac-list nc pac pm)
  (and (eq? pm 'octothorpe)
       (cond ((char=? nc #\!) (adorn-char nc 'default '~directive/sharp))
             ((char=? nc #\s) (adorn-char nc 'default '~svector))
             ((char=? nc #\u) (adorn-char nc 'default '~uvector))
             ((char=? nc #\|) (begin-nestc! ac-list nc pac))
             ((char=? nc #\<) (adorn-char nc 'default '~hs-begin))
             ((char=? nc #\\)
              (set-kind! pac 'char)
              (adorn-char nc 'char '~char-1))
             ((char=? nc #\f)
              (set-kind! pac 'false)
              (adorn-char nc 'false '~f/false/fvector))
             ((char=? nc #\t)
              (set-kind! pac 'true)
              (adorn-char nc 'true '~t))
             ((char=? nc #\;)
              (set-kind! pac 'datumc)
              (set-hop! pac 0)
              (set-stack! pac (list ac-list))
              (adorn-char nc 'datumc '~datumc))
             ((char=? nc #\&)
              (set-kind! pac 'box)
              (adorn-char nc 'box 'box))
             ((char=? nc #\()
              (set-kind! pac 'vector)
              (begin-compound! ac-list nc 'vector))
             ((memc nc decimal-chars)
              (adorn-char nc 'default '~label/ref))
             ((char=? nc #\#)
              (cond ((operator-position? (cdr ac-list))
                     (set-mesg! pac '~~rt-syntax)
                     (adorn-char nc 'default '~rt-syntax))
                    (else (set-kind! pac 'repl-ref)
                          (adorn-char nc 'repl-ref '~repl-ref))))
             ((char-ci=? nc #\e)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~exact))
             ((char-ci=? nc #\i)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~inexact))
             ((char-ci=? nc #\b)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~bin#num))
             ((char-ci=? nc #\d)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~dec#num))
             ((char-ci=? nc #\o)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~oct#num))
             ((char-ci=? nc #\x)
              (set-kind! pac 'number)
              (adorn-char nc 'number '~hex#num))
             ((memc nc delim-chars)
              (set-kind! pac 'repl-ref)
              (try-nc! ac-list nc))
             (else (adorn-char nc 'invalid 'invalid)))))

(define (try-quote-pm! ac-list nc pac pm)
  (cond ((memq pm '(quasiquote quote)) (try-nc! ac-list nc))
        ((eq? pm 'unquote)
         (if (and (char=? nc #\@) (char=? (get-char pac) #\,))
             (adorn-char nc 'abbrev 'unquote)
             (try-nc! ac-list nc)))
        (else #f)))

(define (try~repl-ref-pm! ac-list nc pm)
  (and (eq? pm '~repl-ref)
       (cond ((char=? nc #\#) (adorn-char nc 'repl-ref '~repl-ref))
             ((memc nc delim-chars) (try-nc! ac-list nc))
             (else (revise-until! ac-list 'default 'octothorpe)
                   (adorn-char nc 'default #f)))))

(define (try-rt-syntax-pm! ac-list nc pac pm)
  (define (handle~rt-syntax! ac-list nc)
    (define (rt-syntax? ac) (eq? (get-kind ac) 'rt-syntax))
    (let* ((recents (chars-until ac-list '~~rt-syntax))
           (tested (append recents (list nc))))
      (cond ((matches-one-of? runtime-syntax tested)
             (revise-until! ac-list 'rt-syntax '~~rt-syntax)
             (adorn-char nc 'rt-syntax '~rt-syntax))
            ((could-match-one-of? runtime-syntax tested)
             (revise-while! ac-list 'default rt-syntax?)
             (adorn-char nc 'default '~rt-syntax))
            ((and (char=? nc #\#) (= (length recents) 2))
             (set-mesg! pac '~repl-ref)
             (set-mesg! (cadr ac-list) 'octothorpe)
             (revise-until! ac-list 'repl-ref 'octothorpe)
             (adorn-char nc 'repl-ref '~repl-ref))
            ((memc nc delim-chars)
             (when (and (char=? (get-char pac) #\#)
                        (= (length recents) 2))
               (revise-until! ac-list 'repl-ref '2))
             (try-nc! ac-list nc))
            (else (revise-while! ac-list 'default rt-syntax?)
                  (adorn-char nc 'default #f)))))
  (and (memq pm '(~rt-syntax ~~rt-syntax))
       (handle~rt-syntax! ac-list nc)))

(define (try-shebang-pm! ac-list nc pm)
  (and (eq? pm 'shebang)
       (cond ((char=? nc #\newline) (try-nc! ac-list nc))
             (else (adorn-char nc 'shebang 'shebang)))))
