(define (ident/string-mesg-alist base)
  (list (cons 'base base) (cons 'unmatched (->unmatched base))
        (cons 'begin (->begin base)) (cons 'end (->end base))
        (cons 'hex-x (->hex-x base)) (cons 'hex-U (->hex-U base))
        (cons 'hex-u (->hex-u base)) (cons 'backslash (->backslash base))
        (cons 'nil-esc (->nil-esc base)) (cons 'octal-1 (->octal-1 base))
        (cons 'octal-2 (->octal-2 base)) (cons 'octal-3 (->octal-3 base))))

(define (^ident/string-dispatch! base-sym delim-char end!)
  (define sym-alist (ident/string-mesg-alist base-sym))
  (define reversed-alist (map (lambda (p) (cons (cdr p) (car p))) sym-alist))
  (define (generic->specific sym) (cdr (assq sym sym-alist)))
  (define (specific->generic sym) (cdr (assq sym reversed-alist)))
  (define (generic->handler sym)
    (define (^handle:ident/string! base-sym delim-char end!)
      (let ((backslash (->backslash base-sym)))
        (lambda (ac-list nc)
          (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                ((char=? nc #\\) (adorn-char nc base-sym backslash))
                (else (adorn-char nc base-sym base-sym))))))
    (define (^handle:ident/string-backslash! base-sym)
      (let ((esc (->esc base-sym)) (hex-x (->hex-x base-sym))
            (hex-u (->hex-u base-sym)) (hex-U (->hex-U base-sym))
            (nil-esc (->nil-esc base-sym)) (octal-1 (->octal-1 base-sym)))
        (lambda (nc pac)
          (cond ((char=? nc #\x) (adorn-char nc base-sym hex-x))
                ((char=? nc #\u) (adorn-char nc base-sym hex-u))
                ((char=? nc #\U) (adorn-char nc base-sym hex-U))
                ((char=? nc #\newline)
                 (set-kind! pac esc)
                 (adorn-char nc esc nil-esc))
                ((memc nc octal-chars)
                 (set-kind! pac esc)
                 (adorn-char nc esc octal-1))
                ((memc nc ident/string-mnemonic-escape-chars)
                 (set-kind! pac esc)
                 (adorn-char nc esc base-sym))
                (else (adorn-char nc 'invalid 'base-sym))))))
    (define (^handle:ident/string-hex-Uu! base-sym sym delim-char end!)
      (let ((ending (car (reverse (string->list (symbol->string sym)))))
            (esc (->esc base-sym)) (backslash (->backslash base-sym)))
        (let ((hex-Uu/target (if (char=? ending #\U)
                                 (cons (->hex-U base-sym) 8)
                                 (cons (->hex-u base-sym) 4))))
          (let ((hex-Uu (car hex-Uu/target)) (target (cdr hex-Uu/target)))
            (lambda (ac-list nc)
              (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                    ((memc-ci nc hexadecimal-chars)
                     (let ((total (distance-until ac-list backslash)))
                       (if (> target total)
                           (adorn-char nc base-sym hex-Uu)
                           (begin (revise-until! ac-list esc (+ target 1))
                                  (adorn-char nc esc base-sym)))))
                    (else (adorn-char nc 'invalid base-sym))))))))
    (define (^handle:ident/string-hex-x! base-sym delim-char end!)
      (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
            (hex-x (->hex-x base-sym)))
        (lambda (ac-list nc)
          (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                ((char=? nc #\;)
                 (revise-until! ac-list esc backslash)
                 (adorn-char nc esc base-sym))
                ((memc-ci nc hexadecimal-chars)
                 (adorn-char nc base-sym hex-x))
                (else (adorn-char nc 'invalid base-sym))))))
    (define (^handle:ident/string-nil-esc! base-sym delim-char end!)
      (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
            (nil-esc (->nil-esc base-sym)))
        (lambda (ac-list nc)
          (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                ((char=? nc #\\) (adorn-char nc base-sym backslash))
                ((memc nc '(#\space #\tab)) (adorn-char nc esc nil-esc))
                (else (adorn-char nc base-sym base-sym))))))
    (define (^handle:ident/string-octal-1! base-sym delim-char end!)
      (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
            (octal-2 (->octal-2 base-sym)))
        (lambda (ac-list nc)
          (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                ((char=? nc #\\) (adorn-char nc base-sym backslash))
                ((memc nc octal-chars) (adorn-char nc esc octal-2))
                (else (adorn-char nc base-sym base-sym))))))
    (define (^handle:ident/string-octal-2! base-sym delim-char end!)
      (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
            (octal-1 (->octal-1 base-sym)) (octal-3 (->octal-3 base-sym)))
        (lambda (ac-list nc)
          (cond ((char=? nc delim-char) (end! ac-list nc base-sym))
                ((char=? nc #\\) (adorn-char nc base-sym backslash))
                ((memc nc octal-chars)
                 (if (memc (get-char (cadr ac-list)) '(#\0 #\1 #\2 #\3))
                     (adorn-char nc esc octal-3)
                     (adorn-char nc base-sym base-sym)))
                (else (adorn-char nc base-sym base-sym))))))
    (cond ((memq sym '(base unmatched octal-3))
           (^handle:ident/string! base-sym delim-char end!))
          ((eq? sym 'backslash)
           (^handle:ident/string-backslash! base-sym))
          ((eq? sym 'hex-x)
           (^handle:ident/string-hex-x! base-sym delim-char end!))
          ((memq sym '(hex-U hex-u))
           (^handle:ident/string-hex-Uu! base-sym sym delim-char end!))
          ((eq? sym 'nil-esc)
           (^handle:ident/string-nil-esc! base-sym delim-char end!))
          ((eq? sym 'octal-1)
           (^handle:ident/string-octal-1! base-sym delim-char end!))
          ((eq? sym 'octal-2)
           (^handle:ident/string-octal-2! base-sym delim-char end!))
          (else try-nc!)))
  (lambda (ac-list nc pac pm)
    (let* ((generic-sym (specific->generic pm))
           (handler (generic->handler generic-sym)))
      (cond ((eq? generic-sym 'backslash) (handler nc pac))
            (else (handler ac-list nc))))))

(define string-dispatch! (^ident/string-dispatch! 'string #\" end-symmetric!))

(define (^ident-dispatch! kind)
  (^ident/string-dispatch! kind #\| end-symmetric!))

;; For ||-delimiter identifiers, plus various identifier "sub-kinds"
(define ident-dispatch!             (^ident-dispatch! 'ident))
(define defun-proc-ident-dispatch!  (^ident-dispatch! 'defun-proc-ident))
(define defun-param-ident-dispatch! (^ident-dispatch! 'defun-param-ident))
(define sv-define-ident-dispatch!   (^ident-dispatch! 'sv-define-ident))
(define mv-define-ident-dispatch!   (^ident-dispatch! 'mv-define-ident))
(define named-let-ident-dispatch!   (^ident-dispatch! 'named-let-ident))
(define sv-let-ident-dispatch!      (^ident-dispatch! 'sv-let-ident))
(define mv-let-ident-dispatch!      (^ident-dispatch! 'mv-let-ident))
(define lambda-bind-ident-dispatch! (^ident-dispatch! 'lambda-bind-ident))
(define lambda-rest-ident-dispatch! (^ident-dispatch! 'lambda-rest-ident))
(define key-param-ident-dispatch!   (^ident-dispatch! 'key-param-ident))
(define opt-param-ident-dispatch!   (^ident-dispatch! 'opt-param-ident))
(define rest-param-ident-dispatch!  (^ident-dispatch! 'rest-param-ident))
(define key-init-ident-dispatch!    (^ident-dispatch! 'key-init-param-ident))
(define opt-init-ident-dispatch!    (^ident-dispatch! 'opt-init-param-ident))
(define case-lambda-bind-ident-dispatch!
  (^ident-dispatch! 'case-lambda-bind-ident))
(define case-lambda-rest-ident-dispatch!
  (^ident-dispatch! 'case-lambda-rest-ident))

;; For datum-commented identifier/string data
(define datumc-string-dispatch!
  (^ident/string-dispatch! 'datumc-string #\" datumc:end-symmetric!))
(define datumc-ident-dispatch!
  (^ident/string-dispatch! 'datumc-ident #\| datumc:end-symmetric!))
(define datumc-compound-string-dispatch!
  (^ident/string-dispatch! 'datumc-compound-string #\" end-symmetric!))
(define datumc-compound-ident-dispatch!
  (^ident/string-dispatch! 'datumc-compound-ident #\| end-symmetric!))
(define (^ident-dispatch! kind)
  (^ident/string-dispatch! kind #\| end-symmetric!))

(define (try-ident/string-pm! ac-list nc pac pm) 
  (define (ident/string-mesg-list base)
    (map cdr (ident/string-mesg-alist base)))
  (define ident/string-mesg-lists
    (map ident/string-mesg-list ident/string-base-mesgs))
  (define (pm->mesgs pm) (assq pm ident/string-mesg-lists))
  ((cond ((memq pm (pm->mesgs 'sv-define-ident))   sv-define-ident-dispatch!)
         ((memq pm (pm->mesgs 'defun-proc-ident))  defun-proc-ident-dispatch!)
         ((memq pm (pm->mesgs 'defun-param-ident)) defun-param-ident-dispatch!)
         ((memq pm (pm->mesgs 'sv-let-ident))      sv-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'named-let-ident))   named-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'string))            string-dispatch!)
         ((memq pm (pm->mesgs 'ident))             ident-dispatch!)
         ((memq pm (pm->mesgs 'lambda-bind-ident)) lambda-bind-ident-dispatch!)
         ((memq pm (pm->mesgs 'lambda-rest-ident)) lambda-rest-ident-dispatch!)
         ((memq pm (pm->mesgs 'datumc-string))     datumc-string-dispatch!)
         ((memq pm (pm->mesgs 'datumc-ident))      datumc-ident-dispatch!)
         ((memq pm (pm->mesgs 'key-param-ident))   key-param-ident-dispatch!)
         ((memq pm (pm->mesgs 'opt-param-ident))   opt-param-ident-dispatch!)
         ((memq pm (pm->mesgs 'rest-param-ident))  rest-param-ident-dispatch!)
         ((memq pm (pm->mesgs 'key-init-param-ident)) key-init-ident-dispatch!)
         ((memq pm (pm->mesgs 'opt-init-param-ident)) key-init-ident-dispatch!)
         ((memq pm (pm->mesgs 'mv-define-ident))   mv-define-ident-dispatch!)
         ((memq pm (pm->mesgs 'mv-let-ident))      mv-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'datumc-compound-string))
          datumc-compound-string-dispatch!)
         ((memq pm (pm->mesgs 'datumc-compound-ident))
          datumc-compound-ident-dispatch!)
         ((memq pm (pm->mesgs 'case-lambda-bind-ident))
          case-lambda-bind-ident-dispatch!)
         ((memq pm (pm->mesgs 'case-lambda-rest-ident))
          case-lambda-rest-ident-dispatch!)
         (else (lambda x #f)))
   ac-list nc pac pm))
