;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define delimiter-chars
  '(#\) #\( #\space #\newline #\tab #\" #\; #\| #\' #\` #\\))
(define whitespace-chars '(#\space #\newline #\tab))
(define compound-begin-chars '(#\( #\[ #\{))
(define compound-end-chars '(#\) #\] #\}))
(define octal-chars '(#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7))
(define decimal-chars '(#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9))
(define hexadecimal-chars '(#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9
                            #\a #\b #\c #\d #\e #\f #\A #\B #\C #\D #\E #\F))
(define directives '("#!fold-case" "#!no-fold-case"))
(define sharp-objects '("#!eof" "#!key" "#!optional" "#!rest" "#!void"))
(define short-named-chars '("#\\esc" "#\\nul"))
(define long-named-chars
  '("#\\null" "#\\alarm" "#\\backspace" "#\\tab" "#\\space" "#\\newline"
    "#\\return" "#\\delete" "#\\escape" "#\\page" "#\\vtab" "#\\linefeed"))
(define fvector-strings '("#f32(" "#f64("))
(define svector-strings '("#s8(" "#s16(" "#s32(" "#s64("))
(define uvector-strings '("#u8(" "#u16(" "#u32(" "#u64("))
(define fvector-kinds '(f32vector f64vector))
(define svector-kinds '(s8vector s16vector s32vector s64vector))
(define uvector-kinds '(u8vector u16vector u32vector u64vector))
(define atmosphere-kinds '(whitespace linec datumc nestc directive))
(define runtime-syntax
  '("and" "begin" "c-declare" "c-define" "c-define-type" "c-initialize"
    "c-lambda" "case" "case-lambda" "cond" "cond-expand" "declare" "define"
    "define-library" "define-macro" "define-record-type" "define-structure"
    "define-syntax" "define-type" "define-type-of-thread" "define-values"
    "delay" "delay-force" "do" "else" "future" "guard" "if" "import"
    "include" "include-ci" "\x3bb;" "lambda" "let" "let*" "let*-values"
    "let-values" "letrec" "letrec*" "letrec*-values" "letrec-values"
    "namespace" "or" "parameterize" "quasiquote" "quote" "r7rs-guard"
    "receive" "set!" "syntax-error" "syntax-rules" "this-source-file"
    "unless" "when"))
(define single-value-define-variable-syntax '("define" "define-record-type"))
(define single-value-let-syntax
  '("let" "let*" "letrec" "letrec*" "parameterize"))

(define sublist-begin-mesgs '(sublist-unmatched sublist-begin))
(define list-begin-mesgs
  (append sublist-begin-mesgs '(list-unmatched list-begin)))
(define sublist-delimiter-mesgs (append sublist-begin-mesgs '(sublist-end)))
(define list-delimiter-mesgs
  (append sublist-delimiter-mesgs list-begin-mesgs '(list-end)))
(define list-end-mesgs '(sublist-end list-end))

(define compound-kinds
  (append '(list vector) fvector-kinds svector-kinds uvector-kinds))

(define bind-mesgs
  '( sv-define mv-define defun-proc defun-param named-let sv-let mv-let
     lambda-bind case-lambda-bind ))

(define ident/string-base-mesgs
  '( string datumc-string ident datumc-ident defun-proc-ident defun-param-ident
     sv-define-ident mv-define-ident named-let-ident sv-let-ident mv-let-ident
     lambda-bind-ident case-lambda-bind-ident ))

(define-record-type achar
  (make-adorned-char c k m h s)
  adorned-char?
  (c get-char)
  (k get-kind set-kind!)
  (m get-mesg set-mesg!)
  (h get-hop set-hop!)
  (s get-stack set-stack!))

(define (adorn-char char kind mesg #!optional (hop #f) (stack '()))
  (make-adorned-char char kind mesg hop stack))

(define (memc c l) (member c l char=?))

(define (append-to-symbol string)
  (lambda (symbol)
    (string->symbol (string-append (symbol->string symbol) string))))

(define ->sub
  (case-lambda
    ((symbol)
     (string->symbol (string-append "sub" (symbol->string symbol))))
    ((symbol ending)
     (string->symbol (string-append "sub" (symbol->string symbol) ending)))))

(define (->backslash symbol) ((append-to-symbol "-backslash") symbol))
(define (->begin symbol) ((append-to-symbol "-begin") symbol))
(define (->empty symbol) ((append-to-symbol "-empty") symbol))
(define (->end symbol) ((append-to-symbol "-end") symbol))
(define (->esc symbol) ((append-to-symbol "-esc") symbol))
(define (->hex-U symbol) ((append-to-symbol "-hex-U") symbol))
(define (->hex-u symbol) ((append-to-symbol "-hex-u") symbol))
(define (->hex-x symbol) ((append-to-symbol "-hex-x") symbol))
(define (->nil-esc symbol) ((append-to-symbol "-nil-esc") symbol))
(define (->octal-1 symbol) ((append-to-symbol "-octal-1") symbol))
(define (->octal-2 symbol) ((append-to-symbol "-octal-2") symbol))
(define (->octal-3 symbol) ((append-to-symbol "-octal-3") symbol))
(define (->unmatched symbol) ((append-to-symbol "-unmatched") symbol))

(define (->sub-unmatched kind) (->sub kind "-unmatched"))
(define (->sub-begin kind) (->sub kind "-begin"))
(define (->sub-end kind) (->sub kind "-end"))

(define compound-end-mesgs (map ->end compound-kinds))
(define subcompound-end-mesgs (map ->sub compound-end-mesgs))
(define compound-unmatched-mesgs (map ->unmatched compound-kinds))
(define subcompound-unmatched-mesgs (map ->sub compound-unmatched-mesgs))
(define compound-unmatched-mesgs
  (append compound-unmatched-mesgs subcompound-unmatched-mesgs))
(define compound-peering-mesgs
  (append compound-unmatched-mesgs subcompound-end-mesgs))

(define datumc-compound-unmatched-mesgs
  (map ->unmatched '(datumc-compound datumc-subcompound)))
(define datumc-compound-peering-mesgs
  (cons 'datumc-subcompound-end datumc-compound-unmatched-mesgs))
;==============================================================================
(define (increment-hops! peer-stack amount)
  (let ((heads (map car peer-stack)))
    (for-each (lambda (ac) (set-hop! ac (+ (get-hop ac) amount))) heads)))

(define (datumc:peer/distance ac-list)
  (let ((peering-mesgs '(octothorpe datumc#)))
    (let seek ((rest ac-list) (distance 0))
      (if (null? rest)
          '(#f 0)
          (let* ((ac (car rest)) (mesg (get-mesg ac)))
            (if (and (memq mesg peering-mesgs) (not (null? (get-stack ac))))
                (cons rest distance)
                (seek (cdr rest) (+ distance 1))))))))

(define (^compound-peer+distance peering-mesgs end-mesgs)
  (lambda (ac-list)
    (let seek ((rest ac-list) (distance 1))
      (if (null? rest)
          (values #f 0)
          (let* ((ac (car rest)) (mesg (get-mesg ac)))
            (cond ((memq mesg peering-mesgs) (values rest distance))
                  ((memq mesg end-mesgs) (values #f 0))
                  (else (seek (cdr rest) (+ distance 1)))))))))
(define compound-peer+distance
  (^compound-peer+distance compound-peering-mesgs compound-end-mesgs))
(define datumc-compound-peer+distance
  (^compound-peer+distance datumc-compound-peering-mesgs
                           '(datumc-compound-end)))

(define (^begin-compound! peer+distance ->sub-unmatched)
  (lambda (ac-list char kind)
    (let-values (((from-peer distance) (peer+distance ac-list)))
      (if from-peer
          (let* ((peer (car from-peer))
                 (peer-stack (get-stack peer))
                 (first-peer (caar peer-stack)))
            (let ((new-ac (adorn-char char kind (->sub-unmatched kind) 0 '())))
              (increment-hops! peer-stack distance)
              (set-stack! peer '())
              (set-stack! new-ac (cons (cons new-ac ac-list) peer-stack))
              new-ac))
          (let ((new-ac (adorn-char char kind (->unmatched kind) 0 '())))
            (begin (set-stack! new-ac (list (cons new-ac ac-list)))
                   new-ac))))))
(define begin-compound!
  (^begin-compound! compound-peer+distance ->sub-unmatched))
(define (begin-datumc-compound! ac-list char)
  ((^begin-compound! datumc-compound-peer+distance
                     (lambda (kind) 'datumc-subcompound-unmatched))
   ac-list char 'datumc-compound))

(define (^compound:peer+empty?+distance peering-mesgs end-mesgs empty-init)
  (lambda (ac-list)
    (let ((empty empty-init))
      (let seek ((rest ac-list) (distance 1))
        (if (null? rest)
            (values #f #f 0)
            (let* ((ac (car rest)) (mesg (get-mesg ac)))
              (cond ((memq mesg peering-mesgs)
                     (if (and empty (memc (get-char ac) compound-begin-chars))
                         (values rest #t distance)
                         (values rest #f distance)))
                    ((memq mesg end-mesgs) (values #f #f 0))
                    ((and empty (not (memq (get-kind ac) atmosphere-kinds)))
                     (set! empty #f)
                     (seek (cdr rest) (+ distance 1)))
                    (else (seek (cdr rest) (+ distance 1))))))))))
(define compound:peer+empty?+distance
  (^compound:peer+empty?+distance
   compound-peering-mesgs compound-end-mesgs #t))
(define datumc-compound:peer+empty?+distance
  (^compound:peer+empty?+distance
   datumc-compound-peering-mesgs '(datumc-compound-end) #f))

(define (subcompound-mesg? symbol)
  (and symbol (string=? "sub" (string-copy (symbol->string symbol) 0 3))))

(define (datumc-subcompound-mesg? symbol)
  (and symbol
       (string=? "datumc-sub" (string-copy (symbol->string symbol) 0 10))))

(define (^end-compound! sub-mesg? peer+empty?+distance ->sub-begin ->sub-end)
  (define (compound-kind->distance symbol)
    (cond ((eq? symbol 'list) 1)
          ((eq? symbol 'vector) 2)
          ((memq symbol '(u8vector s8vector)) 4)
          (else 5)))
  (lambda (ac-list char)
    (let-values (((from-peer empty distance) (peer+empty?+distance ac-list)))
      (if from-peer
          (let* ((peer (car from-peer)) (peer-stack (get-stack peer)))
            (increment-hops! (cdr peer-stack) distance)
            (let ((first-peer (caar peer-stack)))
              (let ((total-dist (+ (get-hop first-peer) distance))
                    (kind (get-kind first-peer))
                    (initial-mesg (get-mesg first-peer)))
                (set-stack! peer '())
                (set-hop! first-peer total-dist)
                (let-values (((begin-mesg end-mesg)
                              (if (sub-mesg? initial-mesg)
                                  (values (->sub-begin kind)
                                          (->sub-end kind))
                                  (values (->begin kind)
                                          (->end kind)))))
                  (let ((revision-distance (compound-kind->distance kind))
                        (kind (if empty (->empty kind) kind)))
                    (let ((nac (adorn-char char kind end-mesg (- total-dist))))
                      (revise-until! from-peer kind revision-distance)
                      (set-mesg! first-peer begin-mesg)
                      (set-stack! nac (cdr peer-stack))
                      (values nac (car peer-stack))))))))
          (values (adorn-char char 'invalid 'unmatched-end) '())))))

(define (end-compound! ac-list char)
  (call-with-values
      (lambda ()
        ((^end-compound! subcompound-mesg? compound:peer+empty?+distance
                         ->sub-begin ->sub-end)
         ac-list char))
    (lambda (ac rest) ac)))

(define (end-datumc-compound! ac-list char)
  (call-with-values
      (lambda ()
        ((^end-compound! datumc-subcompound-mesg?
                         datumc-compound:peer+empty?+distance
                         (lambda (symbol) 'datumc-subcompound-begin)
                         (lambda (symbol) 'datumc-subcompound-end))
         ac-list char))
    (lambda (ac rest)
      (when (eq? (get-mesg ac) 'datumc-compound-end)
        (let ((p/d (datumc:peer/distance rest)))
          (let ((from-peer (car p/d)) (distance-from-# (cdr p/d)))
            (let* ((initial-# (car from-peer))
                   (initial-#-stack (get-stack initial-#)))
              (let ((top-peer (caar initial-#-stack))
                    (popped-#-stack (cdr initial-#-stack)))
                (when (null? popped-#-stack) (set-mesg! ac 'datumc-end))
                (let* ((intra-compound-distance (get-hop (car rest)))
                       (~distance (+ intra-compound-distance distance-from-#))
                       (total-distance (+ ~distance (get-hop top-peer))))
                  (set-hop! ac (- total-distance))
                  (set-hop! top-peer total-distance)
                  (set-stack! initial-# popped-#-stack)))))))
      ac)))

(define (adorn-without-context char)
  (cond ((char=? char #\\) (adorn-char char 'infix #f))
        ((char=? char #\;) (adorn-char char 'linec 'linec))
        ((char=? char #\#) (adorn-char char 'default 'octothorpe))
        ((char=? char #\|) (adorn-char char 'ident #f))
        ((char=? char #\") (adorn-char char 'string #f))
        ((char=? char #\') (adorn-char char 'quote #f))
        ((char=? char #\`) (adorn-char char 'quasiquote #f))
        ((char=? char #\,) (adorn-char char 'unquote #f))
        ((memc char '(#\space #\newline #\tab))
         (adorn-char char 'whitespace #f))
        (else (adorn-char char 'default #f))))

(define (adorn-invalid char)
  (adorn-char char 'invalid 'invalid))

(define (symmetric-peer+distance ac-list kind)
  (let ((unmatched-kind (->unmatched kind)))
    (let seek ((rest ac-list) (distance 1))
      (cond ((null? rest) (values #f 0))
            ((eq? (get-mesg (car rest)) unmatched-kind) (values rest distance))
            (else (seek (cdr rest) (+ distance 1)))))))

(define (begin-symmetric ac-list char kind)
  (let ((new-ac (adorn-char char kind (->unmatched kind) 0)))
    (set-stack! new-ac (list (cons new-ac ac-list)))
    new-ac))

(define (end-datumc-symmetric! ac-list char kind)
  (let-values (((from-peer distance) (symmetric-peer+distance ac-list kind)))
    (or from-peer (error "Unable to find beginning of symmetric datum"))
    (let ((peer (car from-peer)))
      (set-hop! peer distance)
      (set-mesg! peer (->begin kind))
      (set-stack! peer '()))
    (let ((datumc:p/d (datumc:peer/distance from-peer)))
      (let ((from-dc-peer (car datumc:p/d)) (dc-distance (cdr datumc:p/d)))
        (let* ((nearest-peer (car from-dc-peer))
               (peer-stack (get-stack nearest-peer))
               (top-peer (caar peer-stack))
               (total-distance (+ distance dc-distance (get-hop top-peer))))
          (set-hop! top-peer total-distance)
          (let ((rest (cdr peer-stack)))
            (set-stack! nearest-peer rest)
            (if (null? rest)
                (adorn-char char kind 'datumc-end (- total-distance))
                (adorn-char char kind (->end kind) (- total-distance)))))))))

(define (end-symmetric! ac-list char kind)
  (let-values (((from-peer distance) (symmetric-peer+distance ac-list kind)))
    (or from-peer (error "Unable to find beginning of symmetric datum"))
    (let ((peer (car from-peer)))
      (set-hop! peer distance)
      (set-mesg! peer (->begin kind))
      (set-stack! peer '()))
    (adorn-char char kind (->end kind) (- distance))))

(define (distance-until ac-list char/mesg)
  (cond ((char? char/mesg)
         (let loop ((rest ac-list) (distance 0))
           (cond ((null? rest) (error "Not found" char/mesg))
                 ((char=? (get-char (car rest)) char/mesg) distance)
                 (else (loop (cdr rest) (+ distance 1))))))
        ((symbol? char/mesg)
         (let loop ((rest ac-list) (distance 0))
           (cond ((null? rest) (error "Not found" char/mesg))
                 ((eq? (get-mesg (car rest)) char/mesg) distance)
                 (else (loop (cdr rest) (+ distance 1))))))))

(define (revise-until! ac-list new-kind int/mesg/predicate? #!optional end-act)
  (cond ((integer? int/mesg/predicate?)
         (let loop ((rest ac-list) (i int/mesg/predicate?))
           (unless (or (null? rest) (> 1 i))
             (let ((ac (car rest)))
               (set-kind! ac new-kind)
               (when (and end-act (= i 1)) (end-act rest))
               (loop (cdr rest) (- i 1))))))
        ((symbol? int/mesg/predicate?)
         (let loop ((rest ac-list))
           (unless (null? rest)
             (let ((ac (car rest)))
               (set-kind! ac new-kind)
               (if (eq? (get-mesg ac) int/mesg/predicate?)
                   (when end-act (end-act rest))
                   (loop (cdr rest)))))))
        (else (let loop ((rest ac-list))
                (unless (null? rest)
                  (let ((ac (car rest)))
                    (if (int/mesg/predicate? ac)
                        (begin (set-kind! ac new-kind)
                               (when end-act (end-act rest)))
                        (loop (cdr rest)))))))))

(define (revise-while! ac-list new-kind predicate?)
  (unless (null? ac-list)
    (let ((ac (car ac-list)))
      (when (predicate? ac)
        (set-kind! ac new-kind)
        (revise-while! (cdr ac-list) new-kind predicate?)))))

(define (chars-until ac-list char/int/mesg/predicate?)
  (cond ((char? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list))
           (if (null? rest)
               chars
               (let ((char (get-char (car rest))))
                 (if (char=? char char/int/mesg/predicate?)
                     (cons char chars)
                     (loop (cons char chars) (cdr rest)))))))
        ((integer? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list) (i char/int/mesg/predicate?))
           (if (or (zero? i) (null? rest))
               chars
               (loop (cons (get-char (car rest)) chars) (cdr rest) (- i 1)))))
        ((symbol? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list))
           (if (null? rest)
               chars
               (let ((ac (car rest)))
                 (let ((char (get-char ac))
                       (mesg (get-mesg ac)))
                   (if (eq? mesg char/int/mesg/predicate?)
                       (cons char chars)
                       (loop (cons char chars) (cdr rest))))))))
        (else (let loop ((chars '()) (rest ac-list))
                (if (null? rest)
                    chars
                    (let ((ac (car rest)))
                      (if (char/int/mesg/predicate? ac)
                          (cons (get-char ac) rest)
                          (loop (cons (get-char ac) chars) (cdr rest)))))))))

(define (char-list-backmatch goal actual)
  (let backmatch-loop ((goal (reverse goal)) (actual-rest (reverse actual)))
    (if (null? goal)
        actual
        (and (not (null? actual-rest))
             (char=? (car goal) (car actual-rest))
             (backmatch-loop (cdr goal) (cdr actual-rest))))))

(define (backmatch goal actual)
  (let ((cl-goal (if (string? goal) (string->list goal) goal))
        (cl-actual (if (string? actual) (string->list actual) actual)))
    (char-list-backmatch cl-goal cl-actual)))

(define (char-list-could-match? goal actual)
  (or (null? actual)
      (and (not (null? goal))
           (char=? (car goal) (car actual))
           (char-list-could-match? (cdr goal) (cdr actual)))))

(define (could-match? goal actual)
  (let ((cl-goal (if (string? goal) (string->list goal) goal))
        (cl-actual (if (string? actual) (string->list actual) actual)))
    (char-list-could-match? cl-goal cl-actual)))

(define (could-match-one-of? goals actual)
  (and (not (null? goals))
       (or (could-match? (car goals) actual)
           (could-match-one-of? (cdr goals) actual))))

(define (achievable-goals goals actual)
  (let loop ((old goals) (new '()))
    (if (null? old)
        new
        (let ((goal (car old)))
          (cond ((could-match? goal actual) (loop (cdr old) (cons goal new)))
                (else (loop (cdr old) new)))))))

(define (backmatch-one-of goals actual)
  (let loop ((achievable (achievable-goals goals actual)))
    (and (not (null? achievable))
         (or (backmatch (car achievable) actual)
             (loop (cdr achievable))))))

(define (matches? goal actual)
  (let ((cl-goal (if (string? goal) (string->list goal) goal))
        (cl-actual (if (string? actual) (string->list actual) actual)))
    (or (and (null? cl-goal) (null? cl-actual))
        (and (not (or (null? cl-goal) (null? cl-actual)))
             (char=? (car cl-goal) (car cl-actual))
             (matches? (cdr cl-goal) (cdr cl-actual))))))

(define (matches-one-of? goals actual)
  (let loop ((achievable (achievable-goals goals actual)))
    (and (not (null? achievable))
         (or (matches? (car achievable) actual)
             (loop (cdr achievable))))))

(define (looking-at ac-list mesg-list)
  (and (not (null? ac-list)) (let ((ac (car ac-list)))
                               (if (memq (get-kind ac) atmosphere-kinds)
                                   (looking-at (cdr ac-list) mesg-list)
                                   (memq (get-mesg ac) mesg-list)))))

(define (handle~datumc! ac-list nc)
  (cond ((char=? nc #\#) (adorn-char nc 'datumc 'datumc#))
        ((char=? nc #\") (adorn-char nc 'datumc 'datumc-string-unmatched))
        ((char=? nc #\|) (adorn-char nc 'datumc 'datumc-ident-unmatched))
        ((char=? nc #\;) (adorn-char nc 'linec 'linec))
        ((memc nc compound-begin-chars) (begin-datumc-compound! ac-list nc))
        ((memc nc '(#\) #\] #\})) (end-datumc-compound! ac-list nc))
        ((or (memc nc '(#\space #\newline #\tab #\' #\` #\,))
             (and (char=? nc #\@) (memc pc '(#\' #\` #\,))))
         (adorn-char nc 'datumc '~datumc))
        (else (adorn-char nc 'datumc 'datumc-simple-begin))))

(define (handle~datumc-compound! ac-list nc)
  (cond ((char=? nc #\#) (adorn-char nc 'datumc '~datumc-compound))
        ((char=? nc #\") (adorn-char nc 'datumc 'datumc-string-unmatched))
        ((char=? nc #\|) (adorn-char nc 'datumc 'datumc-ident-unmatched))
        ((memc nc compound-begin-chars) (begin-datumc-compound! ac-list nc))
        ((memc nc compound-end-chars) (end-datumc-compound! ac-list nc))
        (else (adorn-char nc 'datumc '~datumc-compound))))

(define (proceed-until-delimiter ac-list nc pm)
  (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (adorn-char nc pm pm))))

(define (proceed-until-newline nc pm)
  (cond ((char=? nc #\newline) (adorn-char #\newline 'whitespace #f))
        (else (adorn-char nc pm pm))))

(define (handle~hs-begin! ac-list nc)
  (cond ((char=? nc #\<)
         (revise-until! ac-list 'hs-begin 2)
         (adorn-char nc 'hs-begin '~hs-key-begin))
        ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (adorn-char nc 'invalid 'invalid))))

(define (handle:hs-key ac-list nc)
  (cond ((char=? nc #\newline) (adorn-char nc 'hs-key 'hs-key-end #f ac-list))
        (else (adorn-char nc 'hs-key 'hs-key))))

(define (handle:hs-body! ac-list nc)
  (if (char=? nc #\newline)
      (let ((line/from-hs-key (let seek ((rest ac-list) (chars '()))
                                (let* ((ac (car rest))
                                       (char (get-char ac)))
                                  (if (char=? char #\newline)
                                      (let ((stack (get-stack ac)))
                                        (set-stack! ac '())
                                        (list chars stack))
                                      (seek (cdr rest) (cons char chars)))))))
        (let ((previous-line (car line/from-hs-key))
              (from-hs-key (cadr line/from-hs-key)))
          (let* ((hs-key (cdr (chars-until from-hs-key '~hs-key-begin)))
                 (hs-key-length (length hs-key)))
            (if (or (equal? hs-key previous-line) (zero? hs-key-length))
                (begin (revise-until! ac-list 'hs-key hs-key-length)
                       (adorn-char nc 'hs-key #f))
                (adorn-char nc 'hs-body 'hs-body #f from-hs-key)))))
      (adorn-char nc 'hs-body 'hs-body)))

(define (^begin-nestc! mesg)
  (lambda (ac-list nc pac)
    (set-kind! pac 'nestc)
    (set-hop! pac 0)
    (set-stack! pac (list ac-list))
    (adorn-char nc 'nestc mesg)))
(define begin-nestc! (^begin-nestc! 'nestc-begin))
(define begin-datumc-nestc! (^begin-nestc! 'datumc-nestc-begin))

(define (^handle:nestc ~mesg+ ~mesg- mesg)
  (lambda (nc)
    (cond ((char=? nc #\#) (adorn-char nc 'nestc ~mesg+))
          ((char=? nc #\|) (adorn-char nc 'nestc ~mesg-))
          (else (adorn-char nc 'nestc mesg)))))
(define handle:nestc (^handle:nestc '~nestc+ '~nestc- 'nestc))
(define handle:datumc-nestc
  (^handle:nestc '~datumc-nestc+ '~datumc-nestc- 'datumc-nestc))

(define (nestc:peer/stack/distance ac-list)
  (let seek ((rest ac-list) (distance 0))
    (let* ((peer (car rest)) (stack (get-stack peer)))
      (cond ((null? stack) (seek (cdr rest) (+ distance 1)))
            (else (cons peer (cons stack distance)))))))

(define (^increment-nestc! mesg+)
  (lambda (ac-list nc pac)
    (let ((values (nestc:peer/stack/distance ac-list)))
      (let ((peer (car values)) (stack (cadr values)) (distance (cddr values)))
        (set-stack! peer '())
        (increment-hops! stack distance)
        (set-hop! pac 0)
        (set-stack! pac (cons ac-list stack))))
    (adorn-char nc 'nestc mesg+)))
(define increment-nestc! (^increment-nestc! 'nestc+))
(define increment-datumc-nestc! (^increment-nestc! 'datumc-nestc+))

(define (^decrement-nestc! mesg-end mesg-)
  (lambda (ac-list nc)
    (let ((values (nestc:peer/stack/distance ac-list)))
      (let ((peer (car values)) (stack (cadr values)) (distance (cddr values)))
        (let ((adjusted-distance (+ distance 1))
              (top-peer (caar (get-stack peer)))
              (rest (cdr stack)))
          (set-stack! peer '())
          (increment-hops! rest adjusted-distance)
          (let ((total-distance (+ (get-hop top-peer) adjusted-distance))
                (mesg (if (null? rest) mesg-end mesg-)))
            (set-hop! top-peer total-distance)
            (adorn-char nc 'nestc mesg (- total-distance) rest)))))))
(define decrement-nestc! (^decrement-nestc! 'nestc-end 'nestc-))
(define decrement-datumc-nestc!
  (^decrement-nestc! 'datumc-nestc-end 'datumc-nestc-))

(define (^handle~nestc+! increment-nestc! ~mesg+ mesg)
  (lambda (ac-list nc pac)
    (cond ((char=? nc #\|) (increment-nestc! ac-list nc pac))
          ((char=? nc #\#) (adorn-char nc 'nestc ~mesg+))
          (else (adorn-char nc 'nestc mesg)))))
(define handle~nestc+! (^handle~nestc+! increment-nestc! 'nestc+ 'nestc))
(define handle~datumc-nestc+!
  (^handle~nestc+! increment-datumc-nestc! 'datumc-nestc+ 'datumc-nestc))

(define (^handle~nestc-! decrement-nestc! ~mesg- mesg)
  (lambda (ac-list nc)
    (cond ((char=? nc #\#) (decrement-nestc! ac-list nc))
          ((char=? nc #\|) (adorn-char nc 'nestc ~mesg-))
          (else (adorn-char nc 'nestc mesg)))))
(define handle~nestc-! (^handle~nestc-! decrement-nestc! 'nestc- 'nestc))
(define handle~datumc-nestc-!
  (^handle~nestc-! decrement-datumc-nestc! 'datumc-nestc- 'datumc-nestc))

(define (handle:octothorpe! ac-list nc pac)
  (cond ((char=? nc #\\)
         (adorn-char nc 'default '~char-1))
        ((char=? nc #\f)
         (set-kind! pac 'false)
         (adorn-char nc 'false '~f/fvector))
        ((char=? nc #\s)
         (adorn-char nc 'default '~svector))
        ((char=? nc #\u)
         (adorn-char nc 'default '~uvector))
        ((char=? nc #\!)
         (adorn-char nc 'default '~directive/sharp))
        ((char=? nc #\t)
         (set-kind! pac 'true)
         (adorn-char nc 'true '~t))
        ((char=? nc #\;)
         (set-kind! pac 'datumc)
         (set-hop! pac 0)
         (set-stack! pac (list ac-list))
         (adorn-char nc 'datumc '~datumc))
        ((char=? nc #\|)
         (begin-nestc! ac-list nc pac))
        ((char=? nc #\&)
         (set-kind! pac 'box)
         (adorn-char nc 'box #f))
        ((char=? nc #\()
         (set-kind! pac 'vector)
         (begin-compound! ac-list nc 'vector))
        ((char=? nc #\<)
         (adorn-char nc 'default '~hs-begin))
        ((memc nc '(#\# #\b #\e #\i #\o #\x))
         (adorn-char nc 'default #f))
        ((memc nc decimal-chars)
         (adorn-char nc 'default '~label/reference))
        (else (adorn-char nc 'invalid 'invalid))))
;==============================================================================
(define (^handle:ident/string! base-sym delimiter-char end-symmetric!)
  (let ((backslash (->backslash base-sym)))
    (lambda (ac-list nc)
      (cond ((char=? nc delimiter-char) (end-symmetric! ac-list nc base-sym))
            ((char=? nc #\\) (adorn-char nc base-sym backslash))
            (else (adorn-char nc base-sym base-sym))))))

(define (^handle:ident/string-backslash! base-sym)
  (let ((esc (->esc base-sym)) (hex-x (->hex-x base-sym))
        (hex-u (->hex-u base-sym)) (hex-U (->hex-U base-sym))
        (nil-esc (->nil-esc base-sym)) (octal-1 (->octal-1 base-sym)))
    (lambda (nc pac)
      (cond ((char=? nc #\x) (adorn-char nc base-sym hex-x))
            ((char=? nc #\u) (adorn-char nc base-sym hex-u))
            ((char=? nc #\U) (adorn-char nc base-sym hex-U))
            ((char=? nc #\newline)
             (set-kind! pac esc)
             (adorn-char nc esc nil-esc))
            ((memc nc octal-chars)
             (set-kind! pac esc)
             (adorn-char nc esc octal-1))
            ((memc nc '(#\a #\b #\f #\n #\r #\t #\v #\" #\\ #\| #\? #\space))
             (set-kind! pac esc)
             (adorn-char nc esc base-sym))
            (else (adorn-char nc 'invalid 'base-sym))))))

(define (^handle:ident/string-hex-x! base-sym delimiter-char end-symmetric!)
  (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
        (hex-x (->hex-x base-sym)))
    (lambda (ac-list nc)
      (cond ((char=? nc delimiter-char) (end-symmetric! ac-list nc base-sym))
            ((char=? nc #\;)
             (revise-until! ac-list esc backslash)
             (adorn-char nc esc base-sym))
            ((memc nc hexadecimal-chars)
             (adorn-char nc base-sym hex-x))
            (else (adorn-char nc 'invalid base-sym))))))

(define (^handle:ident/string-hex-Uu! base-sym delimiter-char hex-Uu end!)
  (define U '(string-hex-U ident-hex-U datumc-string-hex-U datumc-ident-hex-U))
  (let ((esc (->esc base-sym)) (backslash (->backslash base-sym)))
    (let ((target (if (memq hex-Uu U) 8 4)))
      (lambda (ac-list nc)
        (cond ((char=? nc delimiter-char)
               (end! ac-list nc base-sym))
              ((memc nc hexadecimal-chars)
               (let ((running-total (distance-until ac-list backslash)))
                 (if (> target running-total)
                     (adorn-char nc base-sym hex-Uu)
                     (begin (revise-until! ac-list esc (+ target 1))
                            (adorn-char nc esc base-sym)))))
              (else (adorn-char nc 'invalid base-sym)))))))

(define (^handle:ident/string-nil-esc! base-sym delimiter-char end-symmetric!)
  (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
        (nil-esc (->nil-esc base-sym)))
    (lambda (ac-list nc)
      (cond ((char=? nc delimiter-char) (end-symmetric! ac-list nc base-sym))
            ((char=? nc #\\) (adorn-char nc base-sym backslash))
            ((memc nc '(#\space #\tab)) (adorn-char nc esc nil-esc))
            (else (adorn-char nc base-sym base-sym))))))

(define (^handle:ident/string-octal-1! base-sym delimiter-char end-symmetric!)
  (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
        (octal-2 (->octal-2 base-sym)))
    (lambda (ac-list nc)
      (cond ((char=? nc delimiter-char) (end-symmetric! ac-list nc base-sym))
            ((char=? nc #\\) (adorn-char nc base-sym backslash))
            ((memc nc octal-chars) (adorn-char nc esc octal-2))
            (else (adorn-char nc base-sym base-sym))))))

(define (^handle:ident/string-octal-2! base-sym delimiter-char end-symmetric!)
  (let ((backslash (->backslash base-sym)) (esc (->esc base-sym))
        (octal-1 (->octal-1 base-sym)) (octal-3 (->octal-3 base-sym)))
    (lambda (ac-list nc)
      (cond ((char=? nc delimiter-char) (end-symmetric! ac-list nc base-sym))
            ((char=? nc #\\) (adorn-char nc base-sym backslash))
            ((memc nc octal-chars)
             (adorn-char nc esc (let* ((octal-first (cadr ac-list))
                                          (first-char (get-char octal-first)))
                                     (if (memc first-char '(#\0 #\1 #\2 #\3))
                                         octal-3
                                         base-sym))))
            (else (adorn-char nc base-sym base-sym))))))

(define (ident/string-mesg-alist base)
  (list (cons 'base base)                 (cons 'unmatched (->unmatched base))
        (cons 'hex-x (->hex-x base))      (cons 'hex-U (->hex-U base))
        (cons 'hex-u (->hex-u base))      (cons 'backslash (->backslash base))
        (cons 'nil-esc (->nil-esc base))  (cons 'octal-1 (->octal-1 base))
        (cons 'octal-2 (->octal-2 base))  (cons 'octal-3 (->octal-3 base))))

(define (ident/string-mesg-list base) (map cdr (ident/string-mesg-alist base)))
(define ident/string-mesg-lists
  (map ident/string-mesg-list ident/string-base-mesgs))

(define (^ident/string-dispatch! base-sym delimiter-char end!)
  (define sym-alist (ident/string-mesg-alist base-sym))
  (define reversed-alist (map (lambda (p) (cons (cdr p) (car p))) sym-alist))
  (define (generic->specific sym) (cdr (assq sym sym-alist)))
  (define (specific->generic sym) (cdr (assq sym reversed-alist)))
  (define (generic->handler sym)
    (cond ((memq sym '(base unmatched octal-3))
           (^handle:ident/string! base-sym delimiter-char end-symmetric!))
          ((eq? sym 'backslash)
           (^handle:ident/string-backslash! base-sym))
          ((eq? sym 'hex-x)
           (^handle:ident/string-hex-x! base-sym delimiter-char end!))
          ((memq sym '(hex-U hex-u))
           (^handle:ident/string-hex-Uu! base-sym delimiter-char sym end!))
          ((eq? sym 'nil-esc)
           (^handle:ident/string-nil-esc! base-sym delimiter-char end!))
          ((eq? sym 'octal-1)
           (^handle:ident/string-octal-1! base-sym delimiter-char end!))
          ((eq? sym 'octal-2)
           (^handle:ident/string-octal-1! base-sym delimiter-char end!))))
    (lambda (ac-list nc pac pm)
      (let* ((generic-sym (specific->generic pm))
             (handler (generic->handler generic-sym)))
        (cond ((eq? generic-sym 'backslash) (handler nc pac))
              (else (handler ac-list nc))))))

(define (ident/string-dispatch! ac-list nc pac pm)
  (define string-dispatch!
    (^ident/string-dispatch! 'string #\" end-symmetric!))
  (define datumc-string-dispatch!
    (^ident/string-dispatch! 'datumc-string #\" end-datumc-symmetric!))
  (define datumc-ident-dispatch!
    (^ident/string-dispatch! 'datumc-ident #\| end-datumc-symmetric!))
  (define (^ident-dispatch! kind)
    (^ident/string-dispatch! kind #\| end-symmetric!))
  (define ident-dispatch! (^ident-dispatch! 'ident))
  (define defun-proc-ident-dispatch! (^ident-dispatch! 'defun-proc-ident))
  (define defun-param-ident-dispatch! (^ident-dispatch! 'defun-param-ident))
  (define sv-define-ident-dispatch! (^ident-dispatch! 'sv-define-ident))
  (define mv-define-ident-dispatch! (^ident-dispatch! 'mv-define-ident))
  (define named-let-ident-dispatch! (^ident-dispatch! 'named-let-ident))
  (define sv-let-ident-dispatch! (^ident-dispatch! 'sv-let-ident))
  (define mv-let-ident-dispatch! (^ident-dispatch! 'mv-let-ident))
  (define lambda-bind-ident-dispatch! (^ident-dispatch! 'lambda-bind-ident))
  (define case-lambda-bind-ident-dispatch!
    (^ident-dispatch! 'case-lambda-bind-ident))
  (define (pm->mesgs pm) (assq pm ident/string-mesg-lists))
  ((cond ((memq pm (pm->mesgs 'string)) string-dispatch!)
         ((memq pm (pm->mesgs 'datumc-string)) datumc-string-dispatch!)
         ((memq pm (pm->mesgs 'datumc-ident)) datumc-ident-dispatch!)
         ((memq pm (pm->mesgs 'ident)) ident-dispatch!)
         ((memq pm (pm->mesgs 'defun-proc-ident)) defun-proc-ident-dispatch!)
         ((memq pm (pm->mesgs 'defun-param-ident)) defun-param-ident-dispatch!)
         ((memq pm (pm->mesgs 'sv-define-ident)) sv-define-ident-dispatch!)
         ((memq pm (pm->mesgs 'mv-define-ident)) mv-define-ident-dispatch!)
         ((memq pm (pm->mesgs 'named-let-ident)) named-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'sv-let-ident)) sv-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'mv-let-ident)) mv-let-ident-dispatch!)
         ((memq pm (pm->mesgs 'lambda-bind-ident)) lambda-bind-ident-dispatch!)
         ((memq pm (pm->mesgs 'case-lambda-bind-ident))
          case-lambda-bind-ident-dispatch!)
         (else (lambda x #f)))
   ac-list nc pac pm))
;==============================================================================
(define (maybe-end-datumc! ac-list nc pac pm)
  (let ((p/d (datumc:peer/distance ac-list)))
    (let ((from-peer (car p/d)) (distance (cdr p/d)))
      (let* ((nearest-peer (car from-peer))
             (peer-stack (get-stack nearest-peer))
             (top-peer (caar peer-stack))
             (total-distance (+ distance (get-hop top-peer))))
        (set-hop! top-peer total-distance)
        (let ((rest (cdr peer-stack)))
          (set-stack! nearest-peer rest)
          (set-hop! pac (- total-distance))
          (if (null? rest)
              (begin (set-mesg! pac 'datumc-end)
                     (try-nc! ac-list nc))
              (cond ((char=? nc #\")
                     (adorn-char nc 'datumc 'datumc-string-unmatched))
                    ((char=? nc #\|)
                     (adorn-char nc 'datumc 'datumc-ident-unmatched))
                    ((and (eq? pm 'datumc#) (memc nc delimiter-chars))
                     (set-mesg! pac 'datumc-simple-end)
                     (adorn-char nc 'datumc '~datumc))
                    ((memc nc compound-begin-chars)
                     (begin-datumc-compound! ac-list nc))
                    (else (adorn-char nc 'datumc '~datumc)))))))))

(define (handle:datumc-simple! ac-list nc pac pm)
  (cond ((memc nc delimiter-chars) (maybe-end-datumc! ac-list nc pac pm))
        (else (adorn-char nc 'datumc 'datumc-simple))))

(define (handle:datumc~hvector! ~mesg prefix-strings)
  (lambda (ac-list nc pac pm)
    (let ((recent-chars (append (chars-until ac-list 'datumc#) (list nc))))
      (cond ((matches-one-of? prefix-strings recent-chars)
             (begin-compound! ac-list nc 'datumc-compound))
            ((could-match-one-of? prefix-strings recent-chars)
             (adorn-char nc 'datumc ~mesg))
            (else (revise-until! ac-list 'datumc 'datumc#
                                 (lambda (acl)
                                   (set-mesg! (car acl) 'datumc-simple-begin)))
                  (if (memc nc delimiter-chars)
                      (maybe-end-datumc! ac-list nc pac pm)
                      (adorn-char nc 'datumc 'datumc-simple)))))))
(define handle:datumc~fvector!
  (handle:datumc~hvector! '~datumc-fvector fvector-strings))
(define handle:datumc~svector!
  (handle:datumc~hvector! '~datumc-svector svector-strings))
(define handle:datumc~uvector!
  (handle:datumc~hvector! '~datumc-uvector uvector-strings))

(define (handle~datumc-directive! ac-list nc pac pm)
  (let ((tested-chars (append (chars-until ac-list 'datumc#) (list nc))))
    (cond ((matches-one-of? directives tested-chars)
           (adorn-char nc 'datumc '~datumc))
          ((could-match-one-of? directives tested-chars)
           (adorn-char nc 'datumc '~datumc-directive))
          ((memc nc delimiter-chars)
           (maybe-end-datumc! ac-list nc pac pm))
          (else (adorn-char nc 'datumc 'datumc-simple)))))

(define (hvector-char-list->symbol chars)
  (string->symbol (list->string (append (reverse (cdr (reverse (cdr chars))))
                                        '(#\v #\e #\c #\t #\o #\r)))))

(define (handle~hvector! ~mesg prefix-strings)
  (lambda (ac-list nc)
    (let* ((tested-chars (append (chars-until ac-list 'octothorpe) (list nc)))
           (matched-chars (backmatch-one-of prefix-strings tested-chars)))
      (cond (matched-chars
             (let ((kind (hvector-char-list->symbol matched-chars)))
               (revise-until! ac-list kind (- (length matched-chars) 1))
               (begin-compound! ac-list nc kind)))
            ((could-match-one-of? prefix-strings tested-chars)
             (adorn-char nc 'default ~mesg))
            ((and (not (memc nc compound-begin-chars))
                  (memc nc delimiter-chars))
             (try-nc! ac-list nc))
            (else (adorn-char nc 'invalid 'invalid))))))
(define handle~fvector!
  (handle~hvector! '~fvector fvector-strings))
(define handle~svector!
  (handle~hvector! '~svector svector-strings))
(define handle~uvector!
  (handle~hvector! '~uvector uvector-strings))

(define (^revise-when-complete kind ~mesg strings)
  (lambda (ac-list nc)
    (let* ((tested-chars (append (chars-until ac-list 'octothorpe) (list nc)))
           (matched-chars (backmatch-one-of strings tested-chars)))
      (cond (matched-chars
             (revise-until! ac-list kind (- (length matched-chars) 1))
             (adorn-char nc kind kind))
            ((could-match-one-of? strings tested-chars)
             (adorn-char nc 'default ~mesg))
            ((memc nc delimiter-chars)
             (try-nc! ac-list nc))
            (else (adorn-char nc 'invalid 'invalid))))))
(define handle~false!
  (^revise-when-complete 'false '~false '("#false")))
(define handle~true!
  (^revise-when-complete 'true '~true '("#true")))
(define handle~directive!
  (^revise-when-complete 'directive '~directive directives))
(define handle~sharp-object!
  (^revise-when-complete 'sharp-object '~sharp-object sharp-objects))

(define (handle~directive/sharp-object! ac-list nc)
  (let ((tested-chars (append (chars-until ac-list 'octothorpe) (list nc))))
    (cond ((could-match-one-of? sharp-objects tested-chars)
           (handle~sharp-object! ac-list nc))
          ((could-match-one-of? directives tested-chars)
           (handle~directive! ac-list nc))
          (else (adorn-char nc 'invalid 'invalid)))))

(define (handle~t! ac-list nc)
  (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (revise-until! ac-list 'default 2)
              (cond ((char=? nc #\r) (handle~true! ac-list nc))
                    (else (adorn-char nc 'invalid 'invalid))))))

(define (revise-unless-delimiter ac-list nc int/mesg/predicate?)
  (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (revise-until! ac-list 'default int/mesg/predicate?)
              (adorn-char nc 'invalid 'invalid))))

(define (handle~f/fvector! ac-list nc)
  (cond ((char-numeric? nc)
         (revise-until! ac-list 'default 2)
         (handle~fvector! ac-list nc))
        ((char=? nc #\a)
         (revise-until! ac-list 'default 2)
         (handle~false! ac-list nc))
        ((memc nc delimiter chars) (adorn-without-context nc))
        (else (revise-until! ac-list 'default 2)
              (adorn-char nc 'invalid 'invalid))))

(define (handle:datumc#! ac-list nc pac pm)
  (cond ((char=? nc #\!) (adorn-char nc 'datumc '~datumc-directive))
        ((char=? nc #\f) (adorn-char nc 'datumc '~datumc-fvector))
        ((char=? nc #\s) (adorn-char nc 'datumc '~datumc-svector))
        ((char=? nc #\u) (adorn-char nc 'datumc '~datumc-uvector))
        ((char=? nc #\\) (adorn-char nc 'datumc 'datumc-simple-begin))
        ((char=? nc #\() (begin-datumc-compound! ac-list nc))
        ((char=? nc #\|) (begin-datumc-nestc! ac-list nc pac))
        ((char=? nc #\;)
         (let ((p/d (datumc:peer/distance ac-list)))
           (let ((from-peer (car p/d)) (distance (cdr p/d)))
             (let* ((datumc-peer-stack (get-stack (car from-peer)))
                    (top-datumc-peer (caar datumc-peer-stack)))
               (increment-hops! datumc-peer-stack distance)
               (set-hop! pac 0)
               (set-stack! pac (cons ac-list datumc-peer-stack))
               (set-stack! top-datumc-peer '())))
           (adorn-char nc 'datumc '~datumc))
         ((memc nc delimiter-chars) (maybe-end-datumc! ac-list nc pac pm))
         (else (adorn-char nc 'datumc 'datumc-simple)))))

(define (handle~char-1! ac-list nc)
  (revise-until! ac-list 'char 2)
  (adorn-char nc 'char-body (cond ((char=? nc #\x) '~char-x)
                                  ((char=? nc #\U) '~char-U)
                                  ((char=? nc #\u) '~char-u)
                                  (else '~char-2))))

(define (handle~char-x! ac-list nc)
  (cond ((memc nc hexadecimal-chars) (adorn-char nc 'char-body '~char-x))
        ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (adorn-char nc 'invalid 'invalid))))

(define (^handle~char-Uu! ~mesg mesg)
  (let ((revise-last-two! (lambda (ac-list) (revise-until! ac-list 'char 2)))
        (target (if (eq? mesg 'char-U) 8 4)))
    (lambda (ac-list nc)
      (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
            (else (let ((distance (distance-until ac-list '~char-1)))
                    (when (= distance 1) (revise-until! ac-list 'default 3))
                    (cond ((> target distance) (adorn-char nc 'default ~mesg))
                          (else (revise-until! ac-list 'char-body (+ target 1)
                                               revise-last-two!)
                                (adorn-char nc 'char-body mesg)))))))))
(define handle~char-U! (^handle~char-Uu! '~char-U 'char-U))
(define handle~char-u! (^handle~char-Uu! '~char-u 'char-u))

(define (handle~char-2! ac-list nc)
  (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (let ((tested-chars (append (chars-until ac-list 3) (list nc))))
                (revise-until! ac-list 'default 3)
                (if (could-match-one-of? long-named-chars tested-chars)
                    (adorn-char nc 'default '~char-3)
                    (adorn-char nc 'invalid 'invalid))))))

(define (handle~char-3! ac-list nc)
  (let ((tested-chars (append (chars-until ac-list 4) (list nc))))
    (cond ((matches-one-of? short-named-chars tested-chars)
           (revise-until! ac-list 'char-body '~char-2)
           (revise-until! (cddr ac-list) 'char 2)
           (adorn-char nc 'char-body '~char-4))
          ((could-match-one-of? long-named-chars tested-chars)
           (adorn-char nc 'default '~named-char))
          ((memc nc delimiter-chars)
           (try-nc! ac-list nc))
          (else (adorn-char nc 'invalid 'invalid)))))

(define (handle~char-4! ac-list nc)
  (cond ((memc nc delimiter-chars) (try-nc! ac-list nc))
        (else (revise-until! ac-list 'default 5)
              (handle~named-char! ac-list nc))))

(define (handle~named-char! ac-list nc)
  (define (revise-first-two acl) (revise-until! (cdr acl) 'char 2))
  (let* ((tested-chars (append (chars-until ac-list 'octothorpe) (list nc)))
         (matched-chars (backmatch-one-of long-named-chars tested-chars)))
    (cond (matched-chars
           (revise-until! ac-list 'char-body '~char-2 revise-first-two)
           (adorn-char nc 'char-body 'named-char))
          ((could-match-one-of? long-named-chars tested-chars)
           (adorn-char nc 'default '~named-char))
          ((memc nc delimiter-chars)
           (try-nc! ac-list nc))
          (else (adorn-char nc 'invalid 'invalid)))))

(define (handle:abbrev ac-list nc)
  (cond ((char=? nc #\@) (adorn-char nc 'abbrev #f))
        (else (try-nc! ac-list nc))))

(define (handle~label/reference ac-list nc)
  (cond ((char=? nc #\=)
         (revise-until! ac-list 'datum-label 'octothorpe)
         (adorn-char nc 'datum-label #f))
        ((char=? nc #\#)
         (revise-until! ac-list 'datum-reference 'octothorpe)
         (adorn-char nc 'datum-reference #f))
        ((memc nc decimal-chars)
         (adorn-char nc 'default '~label/reference))
        ((memc nc delimiter-chars)
         (revise-until! ac-list 'serial-reference 'octothorpe)
         (try-nc! ac-list nc))
        (else (adorn-char nc 'invalid 'invalid))))

(define (handle~runtime-syntax! ac-list nc)
  (define (rt-syntax? ac) (eq? (get-kind ac) 'runtime-syntax))
  (let ((tested (append (chars-until ac-list '~~runtime-syntax) (list nc))))
    (cond ((matches-one-of? runtime-syntax tested)
           (revise-until! ac-list 'runtime-syntax '~~runtime-syntax)
           (adorn-char nc 'runtime-syntax '~runtime-syntax))
          ((could-match-one-of? runtime-syntax tested)
           (revise-while! ac-list 'default rt-syntax?)
           (adorn-char nc 'default '~runtime-syntax))
          ((memc nc delimiter-chars)
           (try-nc! ac-list nc))
          (else (revise-while! ac-list 'default rt-syntax?)
                (adorn-char nc 'default #f)))))

(define (define-variable-bind? ac-list)
  (and (looking-at ac-list '(~runtime-syntax))
       (matches-one-of? single-value-define-variable-syntax
                        (runtime-syntax-operator ac-list))))

(define (defun-proc-bind? ac-list)
  (and (operator-position? ac-list)
       (let ((up-1 (up-list ac-list)))
         (and (looking-at up-1 '(~runtime-syntax))
              (matches? "define" (runtime-syntax-operator up-1))))))

(define (defun-param-bind? ac-list)
  (and (not (operator-position? ac-list))
       (looking-at ac-list '( defun-proc defun-param defun-proc-ident-end
                              defun-param-ident-end ))))

(define (define-values-bind? ac-list)
  (or (looking-at ac-list '(mv-define mv-define-ident-end))
      (let ((up-1 (up-list ac-list)))
        (and (looking-at up-1 '(~runtime-syntax))
             (matches? "define-values" (runtime-syntax-operator up-1))))))

(define (named-let-var? ac-list)
  (and (looking-at ac-list '(~runtime-syntax))
       (matches? "let" (runtime-syntax-operator ac-list))))

(define (sv-let-bind? ac-list)
  (and (operator-position? ac-list)
       (let* ((up-1 (up-list ac-list))
              (up-1-start (start-of-list up-1)))
         (and (operator-position? up-1-start)
              (let ((up-2 (up-list up-1-start)))
                (and (looking-at up-2 '( ~runtime-syntax named-let
                                           named-let-ident-end ))
                     (matches-one-of? single-value-let-syntax
                                      (runtime-syntax-operator up-2))))))))

(define (mv-let-bind? ac-list)
  (or (looking-at ac-list '(mv-let mv-let-ident-end))
      (let ((up-1 (up-list ac-list)))
        (and (operator-position? up-1)
             (let* ((up-2 (up-list up-1))
                    (up-2-start (start-of-list up-2)))
               (and (operator-position? up-2-start)
                    (let ((up-3 (up-list up-2-start)))
                      (and (looking-at up-3 '(~runtime-syntax))
                           (matches? "let-values"
                                     (runtime-syntax-operator up-3))))))))))

(define (lambda-bind? ac-list)
  (or (looking-at ac-list '(lambda-bind lambda-bind-ident-end))
      (let ((up-1 (up-list ac-list)))
        (and (not (operator-position? up-1))
             (looking-at up-1 '(~~runtime-syntax ~runtime-syntax))
             (matches-one-of? '("lambda" "\x3bb;")
                              (runtime-syntax-operator up-1))))))

(define (case-lambda-bind? ac-list)
  (or (looking-at ac-list '(case-lambda-bind case-lambda-bind-ident-end))
      (let ((up-1 (up-list ac-list)))
        (and (operator-position? up-1)
             (let ((up-2 (up-list up-1)))
               (matches? "case-lambda" (runtime-syntax-operator up-2)))))))

(define (defun-proc-bind? ac-list)
  (and (operator-position? ac-list)
       (let ((up-1 (up-list ac-list)))
         (and (looking-at up-1 '(~runtime-syntax))
              (matches? "define" (runtime-syntax-operator up-1))))))

(define (defun-param-bind? ac-list)
  (and (not (operator-position? ac-list))
       (looking-at ac-list '( defun-proc defun-param defun-proc-ident-end
                              defun-param-ident-end ))))

(define (try-pm! ac-list nc pac)
  (let ((pm (get-mesg pac)))
    (case pm
      ((~char-1)                  (handle~char-1! ac-list nc))
      ((~char-x)                  (handle~char-x! ac-list nc))
      ((~char-u)                  (handle~char-u! ac-list nc))
      ((~char-U)                  (handle~char-U! ac-list nc))
      ((~char-2)                  (handle~char-2! ac-list nc))
      ((~char-3)                  (handle~char-3! ac-list nc))
      ((~char-4)                  (handle~char-4! ac-list nc))
      ((~named-char)              (handle~named-char! ac-list nc))
      ((~f/fvector)               (handle~f/fvector! ac-list nc))
      ((~false)                   (handle~false! ac-list nc))
      ((~t)                       (handle~t! ac-list nc))
      ((~true)                    (handle~true! ac-list nc))
      ((~directive/sharp)         (handle~directive/sharp-object! ac-list nc))
      ((~directive)               (handle~directive! ac-list nc))
      ((~sharp-object)            (handle~sharp-object! ac-list nc))
      ((~hs-begin)                (handle~hs-begin! ac-list nc))
      ((~hs-key-begin)            (handle:hs-key ac-list nc))
      ((~label/reference)         (handle~label/reference ac-list nc))
      ((~fvector)                 (handle~fvector! ac-list nc))
      ((~svector)                 (handle~svector! ac-list nc))
      ((~uvector)                 (handle~uvector! ac-list nc))
      ((~datumc-fvector)          (handle:datumc~fvector! ac-list nc pac pm))
      ((~datumc-svector)          (handle:datumc~svector! ac-list nc pac pm))
      ((~datumc-uvector)          (handle:datumc~uvector! ac-list nc pac pm))
      ((abbrev)                   (handle:abbrev ac-list nc))
      ((hs-key)                   (handle:hs-key ac-list nc))
      ((hs-key-end)               (handle:hs-body! ac-list nc))
      ((hs-body)                  (handle:hs-body! ac-list nc))
      ((octothorpe)               (handle:octothorpe! ac-list nc pac))
      ((linec)                    (proceed-until-newline nc pm))
      ((~~runtime-syntax)         (handle~runtime-syntax! ac-list nc))
      ((~runtime-syntax)          (handle~runtime-syntax! ac-list nc))
      ((~nestc+)                  (handle~nestc+! ac-list nc pac))
      ((~nestc-)                  (handle~nestc-! ac-list nc))
      ((nestc+)                   (handle:nestc nc))
      ((nestc-)                   (handle:nestc nc))
      ((nestc-begin)              (handle:nestc nc))
      ((nestc)                    (handle:nestc nc))
      ((~datumc-nestc+)           (handle~datumc-nestc+! ac-list nc pac))
      ((~datumc-nestc-)           (handle~datumc-nestc-! ac-list nc))
      ((datumc-nestc+)            (handle:datumc-nestc nc))
      ((datumc-nestc-)            (handle:datumc-nestc nc))
      ((datumc-nestc-begin)       (handle:datumc-nestc nc))
      ((datumc-nestc)             (handle:datumc-nestc nc))
      ((shebang)                  (proceed-until-newline nc pm))
      ((~datumc)                  (handle~datumc! ac-list nc))
      ((~datumc-directive)        (handle~datumc-directive! ac-list nc pac pm))
      ((datumc-compound-end)      (handle~datumc! ac-list nc))
      ((datumc-ident-end)         (handle~datumc! ac-list nc))
      ((datumc-nestc-end)         (handle~datumc! ac-list nc))
      ((datumc-simple-end)        (handle~datumc! ac-list nc))
      ((datumc-string-end)        (handle~datumc! ac-list nc))
      ((datumc-simple)            (handle:datumc-simple! ac-list nc pac pm))
      ((datumc-simple-begin)      (handle:datumc-simple! ac-list nc pac pm))
      ((datumc#)                  (handle:datumc#! ac-list nc pac pm))
      ((~datumc-compound)             (handle~datumc-compound! ac-list nc))
      ((datumc-compound-simple)       (handle~datumc-compound! ac-list nc))
      ((datumc-compound-unmatched)    (handle~datumc-compound! ac-list nc))
      ((datumc-subcompound-unmatched) (handle~datumc-compound! ac-list nc))
      ((datumc-subcompound-end)       (handle~datumc-compound! ac-list nc))
      ((invalid)                  (proceed-until-delimiter ac-list nc pm))
      ((char-U char-u directive false named-char sharp-object true)
       (revise-unless-delimiter ac-list nc 'octothorpe))
      (else (if (memq pm bind-mesgs)
                (proceed-until-delimiter ac-list nc pm)
                (ident/string-dispatch! ac-list nc pac pm))))))

(define (operator-position? ac-list)
  (and (not (null? ac-list))
       (let ((ac (car ac-list)))
         (or (memq (get-mesg ac) list-begin-mesgs)
             (and (memq (get-kind ac) atmosphere-kinds)
                  (operator-position? (cdr ac-list)))))))

(define (start-of-list ac-list)
  (if (null? ac-list)
      '()
      (let* ((ac (car ac-list)) (mesg (get-mesg ac)))
        (cond ((memq mesg '(list-unmatched sublist-unmatched)) ac-list)
              ((eq? mesg 'list-end) '())
              ((eq? mesg 'sublist-end)
               (let ((stack (get-stack ac)))
                 (start-of-list (if (null? stack)
                                    (let skip ((rest (cdr ac-list))
                                               (i (get-hop ac)))
                                      (if (zero? i)
                                          rest
                                          (skip (cdr ac-list) (+ i 1))))
                                    (car stack)))))
              (else (start-of-list (cdr ac-list)))))))

(define (up-list ac-list)
  (let ((list-start (start-of-list ac-list)))
    (if (null? list-start)
        '()
        (cdr list-start))))

(define (~~runtime-syntax? ac-list nc)
  (and (operator-position? ac-list)
       (could-match-one-of? runtime-syntax (list nc))))

(define (runtime-syntax-operator ac-list)
  (let seek ((rest ac-list) (buffer '()))
    (if (null? rest)
        buffer
        (let* ((ac (car rest)) (mesg (get-mesg ac)))
          (cond ((eq? (get-kind ac) 'runtime-syntax)
                 (seek (cdr rest) (cons (get-char ac) buffer)))
                ((eq? mesg 'list-end) '())
                ((eq? mesg 'sublist-end)
                 (seek (let skip ((rest (cdr rest)) (i (get-hop ac)))
                         (if (zero? i)
                             rest
                             (skip (cdr rest) (+ i 1)))) '()))
                ((memq mesg list-begin-mesgs) buffer)
                (else (seek (cdr rest) '())))))))

(define (try-nc! ac-list nc)
  (cond ((char=? nc #\") (begin-symmetric ac-list nc 'string))
        ((char=? nc #\|) (begin-symmetric ac-list nc 'ident))
        ((memc nc compound-begin-chars) (begin-compound! ac-list nc 'list))
        ((memc nc compound-end-chars) (end-compound! ac-list nc))
        (else #f)))

(define (try-context! ac-list nc pac)
  (define (^begin-bind kind)
    (let ((identifier-kind ((append-to-symbol "-ident") kind)))
      (lambda (ac-list nc)
        (cond ((char=? nc #\|) (begin-symmetric ac-list nc identifier-kind))
              (else (adorn-char nc kind kind))))))
  (define begin-defun-proc (^begin-bind 'defun-proc))
  (define begin-defun-param (^begin-bind 'defun-param))
  (define begin-sv-define (^begin-bind 'sv-define))
  (define begin-mv-define (^begin-bind 'mv-define))
  (define begin-named-let (^begin-bind 'named-let))
  (define begin-sv-let (^begin-bind 'sv-let))
  (define begin-mv-let (^begin-bind 'mv-let))
  (define begin-lambda-bind (^begin-bind 'lambda-bind))
  (define begin-case-lambda-bind (^begin-bind 'case-lambda-bind))
  (define (default+no-mesg? ac)
    (and (not (get-mesg ac)) (eq? (get-kind ac) 'default)))
  (define (valid-keyword? ac-list nc pc)
    (and (char=? pc #\:) (memc nc delimiter-chars)
         (let ((rest (cdr ac-list)))
           (and (not (null? rest))
                (not (memc (get-char (car rest)) delimiter-chars))))))
  (let ((pc (get-char pac)))
    (cond ((not pc) #f)
          ((and (not (char=? nc #\|)) (memc nc delimiter-chars))
           (try-nc! ac-list nc))
          ((valid-keyword? ac-list nc pc)
           (revise-while! ac-list 'keyword default+no-mesg?)
           (try-nc! ac-list nc))
          ((defun-proc-bind? ac-list)      (begin-defun-proc ac-list nc))
          ((defun-param-bind? ac-list)     (begin-defun-param ac-list nc))
          ((define-variable-bind? ac-list) (begin-sv-define ac-list nc))
          ((define-values-bind? ac-list)   (begin-mv-define ac-list nc))
          ((named-let-var? ac-list)        (begin-named-let ac-list nc))
          ((sv-let-bind? ac-list)          (begin-sv-let ac-list nc))
          ((mv-let-bind? ac-list)          (begin-mv-let ac-list nc))
          ((lambda-bind? ac-list)          (begin-lambda-bind ac-list nc))
          ((case-lambda-bind? ac-list)     (begin-case-lambda-bind ac-list nc))
          ((~~runtime-syntax? ac-list nc)
           (if (matches-one-of? runtime-syntax (list nc))
               (adorn-char nc 'runtime-syntax '~~runtime-syntax)
               (adorn-char nc 'default '~~runtime-syntax)))
          (else #f))))

(define (adorn-loop! unadorned adorned)
  (if (null? unadorned)
      adorned
      (let* ((nc (car unadorned))
             (new-ac (if (null? adorned)
                         (or (try-nc! adorned nc) (adorn-without-context nc))
                         (let ((pac (car adorned)))
                           (or (try-pm! adorned nc pac)
                               (try-context! adorned nc pac)
                               (try-nc! adorned nc)
                               (adorn-without-context nc))))))
        (adorn-loop! (cdr unadorned) (cons new-ac adorned)))))

(define (adorn! chars . so-far)
  (define (maybe-handle:shebang chars adorned)
    (if (and (null? adorned) (not (null? chars)) (not (null? (cdr chars)))
             (char=? (car chars) #\#) (char=? (cadr chars) #\!))
        (let ((trunc (cddr chars)))
          (if (and (not (null? trunc)) (memc (car trunc) '(#\/ #\space #\tab)))
              (let ((first-ac (adorn-char #\# 'shebang 'shebang))
                    (second-ac (adorn-char #\! 'shebang 'shebang)))
                (adorn-loop! trunc (list first-ac second-ac)))
              (adorn-loop! chars adorned)))
        (adorn-loop! chars adorned)))
  (let ((char-list (cond ((string? chars) (string->list chars))
                         ((char? chars) (list chars))
                         (else chars))))
    (maybe-handle:shebang char-list (if (null? so-far) so-far (car so-far)))))

;; (define (special-strings symbol)
;;   (define string-lists
;;       (lambda ("lambda" "\x3bb;"))
;;       (long-quote ("quote"))
;;       (short-quote ("'"))
;;   (cadr (assq symbol string-lists)))
;==============================================================================
      ;; (( #\. ) (when (and pac (delimiter? (get-char pac)))
      ;;            (set-kind! nac 'dot)))
 ;; (compound-peer! nac #\( adorned index))
;==============================================================================
;; (define (quoted? ac-list)
;;   (define (case-key? ac-list)
;;     (let* ((inner (start-of-list ac-list)) (outer (up-list inner)))
;;       (and (operator-position? inner)
;;            (operator-position? (cdr inner))
;;            (operator-position? outer)
;;            (let ((outside (cdr outer)))
;;              (and (not (operator-position? outside))
;;                   (let loop ((rest outside) (buffer '()))
;;                     (and (not (null? rest))
;;                          (let* ((ac (car rest)) (kind (get-kind ac)))
;;                            (if (eq? kind 'runtime-syntax)
;;                                (loop (cdr rest) (cons (get-char ac) buffer))
;;                                (if (and (eq? kind 'list)
;;                                         (char=? (get-char ac) #\()
;;                                         (not (get-peer ac)))
;;                                    (string=? (list->string buffer) "case")
;;                                    (loop (cdr rest) '())))))))))))
;;   (and (not (null? ac-list))
;;        (or (looking-at 'quote ac-list)
;;            (case-key? ac-list)
;;            (let ((enclosing-list (up-list ac-list)))
;;              (and (not (null? enclosing-list))
;;                   (quoted? (cdr enclosing-list)))))))
