;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define-record-type achar
  (adorn-char c k m p)
  adorned-char?
  (c get-char)
  (k get-kind set-kind!)
  (m get-mesg set-mesg!)
  (p get-peer set-peer!))
;==============================================================================
(define (memc c l) (member c l char=?))
(define (octal-char? c) (memc c '(#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7)))
(define (decimal-char? c) (or (octal-char? c) (memc c '(#\8 #\9))))
(define (hexadecimal-char? c) (or (decimal-char? c)
                                  (memc c '(#\a #\b #\c #\d #\e #\f
                                            #\A #\B #\C #\D #\E #\F))))
(define (delimiter? c)
  (memc c '( #\) #\( #\space #\newline #\tab #\" #\; #\| #\\ )))

(define (atmosphere-kind? kind)
  (memq kind '(whitespace linec datumc nestc directive)))

(define (atmosphere? ac) (atmosphere-kind? (get-kind ac)))

(define set-kind+mesg!
  (case-lambda
    ((ac km) (set-kind! ac km) (set-mesg! ac km))
    ((ac k m) (set-kind! ac k) (set-mesg! ac m))))

(define (revise! ac-list old-kind new-kind #!optional (ep? not))
  (unless (null? ac-list)
    (let ((ac (car ac-list)))
      (when (eq? (get-kind ac) old-kind)
        (set-kind! ac new-kind)
        (unless (ep? ac)
          (revise! (cdr ac-list) old-kind new-kind ep?))))))

(define (start-of-kind ac-list k)
  (cond ((null? ac-list) '())
        ((eq? (get-kind (car ac-list)) k) (start-of-kind (cdr ac-list) k))
        (else ac-list)))

(define (char-second? ac) (eq? (get-mesg ac) '~char-second))
;; (define (octo-start? ac) (eq? (get-mesg ac) 'octothorpe))
;==============================================================================
(define (get+set-nested-comment-info! symbol ac-list)
  (define (get-nested-comment-info)
    (let loop ((rest (cdr ac-list)))
      (unless (null? rest)
        (if (memq (get-mesg (car rest)) '(nestc- nestc+ nestc-begin))
            (let ((previous-cache-ac (cadr rest))
                  (operator (if (symbol=? symbol 'nestc-) - +)))
              (values (operator (get-mesg previous-cache-ac) 1)
                      (get-peer previous-cache-ac)))
            (loop (cdr rest))))))
  (call-with-values get-nested-comment-info
    (lambda (nesting peer)
      (let ((cache-ac (cadr ac-list)))
        (set-mesg! cache-ac nesting) (set-peer! cache-ac peer) nesting))))

(define (get-hs-key ac-list)
  (let loop ((key '()) (rest ac-list))
    (if (null? rest)
        '()
        (let* ((ac (car rest))
               (kind (get-kind ac)))
          (cond ((eq? kind 'hs-key) (loop (cons (get-char ac) key) (cdr rest)))
                ((eq? kind 'hs-begin) key)
                (else (loop key (cdr rest))))))))

(define (unused-datum-comment? ac-list)
  (and ac-list (not (null? ac-list))
       (let ((ac (car ac-list)))
         (or (and (number? (get-peer ac)) (eq? (get-mesg ac) '~datumc))
             (and (memq (get-kind ac) '(datumc linec nestc))
                  (unused-datum-comment? (cdr ac-list)))))))
;==============================================================================
(define (datum-comment-peer! ending-ac ac-list index)
  (and (not (null? ac-list))
       (let* ((ac (car ac-list))
              (peer (get-peer ac)))
         (if (and peer (char=? (get-char ac) #\;) (eq? (get-mesg ac) '~datumc))
             (begin (set-mesg! ac peer)
                    (set-peer! ac index)
                    (set-peer! ending-ac peer)
                    ac-list)
             (datum-comment-peer! ending-ac (cdr ac-list) index)))))

(define (nested-comment-peer! ending-ac ac-list index)
  (unless (null? ac-list)
    (if (eq? (get-mesg (car ac-list)) 'nestc-begin)
        (let* ((ac (cadr ac-list)) (ac-index (get-peer ac)))
          (set-mesg! ac ac-index)
          (set-peer! ac index)
          (set-mesg! ending-ac index)
          (set-peer! ending-ac ac-index))
        (nested-comment-peer! ending-ac (cdr ac-list) index))))

(define (compound-peer! nac peer-char ac-list index)
  (define (kind->empty-kind kind)
    (cdr (assq kind '((list    . empty-list)    (vector  . empty-vector)
                      (fvector . empty-fvector) (svector . empty-svector)
                      (uvector . empty-uvector)))))
  (let loop ((rest ac-list) (empty? #t))
    (if (null? rest)
        (set-kind! nac 'unmatched)
        (let ((ac (car rest)))
          (let ((char (get-char ac)) (mesg (get-mesg ac)) (peer (get-peer ac)))
            (if (and (char=? char peer-char) (number? mesg) (not peer))
                (let ((kind (get-kind ac)))
                  (if empty?
                      (let ((empty-kind (kind->empty-kind kind)))
                        (set-kind! nac empty-kind)
                        (set-kind! ac empty-kind)
                        (revise! (cdr rest) kind empty-kind octo-start?))
                      (set-kind! nac kind))
                  (set-mesg! nac index)
                  (set-peer! nac mesg)
                  (set-peer! ac index))
                (loop (cdr rest) (and empty? (atmosphere? ac)))))))))

(define (symmetric-peer! peer-char nac ac-list index)
  (let loop ((rest ac-list))
    (unless (null? rest)
      (let ((ac (car rest)))
        (if (char=? peer-char (get-char ac))
            (let ((peer (get-peer ac)))
              (if (number? peer)
                  (begin (set-mesg! nac index)
                         (set-peer! nac peer)
                         (set-mesg! ac peer)
                         (set-peer! ac index))
                  (loop (cdr rest))))
            (loop (cdr rest)))))))
;==============================================================================
(define (operator-position? ac-list)
  (and (not (null? ac-list))
       (let ((ac (car ac-list)))
         (if (atmosphere? ac)
             (operator-position? (cdr ac-list))
             (and (eq? (get-kind ac) 'list) (char=? (get-char ac) #\())))))

(define (quoted? ac-list)
  (define (case-key? ac-list)
    (let* ((inner (start-of-list ac-list)) (outer (up-list inner)))
      (and (operator-position? inner)
           (operator-position? (cdr inner))
           (operator-position? outer)
           (let ((outside (cdr outer)))
             (and (not (operator-position? outside))
                  (let loop ((rest outside) (buffer '()))
                    (and (not (null? rest))
                         (let* ((ac (car rest)) (kind (get-kind ac)))
                           (if (eq? kind 'runtime-syntax)
                               (loop (cdr rest) (cons (get-char ac) buffer))
                               (if (and (eq? kind 'list)
                                        (char=? (get-char ac) #\()
                                        (not (get-peer ac)))
                                   (string=? (list->string buffer) "case")
                                   (loop (cdr rest) '())))))))))))
  (and (not (null? ac-list))
       (or (looking-at 'quote ac-list)
           (case-key? ac-list)
           (let ((enclosing-list (up-list ac-list)))
             (and (not (null? enclosing-list))
                  (quoted? (cdr enclosing-list)))))))
;==============================================================================
(define (special-strings symbol)
  (define string-lists
    '((directive ("#!fold-case" "#!no-fold-case"))
      (false ("#false"))
      (fvector ("#f32(" "#f64("))
      (lambda ("lambda" "\x3bb;"))
      (long-quote ("quote"))
      (mv-define ("define-values"))
      (mv-let ("let-values" "let*-values"))
      (named-let ("let"))
      (sharp ("#!eof" "#!key" "#!optional" "#!rest" "#!void"))
      (short-named-char ("#\\esc" "#\\nul"))
      (short-quote ("'"))
      (sv-define ("define"))
      (sv-let ("let" "let*" "letrec" "letrec*" "parameterize"))
      (svector ("#s8(" "#s16(" "#s32(" "#s64("))
      (true ("#true"))
      (uvector ("#u8(" "#u16(" "#u32(" "#u64("))
      (long-named-char
       ("#\\null" "#\\alarm" "#\\backspace" "#\\tab" "#\\space" "#\\newline"
        "#\\return" "#\\delete" "#\\escape" "#\\page" "#\\vtab" "#\\linefeed"))
      (runtime-syntax
       ("and" "begin" "c-declare" "c-define" "c-define-type" "c-initialize"
        "c-lambda" "case" "case-lambda" "cond" "cond-expand" "declare" "define"
        "define-library" "define-macro" "define-record-type" "define-structure"
        "define-syntax" "define-type" "define-type-of-thread" "define-values"
        "delay" "delay-force" "do" "else" "future" "guard" "if" "import"
        "include" "include-ci" "\x3bb;" "lambda" "let" "let*" "let*-values"
        "let-values" "letrec" "letrec*" "letrec*-values" "letrec-values"
        "namespace" "or" "parameterize" "quasiquote" "quote" "r7rs-guard"
        "receive" "set!" "syntax-error" "syntax-rules" "this-source-file"
        "unless" "when"))))
  (cadr (assq symbol string-lists)))

(define (get-matching-kind+ep? spec)
  (case spec
    (( false true sharp fvector svector uvector )
     (values 'default octo-start?))
    (( lambda sv-define sv-let named-let mv-define mv-let )
     (values 'runtime-syntax #f))
    (( datumc-directive )
     (values 'datumc (lambda (ac) (eq? (get-mesg ac) 'datumc#))))
    (else (values #f #f))))

(define (looking-at spec ac-list #!key kind ep?)
  (define (truncate-acl trunc-predicate? ac-list)
    (if (null? ac-list)
        ac-list
        (if (trunc-predicate? (car ac-list))
            (truncate-acl trunc-predicate? (cdr ac-list))
            ac-list)))
  (define (looking-at-char-list char-list ac-list #!key k ep?)
    (let loop ((cl-rest char-list) (ac-rest ac-list))
      (if (null? cl-rest)
          ac-rest
          (and (not (null? ac-rest))
               (let ((next-char (car cl-rest))
                     (next-ac (car ac-rest)))
                 (and (or (not k) (eq? k (get-kind next-ac)))
                      (char=? next-char (get-char next-ac))
                      (let ((cdr-cl-rest (cdr cl-rest)))
                        (if (and ep? (null? cdr-cl-rest))
                            (and (ep? next-ac) ac-rest)
                            (loop cdr-cl-rest (cdr ac-rest))))))))))
  (define (looking-at-one-of list-of-char-lists ac-list #!key k ep?)
    (and (not (null? list-of-char-lists))
         (or (looking-at-char-list (car list-of-char-lists)
                                   ac-list k: k ep?: ep?)
             (looking-at-one-of (cdr list-of-char-lists)
                                ac-list k: k ep?: ep?))))
  (if (symbol? spec)
      (let-values (((k ep?) (get-matching-kind+ep? spec)))
        (case spec
          (( sv-define sv-let named-let mv-let mv-define lambda )
           (looking-at-one-of (get-char-lists spec)
                              (truncate-acl (lambda (ac)
                                              (atmosphere? ac))
                                            ac-list) k: k ep?: ep?))
          (( datumc )
           (looking-at-char-list
            '(#\; #\#)
            (truncate-acl (lambda (ac)
                            (let ((kind (get-kind ac)))
                              (or (memq kind '(linec nestc datumc-directive))
                                  (and (eq? kind 'datumc)
                                       (memc (get-char ac) '(#\space
                                                             #\newline
                                                             #\tab))))))
                          ac-list)
            k: 'datumc ep?: octo-start?))
          (( directive )
           (looking-at-one-of (get-char-lists spec)
                              (truncate-acl
                               (lambda (ac)
                                 (memq (get-kind ac)
                                       '(whitespace datumc linec nestc))))
                              k: k ep?: ep?))
          (( false true )
           (looking-at-one-of (get-char-lists spec) ac-list k: k ep?: ep?))
          (( keyword )
           (let ((ac (car ac-list)))
             (and (char=? (get-char ac) #\:)
                  (eq? (get-kind ac) 'default)
                  (not (get-mesg ac))
                  (not (null? (cdr ac-list)))
                  (let ((prev (cadr ac-list)))
                    (let ((prev-char (get-char prev))
                          (prev-kind (get-kind prev))
                          (prev-mesg (get-mesg prev)))
                      (or (and (eq? prev-kind 'identifier)
                               (char=? prev-char #\|)
                               (number? prev-mesg)
                               (number? (get-peer prev)))
                          (and (eq? prev-kind 'default)
                               (not (delimiter? prev-char))
                               (or (not prev-mesg)
                                   (eq? prev-mesg 'runtime-syntax)))))))))
          (( quote )
           (let ((truncated-acl (truncate-acl (lambda (ac)
                                                (atmosphere? ac))
                                              ac-list)))
             (or (looking-at-one-of (get-char-lists 'short-quote) truncated-acl
                                    k: 'abbrev)
                 (looking-at-one-of (get-char-lists 'long-quote) truncated-acl
                                    k: 'runtime-syntax))))
          (( runtime-syntax )
           (let ((acl (looking-at-one-of (get-char-lists 'runtime-syntax)
                                         ac-list
                                         k: k ep?: ep?)))
             (and acl (operator-position? acl))))
          (else
           (looking-at-one-of (get-char-lists spec) ac-list k: k ep?: ep?))))
      (looking-at-char-list spec ac-list k: kind ep?: ep?)))


(define (char-list-backmatch? goal actual)
  (let backmatch-loop ((goal (reverse goal)) (actual (reverse actual)))
    (or (null? goal)
        (and (not (null? actual))
             (char=? (car goal) (car actual))
             (backmatch-loop (cdr goal) (cdr actual))))))

(define (backmatch? goal actual)
  (let ((cl-goal (if (string? goal) (string->list goal) goal))
        (cl-actual (if (string? actual) (string->list actual) actual)))
    (char-list-backmatch? cl-goal cl-actual)))

(define (backmatch-one-of? goals actual)
  (and (not (null? goals))
       (or (backmatch? (car goals) actual)
           (backmatch-one-of? (cdr goals) actual))))

(define (char-list-could-match? goal actual)
  (or (null? actual)
      (and (not (null? goal))
           (char=? (car goal) (car actual))
           (char-list-could-match? (cdr goal) (cdr actual)))))

(define (could-match? goal actual)
  (let ((cl-goal (if (string? goal) (string->list goal) goal))
        (cl-actual (if (string? actual) (string->list actual) actual)))
    (char-list-could-match? cl-goal cl-actual)))

(define (could-match-one-of? goals actual)
  (and (not (null? goals))
       (or (could-match? (car goals) actual)
           (could-match-one-of? (cdr goals) actual))))

(define (distance-until ac-list char/mesg)
  (cond ((char? char/mesg)
         (let loop ((rest ac-list) (i 0))
           (cond ((null? rest) (error "Not found" char/mesg))
                 ((char=? (get-char (car rest)) char/mesg) i)
                 (else (loop (cdr rest) (+ i 1))))))
        ((symbol? char/mesg)
         (let loop ((rest ac-list) (i 0))
           (cond ((null? rest) (error "Not found" char/int/mesg/predicate?))
                 ((eq? (get-mesg (car rest)) char/mesg) i)
                 (else (loop (cdr rest) (+ i 1))))))))

(define (chars-until ac-list char/int/mesg/predicate?)
  (cond ((char? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list))
           (if (null? rest)
               chars
               (let ((char (get-char (car rest))))
                 (if (char=? char char/int/mesg/predicate?)
                     (cons char chars)
                     (loop (cons char chars) (cdr rest)))))))
        ((integer? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list) (i char/int/mesg/predicate?))
           (if (or (zero? i) (null? rest))
               chars
               (loop (cons (get-char (car rest)) chars) (cdr rest) (- i 1)))))
        ((symbol? char/int/mesg/predicate?)
         (let loop ((chars '()) (rest ac-list))
           (if (null? rest)
               chars
               (let ((ac (car rest)))
                 (let ((char (get-char ac))
                       (mesg (get-mesg ac)))
                   (if (eq? mesg char/int/mesg/predicate?)
                       (cons char chars)
                       (loop (cons char chars) (cdr rest))))))))
        (else (let loop ((chars '()) (rest ac-list))
                (if (null? rest)
                    chars
                    (let ((ac (car rest)))
                      (if (char/int/mesg/predicate? ac)
                          (cons (get-char ac) rest)
                          (loop (cons (get-char ac) chars) (cdr rest)))))))))

(define (revise-until! ac-list new-kind int/mesg/predicate? #!optional end-act)
  (cond ((integer? int/mesg/predicate?)
         (let loop ((rest ac-list) (i int/mesg/predicate?))
           (unless (or (null? rest) (> 1 i))
             (let ((ac (car rest)))
               (set-kind! ac new-kind)
               (when (and end-act (= i 1)) (end-act ac))
               (loop (cdr rest) (- i 1))))))
        ((symbol? int/mesg/predicate?)
         (let loop ((rest ac-list))
           (unless (null? rest)
             (let ((ac (car rest)))
               (set-kind! ac new-kind)
               (if (eq? (get-mesg ac) int/mesg/predicate?)
                   (when end-act (end-act ac))
                   (loop (cdr rest)))))))
        (else (let loop ((rest ac-list))
                (unless (null? rest)
                  (let ((ac (car rest)))
                    (if (int/mesg/predicate? ac)
                        (begin (set-kind! ac new-kind)
                               (when end-act (end-act ac)))
                        (loop (cdr rest)))))))))

(define (maybe-match? c acl strings until-mesg)
  (could-match-one-of? strings (append (chars-until acl until-mesg) (list c))))

(define (does-match? c acl strings until-mesg)
  (backmatch-one-of? strings (append (chars-until acl until-mesg) (list c))))

(define directives '("#!fold-case" "#!no-fold-case"))
(define (is-directive? c acl) (does-match? c acl directives 'octothorpe))
(define (maybe-directive? c acl) (maybe-match? c acl directives 'octothorpe))

(define sharps '("#!eof" "#!key" "#!optional" "#!rest" "#!void"))
(define (is-sharp? c acl) (does-match? c acl sharps 'octothorpe))
(define (maybe-sharp? c acl) (maybe-match? c acl sharps 'octothorpe))

(define fvectors '("#f32(" "#f64("))
(define uvectors '("#u8(" "#u16(" "#u32(" "#u64("))
(define svectors '("#s8(" "#s16(" "#s32(" "#s64("))
(define (maybe-fvector? c acl) (maybe-match? c acl fvectors 'octothorpe))
(define (maybe-svector? c acl) (maybe-match? c acl svectors 'octothorpe))
(define (maybe-uvector? c acl) (maybe-match? c acl uvectors 'octothorpe))
(define (is-fvector? c acl) (does-match? c acl fvectors 'octothorpe))
(define (is-svector? c acl) (does-match? c acl svectors 'octothorpe))
(define (is-uvector? c acl) (does-match? c acl uvectors 'octothorpe))

(define (is-false? c acl) (does-match? c acl '("#false") 'octothorpe))
(define (maybe-false? c acl) (maybe-match? c acl '("#false") 'octothorpe))
(define (is-true? c acl) (does-match? c acl '("#true") 'octothorpe))
(define (maybe-true? c acl) (maybe-match? c acl '("#true") 'octothorpe))

(define named-chars
  '("#\\null" "#\\alarm" "#\\backspace" "#\\tab" "#\\space" "#\\newline"
    "#\\return" "#\\delete" "#\\escape" "#\\page" "#\\vtab" "#\\linefeed"))
(define (maybe-named-char? c acl) (maybe-match? c acl named-chars 'octothorpe))
(define (is-named-char? c acl) (does-match? c acl named-chars 'octothorpe))

(define short-named-chars '("#\\esc" "#\\nul"))
(define (maybe-short-named-char? c acl)
  (maybe-match? c acl short-named-chars 'octothorpe))
(define (is-short-named-char? c acl)
  (does-match? c acl short-named-chars 'octothorpe))

(define (ac-find-by ac-list predicate?)
  (cond ((null? ac-list) '())
        ((predicate? (car ac-list)) ac-list)
        (else (ac-find-by (cdr ac-list) predicate?))))

(define (find-by-char ac-list char)
  (ac-find-by ac-list (lambda (ac) (char=? (get-char ac) char))))
(define (find-by-kind ac-list kind)
  (ac-find-by ac-list (lambda (ac) (eq? (get-kind ac) kind))))
(define (find-by-mesg ac-list mesg)
  (ac-find-by ac-list (lambda (ac) (eq? (get-mesg ac) mesg))))

(define (find-nearest-peer ac-list)
  (if (null? ac-list)
      '()
      (let ((ac (car ac-list)))
        (if (get-peer ac)
            ac
            (find-nearest-peer (cdr ac-list))))))

(define (ac-trim ac-list predicate?)
  (if (predicate? (car ac-list))
      (ac-trim (cdr ac-list) predicate?)
      ac-list))

;; (define (start-of-bind? ac-list)
;;   (let ((cdr-ac-list (cdr ac-list)))
;;         (and (not (null? cdr-ac-list))
;;              (delimiter? (get-char (car cdr-ac-list)))
;;              (let loop ((binders '(lambda define-proc define-var named-let-var
;;                                    sv-let-formal mv-define mv-let-formal
;;                                    named-let-formal)))
;;                (and (not (null? binders))
;;                     (or (start-of? (car binders) ac-list)
;;                         (loop (cdr binders))))))))

(define (unmatched-lparen? ac)
  (and (eq? (get-kind ac) 'list)
       (not (get-peer ac))
       (char=? (get-char ac) #\()))

(define (start-of-list ac-list #!optional (predicate? unmatched-lparen?))
  (cond ((null? ac-list) '())
        ((predicate? (car ac-list)) ac-list)
        (else (start-of-list (cdr ac-list) predicate?))))

(define (up-list ac-list #!optional (predicate? unmatched-lparen?))
  (if (null? ac-list)
      '()
      (start-of-list (cdr ac-list) predicate?)))

(define (start-of? token ac-list)
  (and (not (null? ac-list))
       (let ((ac (car ac-list)) (rest (cdr ac-list)))
         (and (symbol=? (get-kind ac) 'default)
              (case token
                (( lambda )
                 (let ((list-start (start-of-list ac-list)))
                   (and (not (null? list-start))
                        (let ((outside (cdr list-start)))
                          (and (not (operator-position? outside))
                               (looking-at 'lambda outside))))))
                (( define-proc )
                 (and (operator-position? rest)
                      (let ((cdr-signature (cdr (start-of-list ac-list))))
                        (and (not (operator-position? cdr-signature))
                             (looking-at 'sv-define cdr-signature)))))
                (( define-var )
                 (and (not (null? rest))
                      (not (operator-position? rest))
                      (looking-at 'sv-define rest)))
                (( named-let-var )
                 (and (not (null? rest))
                      (not (operator-position? rest))
                      (looking-at 'named-let rest)))
                (( sv-let-formal )
                 (and (operator-position? rest)
                      (let* ((inner (start-of-list ac-list))
                             (outer (up-list inner)))
                        (and (operator-position? inner)
                             (operator-position? outer)
                             (let ((outside (cdr outer)))
                               (and (not (operator-position? outside))
                                    (looking-at 'sv-let outside)))))))
                (( mv-define )
                 (let ((var-list (start-of-list ac-list)))
                   (and (operator-position? var-list)
                        (let ((outside (cdr var-list)))
                          (and (not (operator-position? outside))
                               (looking-at 'mv-define outside))))))
                (( mv-let-formal )
                 (let ((inner (start-of-list ac-list)))
                   (and (operator-position? inner)
                        (operator-position? (cdr inner))
                        (let ((mid (up-list inner)))
                          (and (operator-position? mid)
                               (let ((outer (up-list mid)))
                                 (and (operator-position? outer)
                                      (let ((outside (cdr outer)))
                                        (and (not (operator-position? outside))
                                             (looking-at 'mv-let
                                                          outside))))))))))
                (( named-let-formal )
                 (and (operator-position? rest)
                      (let* ((inner (start-of-list ac-list))
                             (outer (up-list inner)))
                        (and (operator-position? inner)
                             (operator-position? outer)
                             (let ((outside (cdr outer)))
                               (and (not (operator-position? outside))
                                    (let loop ((rest outside) (named? #f))
                                      (and (not (null? rest))
                                           (let ((kind (get-kind (car rest))))
                                             (cond ((atmosphere-kind? kind)
                                                    (loop (cdr rest) named?))
                                                   ((eq? kind 'bind)
                                                    (loop (cdr rest) #t))
                                                   (else (and named?
                                                              (looking-at
                                                               'named-let
                                                               rest)))))))))))))
                 (else (error "Unknown token")))))))
;==============================================================================
      ;; (( #\. ) (when (and pac (delimiter? (get-char pac)))
      ;;            (set-kind! nac 'dot)))
 ;; (compound-peer! nac #\( adorned index))

(define-macro (%ident/string backslash delim fallback)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((char=? nc #\\)
          (box-ac! nc ,fallback ,backslash #f))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string~backslash esc fallback hex-x hex-u hex-U nil oct)
  `(cond ((char=? nc #\x) (box-ac! nc ,fallback ,hex-x #f))
         ((char=? nc #\u) (box-ac! nc ,fallback ,hex-u #f))
         ((char=? nc #\u) (box-ac! nc ,fallback ,hex-U #f))
         ((char=? nc #\newline)
          (set-kind! (unbox ac-box) ,esc)
          (box-ac! nc ,fallback ,nil #f))
         ((octal-char? nc)
          (set-kind! (unbox ac-box) ,esc)
          (box-ac! nc ,esc ,oct #f))
         ((memc nc '(#\a #\b #\f #\n #\r #\t #\v #\" #\\ #\| #\? #\space))
          (set-kind! (unbox ac-box) ,esc)
          (box-ac! nc ,esc ,fallback #f))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string~hex-Uu backslash delim dist esc fallback hex-Uu)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((hexadecimal-char? nc)
          (if (> ,dist (distance-until adorned ,backslash))
              (box-ac! nc ,fallback ,hex-Uu #f)
              (begin (box-ac! nc ,esc ,fallback #f)
                     (revise-until! adorned ,esc ,(+ dist 1)))))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string-hex-x backslash delim esc fallback hex-x)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((char=? nc #\;)
          (box-ac! nc ,esc ,fallback #f)
          (revise-until! adorned ,esc ,backslash))
         ((hexadecimal-char? nc)
          (box-ac! nc ,fallback ,hex-x #f))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string-nil backslash delim esc fallback esc-nil)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((char=? nc #\\)
          (box-ac! nc ,fallback ,backslash #f))
         ((memc nc '(#\space #\tab))
          (box-ac! nc ,fallback ,esc-nil #f))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string-octal-second backslash delim esc fallback third)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((char=? nc #\\)
          (box-ac! nc ,fallback ,backslash #f))
         ((octal-char? nc)
          (if (memc (get-char (unbox ac-box)) '(#\0 #\1 #\2 #\3))
              (box-ac! nc ,esc ,third #f)
              (box-ac! nc ,esc ,fallback #f)))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define-macro (%ident/string-octal-third backslash delim esc fallback)
  `(cond ((char=? nc ,delim)
          (box-ac! nc ,fallback #f #f)
          (simple-peer! (unbox ac-box) adorned index))
         ((char=? nc #\\)
          (box-ac! nc ,fallback ,backslash #f))
         ((octal-char? nc)
          (box-ac! nc ,esc ,fallback #f))
         (else (box-ac! nc ,fallback ,fallback #f))))

(define (simple-peer! ac ac-list ac-index)
  (let* ((peer-ac (find-nearest-peer ac-list))
         (peer-index (get-peer peer-ac)))
    (set-mesg! ac ac-index)
    (set-peer! ac peer-index)
    (set-mesg! peer-ac peer-index)
    (set-peer! peer-ac ac-index)))

(define (adorn! chars #!optional (so-far '()))
  (define ac-box (box (if (null? so-far)
                          (adorn-char #f #f #f #f)
                          (car so-far))))
  (define (box-ac! char kind mesg peer?)
    (set-box! ac-box (adorn-char char kind mesg peer?)))
  (define (no-context-values char index)
    (lambda ()
      (case char
        (( #\) ) (values char 'default #f #f))
        (( #\\ ) (values char 'infix #f #f))
        (( #\; ) (values char 'linec 'linec #f))
        (( #\( ) (values char 'list 'list index))
        (( #\# ) (values char 'default 'octothorpe #f))
        (( #\| ) (values char 'ident 'ident index))
        (( #\" ) (values char 'string 'string index))
        (( #\' ) (values char 'quote #f #f))
        (( #\` ) (values char 'quasiquote #f #f))
        (( #\, ) (values char 'unquote #f #f))
        (( #\space #\newline #\tab ) (values char 'whitespace #f #f))
        (else (values char 'default #f #f)))))
  (define (box-no-context! char index)
    (call-with-values (no-context-values char index) box-ac!))
  (define (box-invalid! char)
    (box-ac! char 'invalid 'invalid #f))
  (let loop ((adorned so-far)
             (unadorned (if (string? chars) (string->list chars) chars))
             (index (length so-far)))
    (if (null? unadorned)
        adorned
        (let ((nc (car unadorned))
              (pm (get-mesg (unbox ac-box))))
          (case pm
            (( bind invalid )
             (cond ((delimiter? nc) (box-no-context! nc index))
                   (else (box-ac! nc pm pm #f))))
            (( char false true directive sharp datum-reference serial )
             (unless (delimiter? nc)
               (box-invalid! nc)
               (revise-until! adorned 'default 'octothorpe)))
            (( ~char-first )
             (cond ((maybe-named-char? nc adorned)
                    (box-ac! nc 'char-body '~char-second #f))
                   (else (box-ac! nc 'char-body 'char #f)
                         (revise-until! adorned 'default 'octothorpe))))
            (( ~char-second )
             (when (maybe-named-char? nc adorned)
               (box-ac! nc 'default '~char-third #f))
             (revise-until! adorned 'default 'octothorpe))
            (( ~char-third )
             (cond ((is-short-named-char? nc adorned)
                    (box-ac! nc 'char-body 'short-named-char #f)
                    (revise-until! adorned 'char 'octothorpe)
                    (revise-until! adorned 'char-body '~char-second))
                   ((maybe-named-char? nc adorned)
                    (box-ac! nc 'default '~named-char #f))
                   ((not (delimiter? nc))
                    (box-invalid! nc))))
            (( ~named-char )
             (cond ((is-named-char? nc adorned)
                    (box-ac! nc 'char-body 'char #f)
                    (revise-until! adorned 'char 'octothorpe)
                    (revise-until! adorned 'char-body '~char-second))
                   ((maybe-named-char? nc adorned)
                    (box-ac! nc 'default '~named-char #f))
                   ((not (delimiter? nc))
                    (box-invalid! nc))))
            (( ~directive/sharp )
             (cond ((memc nc '(#\f #\n))
                    (box-ac! nc 'default '~directive #f))
                   ((memc nc '(#\e #\k #\o #\r #\v))
                    (box-ac! nc 'default '~sharp #f))
                   ((not (delimiter? nc))
                    (box-invalid! nc))))
            (( ~false/fvector )
             (cond ((char=? nc #\a)
                    (revise-until! adorned 'default 'octothorpe)
                    (box-ac! nc 'default '~false #f))
                   ((memc nc '(#\3 #\6))
                    (revise-until! adorned 'default 'octothorpe)
                    (box-ac! nc 'default '~fvector #f))
                   ((not (delimiter? nc))
                    (box-invalid! nc))))
            (( ~fvector )
             (cond ((is-fvector? nc adorned)
                    (box-ac! nc 'fvector 'fvector index)
                    (revise-until! adorned 'fvector 'octothorpe))
                   ((maybe-fvector? nc adorned)
                    (box-ac! nc 'default '~fvector #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~svector )
             (cond ((is-svector? nc adorned)
                    (box-ac! nc 'svector 'svector index)
                    (revise-until! adorned 'svector 'octothorpe))
                   ((maybe-svector? nc adorned)
                    (box-ac! nc 'default '~svector #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~uvector )
             (cond ((is-uvector? nc adorned)
                    (box-ac! nc 'uvector 'uvector index)
                    (revise-until! adorned 'uvector 'octothorpe))
                   ((maybe-uvector? nc adorned)
                    (box-ac! nc 'default '~uvector #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~directive )
             (cond ((is-directive? nc adorned)
                    (box-ac! nc 'directive 'directive #f)
                    (revise-until! adorned 'directive 'octothorpe))
                   ((maybe-directive? nc adorned)
                    (box-ac! nc 'default '~directive #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~false )
             (cond ((is-false? nc adorned)
                    (box-ac! nc 'false 'false #f)
                    (revise-until! adorned 'false 'octothorpe))
                   ((maybe-false? nc adorned) (box-ac! nc 'default '~false #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~sharp )
             (cond ((is-sharp? nc adorned)
                    (box-ac! nc 'sharp 'sharp #f)
                    (revise-until! adorned 'sharp 'octothorpe))
                   ((maybe-sharp? nc adorned) (box-ac! nc 'default '~sharp #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( ~true )
             (cond ((is-true? nc adorned)
                    (box-ac! nc 'true 'true #f)
                    (revise-until! adorned 'true 'octothorpe))
                   ((maybe-true? nc adorned) (box-ac! nc 'default '~true #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( abbrev )
             (when (char=? nc #\@) (box-ac! nc 'abbrev #f #f)))
            (( short-named-char )
             (cond ((is-named-char? nc adorned)
                    (box-ac! nc 'char-body 'char #f))
                   ((maybe-named-char? nc adorned)
                    (box-ac! nc 'default '~named-char #f)
                    (revise-until! adorned 'default 'octothorpe))
                   ((not (delimiter? nc))
                    (box-invalid! nc))))
            (( hs-begin )
             (cond ((char=? nc #\<) (box-ac! nc 'hs-begin 'hs-key #f))
                   ((not (delimiter? nc)) (box-invalid! nc))))
            (( hs-key )
             (cond ((char=? nc #\newline) (box-ac! nc 'hs-key 'hs-body index))
                   (else (box-ac! nc 'hs-key 'hs-key #f))))
            (( hs-body )
             (cond ((char=? nc #\newline) (box-ac! nc 'hs-body '~hs-end #f))
                   (else (box-ac! nc 'hs-body 'hs-body #f))))
            (( ~hs-end )
             (let ((maybe-end (append (chars-until adorned #\newline)
                                      (list nc)))
                   (hs-ending (cons #\newline (get-hs-key adorned))))
               (cond ((backmatch? hs-ending maybe-end)
                      (let* ((distance (- (length hs-ending) 1))
                             (end-index (- index distance))
                             (hs-peer! (lambda (ac)
                                         (simple-peer! ac adorned end-index))))
                        (revise-until! adorned 'hs-key distance hs-peer!))
                      (box-no-context! nc index))
                     ((could-match? hs-ending maybe-end)
                      (box-ac! nc 'hs-body '~hs-end #f))
                     ((char=? nc #\newline)
                      (box-ac! nc 'hs-body '~hs-end #f))
                     (else (box-ac! nc 'hs-body 'hs-body #f)))))
            (( linec )
             (cond ((char=? nc #\newline) (box-no-context! nc index))
                   (else (box-ac! nc 'linec 'linec #f))))
            (( string )
             (%ident/string 'string-backslash #\" 'string))
            (( ident )
             (%ident/string 'ident-backslash #\| 'ident))
            (( string-backslash )
             (%ident/string~backslash 'string-escape 'string 'string-hex-x
                                      'string-hex-u 'string-hex-U
                                      'string-escape-nil 'string-octal-second))
            (( ident-backslash )
             (%ident/string~backslash 'ident-escape 'ident 'ident-hex-x
                                      'ident-hex-u 'ident-hex-U
                                      'ident-escape-nil 'ident-octal-second))
            (( string-hex-u )
             (%ident/string~hex-Uu 'string-backslash #\" 4 'string-escape
                                   'string 'string-hex-u))
            (( ident-hex-u )
             (%ident/string~hex-Uu 'ident-backslash #\| 4 'ident-escape
                                   'ident 'ident-hex-u))
            (( string-hex-U )
             (%ident/string~hex-Uu 'string-backslash #\" 8 'string-escape
                                   'string 'string-hex-U))
            (( ident-hex-U )
             (%ident/ident~hex-Uu 'ident-backslash #\| 8 'ident-escape
                                  'ident 'ident-hex-U))
            (( string-hex-x )
             (%ident/string-hex-x 'string-backslash #\" 'string-escape
                                  'string 'string-hex-x))
            (( ident-hex-x )
             (%ident/string-hex-x 'ident-backslash #\| 'ident-escape
                                  'ident 'ident-hex-x))
            (( string-nil )
             (%ident/string-nil 'string-backslash #\" 'string-escape 'string
                                'string-nil))
            (( ident-nil )
             (%ident/string-nil 'ident-backslash #\| 'ident-escape 'ident
                                'ident-nil))
            (( string-octal-second )
             (%ident/string-octal-second 'string-backslash #\" 'string-escape
                                         'string 'string-octal-third))
            (( ident-octal-second )
             (%ident/string-octal-second 'ident-backslash #\| 'ident-escape
                                         'ident 'ident-octal-third))
            (( string-octal-third )
             (%ident/string-octal-third 'string-backslash #\" 'string-esc
                                        'string))
            (( ident-octal-third )
             (%ident/string-octal-third 'ident-backslash #\| 'ident-esc
                                        'ident))
            (( octothorpe )
             (case nc
               (( #\! )
                (cond ((= index 1)
                       (set-kind! (unbox ac-box) 'shebang)
                       (box-ac! nc 'shebang 'shebang #f))
                      (else (box-ac! nc 'default '~directive/sharp #f))))
               (( #\\ )
                (set-kind! (unbox ac-box) 'char)
                (box-ac! nc 'char '~char-first #f))
               (( #\f )
                (set-kind! (unbox ac-box) 'false)
                (box-ac! nc 'false '~false/fvector #f))
               (( #\s )
                (box-ac! nc 'default '~svector #f))
               (( #\t )
                (set-kind! (unbox ac-box) 'true)
                (box-ac! nc 'true '~true #f))
               (( #\u )
                (box-ac! nc 'default '~uvector #f))
               (( #\; )
                (set-kind! (unbox ac-box) 'datumc)
                (box-ac! nc 'datumc '~datumc #f))
               (( #\& )
                (set-kind! (unbox ac-box) 'box)
                (box-ac! nc 'box #f #f))
               (( #\( )
                (set-kind! (unbox ac-box) 'vector)
                (box-ac! nc 'vector index #f))
               (( #\< )
                (set-kind! (unbox ac-box) 'hs-begin)
                (box-ac! nc 'hs-begin 'hs-begin #f))
               (( #\| )
                (let ((previous-ac (unbox ac-box)))
                  (set-kind! previous-ac 'nestc)
                  (set-mesg! previous-ac 1)
                  (set-peer! previous-ac (- index 1))
                  (box-ac! nc 'nsetc 'nestc-begin #f)))
               (( #\# #\b #\e #\i #\o #\x )
                (box-ac! nc 'default #f #f))
               (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9 )
                (box-ac! nc 'default '~label/reference #f))
               (else (box-invalid! nc))))
            (( shebang )
             (cond ((char=? nc #\newline) (box-ac! nc 'whitespace #f #f))
                   (else (box-ac! nc 'shebang 'shebang #f))))
            (else (box-no-context! nc index)))
          (when (and (not (null? adorned)) (eq? (unbox ac-box) (car adorned)))
            (box-no-context! nc index))
          (loop (cons (unbox ac-box) adorned) (cdr unadorned) (+ index 1))))))

          ;;   (( keyword )
          ;;    (if (char=? nc #\:)
          ;;        (set-kind+mesg! nac 'keyword)
          ;;        (unless (delimiter? nc)
          ;;          (set-refresh! nac #f)
          ;;          (revise! adorned 'keyword 'default))))
          ;;   (( ~label/reference )
          ;;    (cond ((decimal-char? nc)
          ;;           (set-mesg! nac '~label/reference)
          ;;           (set-refresh! nac #f))
          ;;          ((char=? nc #\=)
          ;;           (set-kind+mesg! nac 'datum-label)
          ;;           (set-refresh! nac #f)
          ;;           (revise! adorned 'default 'datum-label octo-start?))
          ;;          ((char=? nc #\#)
          ;;           (set-kind+mesg! nac 'datum-reference)
          ;;           (set-refresh! nac #f)
          ;;           (revise! adorned 'default 'datum-reference octo-start?))
          ;;          ((delimiter? nc)
          ;;           (revise! adorned 'default 'serial octo-start?))
          ;;          (else (set-kind+mesg! nac 'invalid)
          ;;                (set-refresh! nac #f))))
          ;;   (( datum-label )
          ;;    (when (memc nc '( #\) #\space #\newline #\tab #\; ))
          ;;      (revise! adorned 'default 'invalid octo-start?)))
          ;;   (( runtime-syntax )
          ;;    (unless (delimiter? nc)
          ;;      (if (full-match? 'runtime-syntax (cons nac adorned))
          ;;          (set-kind+mesg! nac 'runtime-syntax)
          ;;          (revise! adorned 'runtime-syntax 'default))))
          ;;   (( string-octal ident-octal )
          ;;    (set-refresh! nac #f)
          ;;    (let-values (((delim fallback)
          ;;                  (case pm
          ;;                    (( string-octal ) (values #\" 'string))
          ;;                    (( ident-octal ) (values #\| 'identifier)))))
          ;;      (case nc
          ;;        (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 )
          ;;         (let ((distance (distance-to-previous #\\ adorned)))
          ;;           (cond ((> 3 distance) (set-kind+mesg! nac pm))
          ;;                 ((and (= 3 distance)
          ;;                       (memc (get-char (cadr adorned))
          ;;                             '(#\0 #\1 #\2 #\3)))
          ;;                  (set-kind+mesg! nac pm fallback))
          ;;                 (else (set-kind! nac fallback)
          ;;                       (set-mesg! nac fallback)))))
          ;;        (else (if (char=? nc delim)
          ;;                  (begin (set-kind! nac fallback)
          ;;                         (symmetric-peer! delim nac adorned index))
          ;;                  (set-kind+mesg! nac fallback))))))
          ;;   (( ~datumc )
          ;;    (let ((pc (get-char pac)))
          ;;      (if (char=? pc #\))
          ;;          (if (number? ppr)
          ;;              (set-mesg! pac (- index 1))
          ;;              (set-refresh! nac #f))
          ;;          (let ((ppac (cadr adorned)))
          ;;            (let ((mesg (get-mesg ppac))
          ;;                  (peer (get-peer ppac)))
          ;;              (set-refresh! nac #f)
          ;;              (if (and (number? peer)
          ;;                       (memq mesg '(datumc-simple datumc#)))
          ;;                  (set-mesg! ppac (- index 2))
          ;;                  (set-refresh! nac #f)))))
          ;;      (cond ((char=? nc #\()
          ;;             (set-kind+mesg! nac 'datumc 'datumc-compound)
          ;;             (set-peer! nac index))
          ;;            ((char=? nc #\#)
          ;;             (set-kind+mesg! nac 'datumc 'datumc#))
          ;;            ((char=? nc #\;)
          ;;             (set-kind+mesg! nac 'linec))
          ;;            ((memc nc '(#\space #\newline #\tab #\' #\` #\,))
          ;;             (set-kind+mesg! nac 'datumc '~datumc))
          ;;            ((and (char=? nc #\@) (char=? pc #\,))
          ;;             (set-kind+mesg! nac 'datumc '~datumc))
          ;;            (else (set-kind+mesg! nac 'datumc 'datumc-simple)))))
          ;;   (( datumc# )
          ;;    (cond ((char=? nc #\!)
          ;;           (set-kind+mesg! nac 'datumc '~datumc-directive)
          ;;           (set-refresh! nac #f))
          ;;          ((char=? nc #\;)
          ;;           (set-kind+mesg! nac 'datumc '~datumc)
          ;;           (set-refresh! nac #f)
          ;;           (set-peer! nac index))
          ;;          ((char=? nc #\|)
          ;;           (set-kind+mesg! nac 'nestc 'nestc-begin)
          ;;           (set-refresh! nac #f)
          ;;           (set-kind+mesg! pac 'nestc 1)
          ;;           (set-peer! pac (- index 1)))
          ;;          ((char=? nc #\()
          ;;           (set-kind+mesg! nac 'datumc 'datumc-compound)
          ;;           (set-refresh! nac #f))
          ;;          ((char=? nc #\\)
          ;;           (set-kind+mesg! nac 'datumc 'datumc-simple)
          ;;           (set-refresh! nac #f))
          ;;          ((delimiter? nc)
          ;;           (let ((r (datum-comment-peer! pac adorned (- index 1))))
          ;;             (if (unused-datum-comment? r)
          ;;                 (begin (set-kind+mesg! nac 'datumc '~datumc)
          ;;                        (set-refresh! nac #f))
          ;;                 (set-mesg! pac (- index 1)))))
          ;;          (else (set-kind+mesg! nac 'datumc 'datumc-simple)
          ;;                (set-refresh! nac #f))))
          ;;   (( datumc-simple )
          ;;    (if (delimiter? nc)
          ;;        (let ((rest (datum-comment-peer! pac adorned (- index 1))))
          ;;          (if (unused-datum-comment? rest)
          ;;              (begin (set-kind+mesg! nac 'datumc '~datumc)
          ;;                     (set-refresh! nac #f))
          ;;              (set-mesg! pac (- index 1))))
          ;;        (begin (set-kind+mesg! nac 'datumc 'datumc-simple)
          ;;               (set-refresh! nac #f))))
          ;;   (( datumc-compound )
          ;;    (set-kind! nac 'datumc)
          ;;    (set-refresh! nac #f)
          ;;    (cond ((char=? nc #\()
          ;;           (set-mesg! nac 'datumc-compound)
          ;;           (set-peer! nac index))
          ;;          ((char=? nc #\))
          ;;           (let ((up-predicate? (lambda (ac)
          ;;                                  (and (eq? (get-kind ac) 'datumc)
          ;;                                       (char=? (get-char ac) #\()))))
          ;;             (let loop ((enclosing-list (up-list adorned up-predicate?)))
          ;;               (if (and (not (null? enclosing-list))
          ;;                        (looking-at 'datumc (cdr enclosing-list)))
          ;;                   (let ((rest (datum-comment-peer! nac adorned index)))
          ;;                     (set-mesg! nac (if (unused-datum-comment? rest)
          ;;                                        '~datumc
          ;;                                        index)))
          ;;                   (when (not (null? enclosing-list))
          ;;                     (let* ((list-start (car enclosing-list))
          ;;                            (mesg (get-mesg list-start)))
          ;;                       (if (number? mesg)
          ;;                           (loop (up-list enclosing-list up-predicate?))
          ;;                           (let ((peer (get-peer list-start)))
          ;;                             (set-mesg! nac 'datumc-compound)
          ;;                             (set-peer! nac peer)
          ;;                             (set-mesg! list-start peer)
          ;;                             (set-peer! list-start index)))))))))
          ;;          (else (set-mesg! nac 'datumc-compound))))
          ;;   (( ~datumc-directive )
          ;;    (let ((all (cons nac adorned)))
          ;;      (let-values (((kind ep?)
          ;;                    (get-matching-kind+ep? 'datumc-directive)))
          ;;        (cond ((full-match? 'directive all kind: kind ep?: ep?)
          ;;               (set-kind+mesg! nac 'datumc 'datumc-directive))
          ;;              ((partial-match? 'directive all kind: kind ep?: ep?)
          ;;               (set-kind+mesg! nac 'datumc '~datumc-directive))
          ;;              ((delimiter? nc)
          ;;               (when (unused-datum-comment?
          ;;                      (datum-comment-peer! pac adorned (- index 1)))
          ;;                 (set-kind+mesg! nac 'datumc '~datumc)
          ;;                 (set-refresh! nac #f)))
          ;;              (else (set-kind+mesg! nac 'datumc 'datumc-simple))))))
          ;;   (( datumc-directive )
          ;;    (set-refresh! nac #f)
          ;;    (if (delimiter? nc)
          ;;        (set-kind+mesg! nac 'datumc '~datumc)
          ;;        (set-kind+mesg! nac 'datumc '~datumc-simple)))
          ;;   (( nestc nestc-begin )
          ;;    (set-refresh! nac #f)
          ;;    (set-kind+mesg! nac 'nestc (cond ((char=? nc #\#) 'nestc#)
          ;;                                     ((char=? nc #\|) 'nestcbar)
          ;;                                     (else 'nestc))))
          ;;   (( nestc- nestc+ )
          ;;    (if (positive? (get+set-nested-comment-info! pm adorned))
          ;;        (begin (set-refresh! nac #f)
          ;;               (set-kind+mesg! nac
          ;;                               'nestc
          ;;                               (cond ((char=? nc #\#) 'nestc#)
          ;;                                     ((char=? nc #\|) 'nestcbar)
          ;;                                     (else 'nestc))))
          ;;        (begin (nested-comment-peer! pac adorned (- index 1))
          ;;               (when (unused-datum-comment? adorned)
          ;;                 (set-kind+mesg! nac 'datumc '~datumc)
          ;;                 (set-refresh! nac #f)))))
          ;;   (( nestcbar )
          ;;    (set-refresh! nac #f)
          ;;    (set-kind+mesg! nac 'nestc (cond ((char=? nc #\#) 'nestc-)
          ;;                                     ((char=? nc #\|) 'nestcbar)
          ;;                                     (else 'nestc))))
          ;;   (( nestc# )
          ;;    (set-refresh! nac #f)
          ;;    (set-kind+mesg! nac 'nestc (cond ((char=? nc #\|) 'nestc+)
          ;;                                     ((char=? nc #\#) 'nestc#)
          ;;                                     (else 'nestc))))
          ;; (when (refresh? nac)
          ;;   (case nc
          ;;     (( #\) ) (compound-peer! nac #\( adorned index))
          ;;     (( #\\ ) (set-kind! nac 'infix))
          ;;     (( #\; ) (set-kind+mesg! nac 'linec))
          ;;     (( #\( ) (set-kind+mesg! nac 'list index))
          ;;     (( #\# ) (set-mesg! nac 'octothorpe))
          ;;     (( #\. ) (when (and pac (delimiter? (get-char pac)))
          ;;                (set-kind! nac 'dot)))
          ;;     (( #\| )
          ;;      (set-kind+mesg! nac 'identifier)
          ;;      (set-peer! nac index))
          ;;     (( #\" )
          ;;      (set-kind+mesg! nac 'string)
          ;;      (set-peer! nac index))
          ;;     (( #\' #\` #\, )
          ;;      (set-kind+mesg! nac 'abbrev))
          ;;     (( #\space #\newline #\tab )
          ;;      (set-kind+mesg! nac 'whitespace #f)))
          ;;   (let ((full (cons nac adorned)))
          ;;     (cond ((and (looking-at 'runtime-syntax full)
          ;;                 (not (quoted? full)))
          ;;            (set-kind+mesg! nac 'runtime-syntax)
          ;;            (revise! adorned 'default 'runtime-syntax))
          ;;           ((looking-at 'keyword full)
          ;;            (set-kind+mesg! nac 'keyword)
          ;;            (revise! adorned 'default 'keyword))
          ;;           ((start-of-bind? full)
          ;;            (set-kind+mesg! nac 'bind)))))
          ;; (loop (cons nac adorned) (cdr unadorned) (+ index 1)))))))
