;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define-record-type achar
  (adorn-char c k m p r t)
  adorned-char?
  (c get-char set-char!)
  (k get-kind set-kind!)
  (m get-mesg set-mesg!)
  (p get-peer set-peer!)
  (r refresh? set-refresh!)
  (t tentative? set-tent!))
;==============================================================================
(define (string-list->char-lists sl)
  (map (lambda (s) (reverse (string->list s))) sl))

(define directive-char-lists
  (string-list->char-lists '("#!fold-case" "#!no-fold-case")))

(define sharp-object-char-lists
  (string-list->char-lists '("#!eof" "#!key" "#!optional" "#!rest" "#!void")))

(define short-named-char-char-lists
  (string-list->char-lists '("#\\esc" "#\\nul")))

(define long-named-char-char-lists
  (string-list->char-lists '("#\\null" "#\\alarm" "#\\backspace" "#\\tab"
                             "#\\space" "#\\newline" "#\\return" "#\\delete"
                             "#\\escape" "#\\page" "#\\vtab" "#\\linefeed")))

(define named-char-firsts
  (map (lambda (cl) (caddr (reverse cl))) long-named-char-char-lists))

(define runtime-syntax-char-lists
  (string-list->char-lists
   '("and" "begin" "c-declare" "c-define" "c-define-type" "c-initialize"
     "c-lambda" "case" "case-lambda" "cond" "cond-expand" "declare" "define"
     "define-library" "define-macro" "define-record-type" "define-structure"
     "define-syntax" "define-type" "define-type-of-thread" "define-values"
     "delay" "delay-force" "do" "else" "future" "guard" "if" "import" "include"
     "include-ci" "lambda" "let" "let*" "let*-values" "let-values" "letrec"
     "letrec*" "letrec*-values" "letrec-values" "namespace" "or" "parameterize"
     "quasiquote" "quote" "r7rs-guard" "receive" "set!" "syntax-error"
     "syntax-rules" "this-source-file" "unless" "when")))

(define let-char-lists
  (string-list->char-lists '("let" "let*" "letrec" "letrec*")))

(define define-char-lists
  (string-list->char-lists '("define" "define-values")))

(define binding-syntax-char-lists
  (string-list->char-lists
   '("define" "define-values" "define-syntax" "let" "let*" "letrec" "letrec*"
     "let-values" "let*-values" "let-syntax" "letrec-syntax")))
;==============================================================================
(define (memc c l) (member c l char=?))

(define (delimiter? c)
  (memc c '( #\) #\( #\space #\newline #\tab #\" #\; #\| #\\ )))

(define set-kind+mesg!
  (case-lambda
    ((ac km) (set-kind! ac km) (set-mesg! ac km))
    ((ac k m) (set-kind! ac k) (set-mesg! ac m))))

(define revise!
  (case-lambda
    ((ac-list new-kind)
     (let loop ((rest ac-list))
       (when (not (null? rest))
         (let ((ac (car rest)))
           (when (tentative? ac)
             (set-kind! ac new-kind)
             (loop (cdr rest)))))))
    ((ac-list new-kind old-kind limit)
     (let loop ((rest ac-list) (count 0))
       (when (and (not (null? rest)) (> limit count))
         (let ((ac (car rest)))
           (when (eq? old-kind (get-kind ac))
             (set-kind! ac new-kind)
             (loop (cdr rest) (+ count 1)))))))))
;==============================================================================
(define (get+set-nested-comment-info! symbol ac-list)
  (define (get-nested-comment-info)
    (let loop ((rest (cdr ac-list)))
      (unless (null? rest)
        (if (memq (get-mesg (car rest)) '(nestc- nestc+ nestc-begin))
            (let ((previous-cache-ac (cadr rest))
                  (operator (if (symbol=? symbol 'nestc-) - +)))
              (values (operator (get-mesg previous-cache-ac) 1)
                      (get-peer previous-cache-ac)))
            (loop (cdr rest))))))
  (call-with-values get-nested-comment-info
    (lambda (nesting peer)
      (let ((cache-ac (cadr ac-list)))
        (set-mesg! cache-ac nesting) (set-peer! cache-ac peer) nesting))))

(define (here-string-key ac-list)
  (let loop ((key '()) (rest ac-list))
    (if (null? rest)
        #f
        (let* ((ac (car rest))
               (kind (get-kind ac)))
          (cond ((eq? kind 'hs-key) (loop (cons (get-char ac) key) (cdr rest)))
                ((eq? kind 'hs-begin) key)
                (else (loop key (cdr rest))))))))

(define (unused-datum-comment? ac-list)
  (let loop ((rest ac-list))
    (if (null? rest)
        #f
        (let ((ac (car rest)))
          (if (and (number? (get-peer ac)) (eq? (get-mesg ac) '~datumc))
              #t
              (if (memq (get-kind ac) '(datumc linec nestc))
                  (loop (cdr rest))
                  #f))))))
;==============================================================================
(define (datum-comment-peer! ending-ac ac-list index)
  (let loop ((rest ac-list))
    (and (not (null? rest))
         (let* ((ac (car rest))
                (peer (get-peer ac)))
           (if (and peer (eq? (get-mesg ac) '~datumc))
               (begin (set-mesg! ac peer)
                      (set-peer! ac index)
                      (set-peer! ending-ac peer)
                      rest)
               (loop (cdr rest)))))))

(define (nested-comment-peer! ending-ac ac-list index)
  (let loop ((rest ac-list))
    (unless (null? rest)
      (if (eq? (get-mesg (car rest)) 'nestc-begin)
          (let* ((ac (cadr rest)) (ac-index (get-peer ac)))
            (set-mesg! ac ac-index)
            (set-peer! ac index)
            (set-mesg! ending-ac index)
            (set-peer! ending-ac ac-index))
          (loop (cdr rest))))))

(define (compound-peer! nac peer-char ac-list index)
  (let ((kind->empty (lambda (sym) ; also used to filter for valid datum kinds
                       (let ((e (assq sym '((list      . empty-list)
                                            (vector    . empty-vector)
                                            (u8vector  . empty-u8vector)
                                            (u16vector . empty-u16vector)
                                            (u32vector . empty-u32vector)
                                            (u64vector . empty-u64vector)
                                            (s8vector  . empty-s8vector)
                                            (s16vector . empty-s16vector)
                                            (s32vector . empty-s32vector)
                                            (s64vector . empty-s64vector)
                                            (f32vector . empty-f32vector)
                                            (f64vector . empty-f64vector)))))
                         (and e (cdr e)))))
        (kind->length (lambda (kind) (case kind
                                       (( list )              1)
                                       (( vector )            2)
                                       (( u8vector s8vector ) 4)
                                       (else                  5))))
        (empty? #t))
    (let loop ((rest ac-list))
      (if (null? rest)
          (set-kind! nac 'invalid)
          (let* ((ac (car rest))
                 (kind (get-kind ac))
                 (ek (kind->empty kind)))
            (let ((peer (get-peer ac))
                  (char (get-char ac)))
              (if (and ek (not peer) (char=? peer-char char))
                  (begin (set-peer! ac index)
                         (set-peer! nac (get-mesg ac))
                         (if empty?
                             (begin (set-kind! nac ek)
                                    (revise! rest ek kind (kind->length kind)))
                             (set-kind! nac kind))
                         (set-mesg! nac index))
                  (begin (unless (memq kind '(whitespace nestc))
                           (set! empty? #f))
                         (loop (cdr rest))))))))))

(define (symmetric-peer! peer-char nac ac-list index)
  (let loop ((rest ac-list))
    (unless (null? rest)
      (let ((ac (car rest)))
        (if (char=? peer-char (get-char ac))
            (let ((peer (get-peer ac)))
              (if (number? peer)
                  (begin (set-mesg! nac index)
                         (set-peer! nac peer)
                         (set-mesg! ac peer)
                         (set-peer! ac index))
                  (loop (cdr rest))))
            (loop (cdr rest)))))))
;==============================================================================
(define (distance-to-previous char ac-list)
  (let loop ((rest ac-list) (count 1))
    (if (null? rest)
        0
        (if (char=? (get-char (car rest)) char)
            count
            (loop (cdr rest) (+ count 1))))))

(define (operator-position? ac-list)
  (let loop ((rest ac-list))
    (if (null? rest)
        #f
        (let ((ac (car rest)))
          (cond ((char=? (get-char ac) #\() (eq? (get-kind ac) 'list))
                ((memq (get-kind ac) '(whitespace nestc)) (loop (cdr rest)))
                (else #f))))))

(define (looking-at? char-list ac-list delimiting-mesg)
  (let loop ((cl char-list) (al ac-list))
    (cond ((null? cl) #t)
          ((null? al) #f)
          ((null? (cdr cl)) (let ((cal (car al)))
                              (if (and (if delimiting-mesg
                                           (eq? delimiting-mesg (get-mesg cal))
                                           #t)
                                       (char=? (car cl) (get-char cal)))
                                  (loop (cdr cl) (cdr al))
                                  #f)))
          ((char=? (car cl) (get-char (car al))) (loop (cdr cl) (cdr al)))
          (else #f))))

(define (looking-at-one-of? char-lists ac-list delimiting-message)
  (let loop ((rest char-lists))
    (cond ((null? rest) #f)
          ((looking-at? (car rest) ac-list delimiting-message) #t)
          (else (loop (cdr rest))))))

(define (could-match? char-list ac-list delimiting-message)
  (let loop ((cl char-list))
    (cond ((null? cl) #f)
          ((looking-at? cl ac-list delimiting-message) #t)
          (else (loop (cdr cl))))))

(define (could-match-one-of? char-lists ac-list delimiting-message)
  (let loop ((rest char-lists))
    (cond ((null? rest) #f)
          ((could-match? (car rest) ac-list delimiting-message) #t)
          (else (loop (cdr rest))))))
;==============================================================================
(define (could-match-directive? ac-list)
  (could-match-one-of? directive-char-lists ac-list 'octothorpe))
(define (looking-at-directive? ac-list)
  (looking-at-one-of? directive-char-lists ac-list 'octothorpe))

(define (could-match-datum-comment-directive? ac-list)
  (could-match-one-of? directive-char-lists ac-list 'datumc#))
(define (looking-at-datum-comment-directive? ac-list)
  (looking-at-one-of? directive-char-lists ac-list 'datumc#))

(define (could-match-sharp-object? ac-list)
  (could-match-one-of? sharp-object-char-lists ac-list 'octothorpe))
(define (looking-at-sharp-object? ac-list)
  (looking-at-one-of? sharp-object-char-lists ac-list 'octothorpe))

(define (could-match-named-char? ac-list)
  (could-match-one-of? long-named-char-char-lists ac-list 'octothorpe))
(define (looking-at-short-named-char? ac-list)
  (looking-at-one-of? short-named-char-char-lists ac-list 'octothorpe))
(define (looking-at-long-named-char? ac-list)
  (looking-at-one-of? long-named-char-char-lists ac-list 'octothorpe))
;==============================================================================
(define (start-of-let-binding? ac-list)
  (and (not (null? ac-list)) (eq? (get-kind (car ac-list)) 'default)
       (operator-position? (cdr ac-list))
       (looking-at-let? (enclosing-list-start (current-list-start ac-list)))))

(define (start-of-var-define-or-named-let? ac-list)
  (and (not (null? ac-list))
       (not (memc (get-char (car ac-list)) '(#\( #\# #\space #\newline #\tab)))
       (let loop ((rest (cdr ac-list)))
         (if (null? rest)
             #f
             (let* ((ac (car rest))
                    (kind (get-kind ac)))
               (cond ((eq? kind 'whitespace)
                      (loop (cdr rest)))
                     ((eq? kind 'runtime-syntax)
                      (looking-at-one-of? '((#\e #\n #\i #\f #\e #\d #\()
                                            (#\t #\e #\l #\()) rest #f))
                     (else #f)))))))

(define (looking-at-let? ac-list)
  (and (not (null? ac-list)) (char=? (get-char (car ac-list)) #\()
       (let loop ((rest (cdr ac-list)))
         (if (null? rest)
             #f
             (let* ((ac (car rest))
                    (kind (get-kind ac)))
               (cond ((eq? kind 'whitespace)
                      (loop (cdr rest)))
                     ((eq? kind 'runtime-syntax)
                      (looking-at-one-of? let-char-lists rest #f))
                     (else #f)))))))

(define (current-list-start ac-list)
  (if (null? ac-list)
      '()
      (let ((ac (car ac-list)))
        (if (and (eq? (get-kind ac) 'list)
                 (char=? (get-char ac) #\()
                 (not (get-peer ac)))
            ac-list
            (current-list-start (cdr ac-list))))))

(define (enclosing-list-start ac-list)
  (if (null? ac-list)
      '()
      (let loop ((rest (cdr ac-list)))
        (if (null? rest)
            '()
            (let ((ac (car rest)))
              (if (and (eq? (get-kind ac) 'list)
                       (char=? (get-char ac) #\()
                       (not (get-peer ac)))
                  rest
                  (loop (cdr rest))))))))

(define (start-of-binding-lval? ac-list)
  (or (and (eq? (get-kind (car ac-list)) 'default)
           (not (null? (cdr ac-list)))
           (memq (get-kind (cadr ac-list)) '(list whitespace))
           (let loop ((rest (cddr ac-list)))
             (if (null? rest)
                 #f
                 (let* ((ac (car rest))
                        (kind (get-kind ac)))
                   (cond ((eq? kind 'runtime-syntax)
                          (looking-at-binding-syntax? rest))
                         ((memq kind '(list whitespace))
                          (loop (cdr rest)))
                         (else #f))))))
      (looking-at-let? (before-previous-unmatched-list
                        (before-previous-unmatched-list ac-list)))))

(define (looking-at-keyword? ac-list)
  (if (null? ac-list)
      #f
      (let ((first (car ac-list)))
        (if (and (eq? (get-kind first) 'default) (char=? (get-char first) #\:))
            (let ((rest (cdr ac-list)))
              (not (or (null? rest) (delimiter? (get-char (car rest))))))
            #f))))

(define (looking-at-syntax? ac-list char-lists expected-kind)
  (let ((plausible-kinds (cons expected-kind '(list datumc linec nestc))))
    (letrec ((start-of-syntax
              (lambda (cl al)
                (cond ((null? cl) al)
                      ((null? al) #f)
                      (else (let ((cal (car al)))
                              (and (memq (get-kind cal) plausible-kinds)
                                   (char=? (car cl) (get-char cal))
                                   (start-of-syntax (cdr cl) (cdr al)))))))))
      (let loop ((rest char-lists))
        (if (null? rest)
            #f
            (let ((start (start-of-syntax (car rest) ac-list)))
              (if start
                  (operator-position? start)
                  (loop (cdr rest)))))))))

(define (looking-at-binding-syntax? ac-list)
  (looking-at-syntax? ac-list binding-syntax-char-lists 'runtime-syntax))

(define (looking-at-runtime-syntax? ac-list)
  (looking-at-syntax? ac-list runtime-syntax-char-lists 'default))
;==============================================================================
(define (adorn! char-list #!optional so-far)
  (let-values (((so-far unadorned index pac pc pk pm ppr pt)
                (if so-far
                    (let ((pac (car so-far)))
                      (values so-far char-list (length so-far) pac
                              (get-char pac) (get-kind pac) (get-mesg pac)
                              (get-peer pac) (tentative? pac)))
                    (values '() char-list 0 #f #f #f '~shebang #f #f))))
    (let loop ((adorned so-far) (unadorned char-list) (index index) (pac pac)
               (pc pc) (pk pk) (pm pm) (ppr ppr) (pt pt))
      (if (null? unadorned)
          adorned
          (let* ((nc (car unadorned))
                 (nac (adorn-char nc 'default #f #f #t #t)))
            (case pm
              (( ~shebang )
               (cond ((and (char=? nc #\#) (not pc))
                      (set-kind+mesg! nac '~shebang)
                      (set-refresh! nac #f))
                     ((and (char=? nc #\!) (char=? pc #\#))
                      (set-kind+mesg! nac 'shebang)
                      (set-refresh! nac #f)
                      (set-kind! pac 'shebang))))
              (( shebang )
               (unless (char=? nc #\newline)
                 (set-kind+mesg! nac 'shebang)
                 (set-refresh! nac #f)))
              (( bind invalid )
               (unless (delimiter? nc)
                 (set-kind+mesg! nac pm)
                 (set-refresh! nac #f)))
              (( abbrev )
               (when (char=? nc #\@)
                 (set-kind! nac 'abbrev)
                 (set-refresh! nac #f)))
              (( ~char )
               (set-kind! nac 'char)
               (set-refresh! nac #f)
               (if (memc nc named-char-firsts)
                   (set-mesg! nac '~named-char)
                   (set-mesg! nac 'char)))
              (( hs-begin )
               (set-refresh! nac #f)
               (if (char=? nc #\<)
                   (set-kind+mesg! nac 'hs-begin 'hs-key)
                   (begin (set-kind+mesg! nac 'invalid)
                          (revise! adorned 'invalid))))
              (( hs-key )
               (set-refresh! nac #f)
               (if (char=? nc #\newline)
                   (begin (set-kind+mesg! nac 'hs-key 'here-string)
                          (set-peer! nac index))
                   (set-kind+mesg! nac 'hs-key)))
              (( here-string )
               (set-refresh! nac #f)
               (if (char=? nc #\newline)
                   (begin (set-kind+mesg! nac 'here-string '~hs-end)
                          (set-tent! nac #f))
                   (set-kind+mesg! nac 'here-string)))
              (( ~hs-end )
               (set-refresh! nac #f)
               (let ((hs-key (here-string-key adorned)))
                 (let ((hs-key-first (car hs-key))
                       (hs-key-reversed (reverse hs-key))
                       (all (cons nac adorned)))
                   (cond ((looking-at? hs-key-reversed all '~hs-end)
                          (set-kind! nac 'hs-end)
                          (symmetric-peer! #\newline nac adorned index)
                          (revise! adorned 'hs-end))
                         ((could-match? hs-key-reversed all '~hs-end)
                          (set-kind+mesg! nac 'here-string '~hs-end))
                         ((and (char=? pc #\newline) (char=? nc hs-key-first))
                          (set-kind+mesg! nac 'here-string '~hs-end))
                         ((char=? nc #\newline)
                          (set-kind+mesg! nac 'here-string '~hs-end))
                         (else (set-kind+mesg! nac 'here-string))))))
              (( ~named-char )
               (if (delimiter? nc)
                   (begin (set-kind! pac 'char)
                          (set-tent! pac #f))
                   (let ((all (cons nac adorned)))
                     (set-refresh! nac #f)
                     (if (could-match-named-char? all)
                         (cond ((looking-at-short-named-char? all)
                                (set-kind+mesg! nac 'char '~named-char)
                                (revise! adorned 'char))
                               ((looking-at-long-named-char? all)
                                (set-kind+mesg! nac 'char 'named-char)
                                (revise! adorned 'char))
                               (else (set-mesg! nac '~named-char)
                                     (revise! adorned 'default)))
                         (begin (set-kind+mesg! nac 'invalid)
                                (revise! adorned 'default))))))
              (( char named-char )
               (if (delimiter? nc)
                   (revise! adorned 'char)
                   (begin (set-kind+mesg! nac 'invalid)
                          (set-refresh! nac #f)
                          (revise! adorned 'default))))
              (( ~directive/sharp )
               (cond ((memc nc '(#\f #\n))
                      (set-mesg! nac '~directive))
                     ((memc nc '(#\e #\k #\o #\r #\v))
                      (set-mesg! nac '~sharp))
                     (else (unless (delimiter? nc)
                             (set-kind+mesg! nac 'invalid)
                             (set-refresh! nac #f)))))
              (( ~directive )
               (unless (delimiter? nc) (set-refresh! nac #f))
               (let ((all (cons nac adorned)))
                 (if (could-match-directive? all)
                     (if (looking-at-directive? all)
                         (set-kind+mesg! nac 'directive)
                         (set-kind+mesg! nac 'directive '~directive))
                     (begin (set-kind+mesg! nac 'invalid)
                            (revise! adorned 'default)))))
              (( ~sharp )
               (unless (delimiter? nc) (set-refresh! nac #f))
               (let ((all (cons nac adorned)))
                 (if (could-match-sharp-object? all)
                     (if (looking-at-sharp-object? all)
                         (set-kind+mesg! nac 'sharp)
                         (set-kind+mesg! nac 'sharp '~sharp))
                     (begin (set-kind+mesg! nac 'invalid)
                            (revise! adorned 'default)))))
              (( directive sharp )
               (if (delimiter? nc)
                   (revise! adorned pm)
                   (begin (set-kind+mesg! nac 'invalid)
                          (set-refresh! nac #f)
                          (revise! adorned 'default))))
              (( linec )
               (if (char=? nc #\newline)
                   (when (unused-datum-comment? adorned)
                     (set-kind+mesg! nac 'datumc '~datumc)
                     (set-refresh! nac #f))
                   (begin (set-kind+mesg! nac 'linec)
                          (set-refresh! nac #f))))
              (( ~false/fvector )
               (unless (delimiter? nc)
                 (cond ((char=? nc #\a) (set-mesg! nac '~false))
                       ((memc nc '(#\3 #\6)) (set-mesg! nac '~fvector))
                       (else (set-kind+mesg! nac 'invalid)))
                 (set-refresh! nac #f)
                 (revise! adorned 'default)))
              (( ~false )
               (unless (delimiter? nc) (set-refresh! nac #f))
               (let ((all (cons nac adorned))
                     (false-char-list '(#\e #\s #\l #\a #\f #\#)))
                 (if (could-match? false-char-list all 'octothorpe)
                     (if (looking-at? false-char-list all 'octothorpe)
                         (begin (set-kind+mesg! nac 'boolean 'false)
                                (revise! adorned 'boolean))
                         (begin (set-mesg! nac '~false)
                                (revise! adorned 'default)))
                     (begin (set-kind+mesg! nac 'invalid)
                            (revise! adorned 'default)))))
              (( ~true )
               (unless (delimiter? nc)
                 (let ((all (cons nac adorned))
                       (set-refresh! nac #f)
                       (true-char-list '(#\e #\u #\r #\t #\#)))
                   (if (could-match? true-char-list all 'octothorpe)
                       (if (looking-at? true-char-list all 'octothorpe)
                           (begin (set-kind+mesg! nac 'boolean 'true)
                                  (revise! adorned 'boolean))
                           (begin (set-mesg! nac '~true)
                                  (revise! adorned 'default)))
                       (begin (set-kind+mesg! nac 'invalid)
                              (revise! adorned 'default))))))
              (( ~keyword )
               (if (delimiter? nc)
                   (revise! adorned 'keyword)
                   (begin (set-kind! nac 'default)
                          (revise! adorned 'default))))
              (( ~label/reference )
               (unless (delimiter? nc) (set-refresh! nac #f))
               (case nc
                 (( #\= )
                  (set-kind+mesg! nac 'datum-label)
                  (revise! adorned 'datum-label))
                 (( #\# )
                  (set-kind+mesg! nac 'datum-reference)
                  (set-refresh! nac #f)
                  (revise! adorned 'datum-reference))
                 (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9 )
                  (set-mesg! nac '~label/reference))
                 (else (if (delimiter? nc)
                           (begin (set-kind! pac 'serial)
                                  (revise! adorned 'serial))
                           (begin (set-kind! pac 'invalid)
                                  (revise! adorned 'invalid))))))
              (( datum-label )
               (when (memc nc '( #\) #\space #\newline #\tab #\; ))
                 (revise! adorned 'invalid)))
              (( datum-reference serial )
               (unless (delimiter? nc)
                 (set-kind+mesg! nac 'invalid)
                 (revise! adorned 'invalid)))
              (( ~runtime-syntax )
               (if (delimiter? nc)
                   (revise! adorned 'runtime-syntax)
                   (begin (set-kind! nac 'default)
                          (revise! adorned 'default))))
              (( true false )
               (if (delimiter? nc)
                   (revise! adorned 'boolean)
                   (begin (set-kind+mesg! nac 'invalid)
                          (set-refresh! nac #f)
                          (revise! adorned 'default))))
              (( string identifier )
               (set-refresh! nac #f)
               (let-values (((delim backslash)
                             (case pm
                               (( string )
                                (values #\" 'string-backslash))
                               (( identifier )
                                (values #\| 'ident-backslash)))))
                 (set-kind! nac pm)
                 (cond ((char=? nc delim)
                        (symmetric-peer! delim nac adorned index))
                       ((char=? nc #\\)
                        (set-mesg! nac backslash))
                       (else (set-mesg! nac pm)))))
              (( string-backslash ident-backslash )
               (set-refresh! nac #f)
               (let-values (((fallback octal esc esc-nothing hex-x hex-u hex-U)
                             (case pm
                               (( ident-backslash )
                                (values 'identifier 'ident-octal 'ident-escape
                                        'ident-nothing 'ident-hex-x
                                        'ident-hex-u 'ident-hex-U))
                               (( string-backslash )
                                (values 'string 'string-octal 'string-escape
                                        'string-nothing 'string-hex-x
                                        'string-hex-u 'string-hex-U)))))
                 (case nc
                   (( #\newline ) (set-kind+mesg! nac fallback esc-nothing))
                   (( #\x ) (set-kind+mesg! nac fallback hex-x))
                   (( #\u ) (set-kind+mesg! nac fallback hex-u))
                   (( #\U ) (set-kind+mesg! nac fallback hex-U))
                   (( #\a #\b #\f #\n #\r #\t #\v #\" #\\ #\| #\? #\space)
                    (set-kind! pac esc)
                    (set-kind+mesg! nac esc fallback))
                   (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 )
                    (set-kind! pac octal)
                    (set-kind+mesg! nac octal))
                   (else (set-kind+mesg! nac fallback)))))
              (( string-nothing ident-nothing )
               (set-refresh! nac #f)
               (let-values (((delim fallback)
                             (case pm
                               (( string-nothing ) (values #\" 'string))
                               (( ident-nothing ) (values #\| 'identifier)))))
                 (cond ((memc nc '(#\space #\tab))
                        (set-kind+mesg! nac fallback pm))
                       ((char=? nc delim)
                        (set-kind! nac fallback)
                        (symmetric-peer! delim nac adorned index))
                       (else (set-kind+mesg! nac fallback)))))
              (( string-octal ident-octal )
               (set-refresh! nac #f)
               (let-values (((delim fallback)
                             (case pm
                               (( string-octal ) (values #\" 'string))
                               (( ident-octal ) (values #\| 'identifier)))))
                 (case nc
                   (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 )
                    (let ((distance (distance-to-previous #\\ adorned)))
                      (cond ((> 3 distance) (set-kind+mesg! nac pm))
                            ((and (= 3 distance)
                                  (memc (get-char (cadr adorned))
                                        '(#\0 #\1 #\2 #\3)))
                             (set-kind+mesg! nac pm fallback))
                            (else (set-kind! nac fallback)
                                  (set-mesg! nac fallback)))))
                   (else (if (char=? nc delim)
                             (begin (set-kind! nac fallback)
                                    (symmetric-peer! delim nac adorned index))
                             (set-kind+mesg! nac fallback))))))
              (( string-hex-x ident-hex-x )
               (set-refresh! nac #f)
               (let-values (((delim fallback)
                             (case pm
                               (( string-hex-x ) (values #\" 'string))
                               (( ident-hex-x )  (values #\| 'identifier)))))
                 (case nc
                   (( #\; )
                    (let ((distance (distance-to-previous #\\ adorned)))
                      (set-kind+mesg! nac pm fallback)
                      (revise! adorned pm fallback distance)))
                   (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9
                      #\a #\b #\c #\d #\e #\f #\A #\B #\C #\D #\E #\F )
                    (set-kind+mesg! nac fallback pm))
                   (else (if (char=? nc delim)
                             (begin (set-kind! nac fallback)
                                    (symmetric-peer! delim nac adorned index))
                             (set-kind+mesg! nac fallback))))))
              (( string-hex-u string-hex-U ident-hex-u ident-hex-U )
               (set-refresh! nac #f)
               (let-values (((target delim fallback)
                             (case pm
                               (( string-hex-u ) (values 4 #\" 'string))
                               (( string-hex-U ) (values 8 #\" 'string))
                               (( ident-hex-u )  (values 4 #\| 'identifier))
                               (( ident-hex-U )  (values 8 #\| 'identifier)))))
                 (case nc
                   (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9
                      #\a #\b #\c #\d #\e #\f #\A #\B #\C #\D #\E #\F )
                    (let ((distance (distance-to-previous #\\ adorned)))
                      (if (>= target distance)
                          (set-kind+mesg! nac fallback pm)
                          (if (< target distance)
                              (begin (set-kind+mesg! nac pm fallback)
                                     (revise! adorned pm fallback distance))
                              (set-kind+mesg! nac fallback)))))
                   (else (if (char=? nc delim)
                             (begin (set-kind! nac fallback)
                                    (symmetric-peer! delim nac adorned index))
                             (set-kind+mesg! nac fallback))))))
              (( ~datumc )
               (if (char=? pc #\))
                   (if (number? ppr)
                       (set-mesg! pac (- index 1))
                       (set-refresh! nac #f))
                   (let ((ppac (cadr adorned)))
                     (let ((mesg (get-mesg ppac))
                           (peer (get-peer ppac)))
                     (set-refresh! nac #f)
                     (if (and (number? peer)
                              (memq mesg '(datumc-simple datumc#)))
                         (set-mesg! ppac (- index 2))
                         (set-refresh! nac #f)))))
               (cond ((char=? nc #\()
                      (set-kind+mesg! nac 'datumc 'datumc-compound))
                     ((char=? nc #\#)
                      (set-kind+mesg! nac 'datumc 'datumc#))
                     ((char=? nc #\;)
                      (set-kind+mesg! nac 'linec))
                     ((memc nc '(#\space #\newline #\tab #\' #\` #\,))
                      (set-kind+mesg! nac 'datumc '~datumc))
                     ((and (char=? nc #\@) (char=? pc #\,))
                      (set-kind+mesg! nac 'datumc '~datumc))
                     (else (set-kind+mesg! nac 'datumc 'datumc-simple))))
              (( datumc# )
               (cond ((char=? nc #\!)
                      (set-kind+mesg! nac 'datumc '~datumc-directive)
                      (set-refresh! nac #f))
                     ((char=? nc #\;)
                      (set-kind+mesg! nac 'datumc '~datumc)
                      (set-refresh! nac #f)
                      (set-peer! nac index))
                     ((char=? nc #\|)
                      (set-kind+mesg! nac 'nestc 'nestc-begin)
                      (set-refresh! nac #f)
                      (set-tent! nac #f)
                      (set-kind+mesg! pac 'nestc 1)
                      (set-peer! pac (- index 1)))
                     ((char=? nc #\()
                      (set-kind+mesg! nac 'datumc 'datumc-compound)
                      (set-refresh! nac #f))
                     ((delimiter? nc)
                      (let ((r (datum-comment-peer! pac adorned (- index 1))))
                        (if (unused-datum-comment? r)
                            (begin (set-kind+mesg! nac 'datumc '~datumc)
                                   (set-refresh! nac #f))
                            (set-mesg! pac (- index 1)))))
                     (else (set-kind+mesg! nac 'datumc 'datumc-simple)
                           (set-refresh! nac #f))))
              (( datumc-simple )
               (if (delimiter? nc)
                   (let ((rest (datum-comment-peer! pac adorned (- index 1))))
                     (if (unused-datum-comment? rest)
                         (begin (set-kind+mesg! nac 'datumc '~datumc)
                                (set-refresh! nac #f))
                         (set-mesg! pac (- index 1))))
                   (begin (set-kind+mesg! nac 'datumc 'datumc-simple)
                          (set-refresh! nac #f))))
              (( datumc-compound )
               (set-kind! nac 'datumc)
               (set-refresh! nac #f)
               (if (char=? nc #\))
                   (let ((rest (datum-comment-peer! nac adorned index)))
                     (set-mesg! nac (if (unused-datum-comment? rest)
                                        '~datumc
                                        index)))
                   (set-mesg! nac 'datumc-compound)))
              (( ~datumc-directive )
               (let ((all (cons nac adorned)))
                 (if (could-match-datum-comment-directive? all)
                     (if (looking-at-datum-comment-directive? all)
                         (set-kind+mesg! nac 'datumc 'datumc-directive)
                         (set-kind+mesg! nac 'datumc '~datumc-directive))
                     (if (delimiter? nc)
                         (let ((r
                                (datum-comment-peer! pac adorned (- index 1))))
                           (when (unused-datum-comment? r)
                             (set-kind+mesg! nac 'datumc '~datumc)
                             (set-refresh! nac #f)))
                         (set-kind+mesg! nac 'datumc 'datumc-simple)))))
              (( datumc-directive )
               (set-refresh! nac #f)
               (if (delimiter? nc)
                   (set-kind+mesg! nac 'datumc '~datumc)
                   (set-kind+mesg! nac 'datumc '~datumc-simple)))
              (( nestc nestc-begin )
               (set-refresh! nac #f)
               (set-kind+mesg! nac 'nestc (cond ((char=? nc #\#) 'nestc#)
                                                ((char=? nc #\|) 'nestcbar)
                                                (else 'nestc))))
              (( nestc- nestc+ )
               (if (positive? (get+set-nested-comment-info! pm adorned))
                   (begin (set-refresh! nac #f)
                          (set-kind+mesg! nac
                                          'nestc
                                          (cond ((char=? nc #\#) 'nestc#)
                                                ((char=? nc #\|) 'nestcbar)
                                                (else 'nestc))))
                   (begin (nested-comment-peer! pac adorned (- index 1))
                          (when (unused-datum-comment? adorned)
                            (set-kind+mesg! nac 'datumc '~datumc)
                            (set-refresh! nac #f)))))
              (( nestcbar )
               (set-refresh! nac #f)
               (set-kind+mesg! nac 'nestc (cond ((char=? nc #\#) 'nestc-)
                                                ((char=? nc #\|) 'nestcbar)
                                                (else 'nestc))))
              (( nestc# )
               (set-refresh! nac #f)
               (set-kind+mesg! nac 'nestc (cond ((char=? nc #\|) 'nestc+)
                                                ((char=? nc #\#) 'nestc#)
                                                (else 'nestc))))
              (( ~uvector ~svector ~fvector )
               (unless (and (not (char=? #\( nc)) (delimiter? nc))
                 (set-refresh! nac #f))
               (let* ((all (cons nac adorned))
                      (la? (lambda (l) (looking-at? l all 'octothorpe)))
                      (cm? (lambda (l) (could-match? l all 'octothorpe)))
                      (handle-match (lambda (s)
                                      (set-kind+mesg! nac s index)
                                      (set-tent! nac #f)
                                      (revise! adorned s)))
                      (handle-tentative (lambda (s ~s)
                                          (set-mesg! nac ~s)
                                          (revise! adorned 'default))))
                 (cond ((la?     '(#\( #\8 #\u #\#)) (handle-match  'u8vector))
                       ((la? '(#\( #\6 #\1 #\u #\#)) (handle-match 'u16vector))
                       ((la? '(#\( #\2 #\3 #\u #\#)) (handle-match 'u32vector))
                       ((la? '(#\( #\4 #\6 #\u #\#)) (handle-match 'u64vector))
                       ((la?     '(#\( #\8 #\s #\#)) (handle-match  's8vector))
                       ((la? '(#\( #\6 #\1 #\s #\#)) (handle-match 's16vector))
                       ((la? '(#\( #\2 #\3 #\s #\#)) (handle-match 's32vector))
                       ((la? '(#\( #\4 #\6 #\s #\#)) (handle-match 's64vector))
                       ((la? '(#\( #\2 #\3 #\f #\#)) (handle-match 'f32vector))
                       ((la? '(#\( #\4 #\6 #\f #\#)) (handle-match 'f64vector))
                       ((or (cm?     '(#\( #\8 #\u #\#))
                            (cm? '(#\( #\1 #\6 #\u #\#))
                            (cm? '(#\( #\2 #\3 #\u #\#))
                            (cm? '(#\( #\4 #\6 #\u #\#)))
                        (handle-tentative 'uvector '~uvector))
                       ((or (cm?     '(#\( #\8 #\s #\#))
                            (cm? '(#\( #\1 #\6 #\s #\#))
                            (cm? '(#\( #\2 #\3 #\s #\#))
                            (cm? '(#\( #\4 #\6 #\s #\#)))
                        (handle-tentative 'svector '~svector))
                       ((or (cm? '(#\( #\2 #\3 #\f #\#))
                            (cm? '(#\( #\4 #\6 #\f #\#)))
                        (handle-tentative 'fvector '~fvector))
                       (else (set-kind+mesg! nac 'invalid)
                             (revise! adorned 'default)))))
              (( octothorpe )
               (case nc
                 (( #\! )
                  (set-mesg! nac '~directive/sharp)
                  (set-refresh! nac #f))
                 (( #\\ )
                  (set-kind+mesg! nac 'char '~char)
                  (set-refresh! nac #f)
                  (set-kind! pac 'char))
                 (( #\f )
                  (set-kind+mesg! nac 'boolean '~false/fvector)
                  (set-kind! pac 'boolean))
                 (( #\s )
                  (set-mesg! nac '~svector))
                 (( #\t )
                  (set-kind+mesg! nac 'boolean '~true)
                  (set-kind! pac 'boolean)
                  (set-refresh! nac #f))
                 (( #\u )
                  (set-mesg! nac '~uvector))
                 (( #\; )
                  (set-kind+mesg! nac 'datumc '~datumc)
                  (set-peer! nac index)
                  (set-refresh! nac #f)
                  (set-kind! pac 'datumc))
                 (( #\& )
                  (set-kind! nac 'box)
                  (set-kind! pac 'box))
                 (( #\( )
                  (set-kind+mesg! nac 'vector index)
                  (set-refresh! nac #f)
                  (set-tent! nac #f)
                  (set-kind! pac 'vector))
                 (( #\< )
                  (set-kind+mesg! nac 'hs-begin)
                  (set-refresh! nac #f)
                  (set-kind! pac 'hs-begin))
                 (( #\| )
                  (set-kind+mesg! nac 'nestc 'nestc-begin)
                  (set-refresh! nac #f)
                  (set-kind+mesg! pac 'nestc 1)
                  (set-mesg! pac 1)
                  (set-peer! pac (- index 1)))
                 (( #\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7 #\8 #\9 )
                  (set-mesg! nac '~label/reference))
                 (( #\b #\e #\i #\o #\x )
                  (set-kind! nac 'default)
                  (set-kind! pac 'default)
                  (set-tent! nac #f))
                 (else (set-kind+mesg! nac 'invalid)))))
            (when (refresh? nac)
              (case nc
                (( #\' #\` #\, )
                 (set-kind+mesg! nac 'abbrev)
                 (set-tent! nac #f))
                (( #\) )
                 (compound-peer! nac #\( adorned index)
                 (set-tent! nac #f))
                (( #\. )
                 (set-kind! nac 'dot)
                 (set-tent! nac #f))
                (( #\| )
                 (set-kind+mesg! nac 'identifier)
                 (set-tent! nac #f))
                (( #\\ )
                 (set-kind! nac 'infix)
                 (set-tent! nac #f))
                (( #\; )
                 (set-kind+mesg! nac 'linec)
                 (set-tent! nac #f))
                (( #\( )
                 (set-kind+mesg! nac 'list index)
                 (set-tent! nac #f))
                (( #\# )
                 (set-mesg! nac 'octothorpe))
                (( #\" )
                 (set-kind+mesg! nac 'string)
                 (set-peer! nac index)
                 (set-tent! nac #f))
                (( #\space #\newline #\tab )
                 (set-kind! nac 'whitespace)
                 (set-tent! nac #f)))
              (let ((full (cons nac adorned)))
                (cond ((start-of-var-define-or-named-let? full)
                       (set-kind+mesg! nac 'bind))
                      ((start-of-let-binding? full)
                       (set-kind+mesg! nac 'bind))
                      ((looking-at-keyword? full)
                       (set-kind+mesg! nac 'keyword '~keyword)
                       (revise! adorned 'keyword))
                      ((looking-at-runtime-syntax? full)
                       (set-kind+mesg! nac 'runtime-syntax '~runtime-syntax)
                       (revise! adorned 'runtime-syntax)))))
            (loop (cons nac adorned) (cdr unadorned) (+ index 1) nac nc
                  (get-kind nac) (get-mesg nac) (get-peer nac)
                  (tentative? nac)))))))
