#!/usr/bin/env gsi-script

(load "adorn/adorn")

(define (file->char-list file)
  (call-with-input-file file
    (lambda (p) (read-all p read-char))))

(define (main . args)
  (let* ((txi (car args)) (char-list (file->char-list txi)))
    (display/watch-for-lisp char-list)))

(define lisp-begin (string->list "\n@lisp\n"))
(define lisp-end (string->list "\n@end lisp\n"))
(define lisp-end-length (length lisp-end))

(define (display/watch-for-lisp chars)
  (let ((initial-buffer (if (and (not (null? chars)) (char=? (car chars) #\@))
                            '(#\newline)
                            '())))
    (let loop ((rest chars) (buffer initial-buffer))
      (unless (null? rest)
        (let ((nc (car rest)))
          (cond ((null? buffer)
                 (display nc)
                 (loop (cdr rest) (if (char=? nc #\newline)
                                      (cons nc buffer)
                                      '())))
                ((adorn#matches? lisp-begin (reverse buffer))
                 (let ((lisp/rest (collect-lisp/rest rest)))
                   (write-lisp (reverse (car lisp/rest)))
                   (display/watch-for-lisp (cadr lisp/rest))))
                ((adorn#could-match? lisp-begin (reverse buffer))
                 (display nc)
                 (loop (cdr rest) (cons nc buffer)))
                (else (display nc)
                      (loop (cdr rest) '()))))))))

(define (collect-lisp/rest char-list)
  (let ((initial-buffer (if (char=? (car char-list) #\@) '(#\newline) '())))
    (let loop ((lisp '()) (rest char-list) (buffer initial-buffer))
      (if (null? rest)
          (list lisp '())
          (let ((nc (car rest)))
            (cond ((null? buffer)
                   (loop (cons nc lisp) (cdr rest) (if (char=? nc #\newline)
                                                       (cons nc buffer)
                                                       '())))
                  ((adorn#matches? lisp-end (reverse buffer))
                   (list (list-tail lisp lisp-end-length)
                         (append lisp-end rest)))
                  ((adorn#could-match? lisp-end (reverse buffer))
                   (loop (cons nc lisp) (cdr rest) (cons nc buffer)))
                  (else (loop (cons nc lisp) (cdr rest) '()))))))))

(define (basename path-string)
  (let loop ((new '()) (old (reverse (string->list path-string))))
    (if (null? old)
        (list->string new)
        (let ((next (car old)))
          (if (char=? next #\/)
              (list->string new)
              (loop (cons next new) (cdr old)))))))

(define (whitespace-char? c) (member c '(#\space #\newline #\tab) char=?))

(define (strip-leading-whitespace char-list)
  (cond ((null? char-list) char-list)
        ((whitespace-char? (car char-list)) (strip-whitespace (cdr char-list)))
        (else char-list)))

(define (strip-trailing-whitespace char-list)
  (reverse (strip-leading-whitespace (reverse char-list))))

(define (strip-whitespace char-list)
  (strip-leading-whitespace (strip-trailing-whitespace char-list)))

(define expression/expectation/trailer
  (let ((tail-matches?
         (lambda (goal)
           (let ((goal-length (string-length goal))
                 (goal-exploded (string->list goal)))
             (lambda (actual)
               (let ((actual-length (length actual)))
                 (and (>= actual-length goal-length)
                      (let* ((tail-length (- actual-length goal-length))
                             (tail (list-tail actual tail-length)))
                        (adorn#matches? goal-exploded tail)))))))))
    (let ((list-head (lambda (l n) (reverse (list-tail (reverse l) n))))
          (exception-macro? (tail-matches? "@exception{"))
          (exception-length (string-length "@exception{"))
          (ok-macro? (tail-matches? "@ok{"))
          (ok-length (string-length "@ok{"))
          (problem-macro? (tail-matches? "@problem{"))
          (problem-length (string-length "@problem{")))
      (let ((get-expression
             (lambda (char-list length)
               (strip-trailing-whitespace (list-head char-list length))))
            (get-expectation
             (lambda (char-list)
               (let loop ((rest char-list) (expectation '()))
                 (cond ((null? rest) expectation)
                       (else (let ((next (car rest)))
                               (cond ((char=? next #\}) ; use @backslashchar{}
                                      (reverse (cons #\} expectation)))
                                     (else (loop (cdr rest)
                                                 (cons next
                                                       expectation))))))))))
            (get-trailer
             (lambda (char-list)
               (let loop ((rest char-list) (trailer '()))
                 (cond ((null? rest) trailer)
                       (else (let ((next (car rest)))
                               (cond ((whitespace-char? next)
                                      (loop (cdr rest) (cons next trailer)))
                                     (else (reverse trailer))))))))))
        (let ((get-e/e/t
               (lambda (char-list chars e+e macro-length)
                 (let* ((expression (get-expression e+e macro-length))
                        (expr-len (length expression))
                        (expectation (get-expectation (list-tail char-list
                                                                 expr-len)))
                        (expect-len (length expectation))
                        (trailer (get-trailer (list-tail char-list
                                                         (+ expr-len
                                                            expect-len)))))
                   (list expression expectation trailer)))))
          (lambda (char-list)
            (let loop ((chars char-list) (e+e '()))
              (cond ((null? chars)
                     (list char-list '() '()))
                    ((ok-macro? e+e)
                     (get-e/e/t char-list chars e+e ok-length))
                    ((exception-macro? e+e)
                     (get-e/e/t char-list chars e+e exception-length))
                    ((problem-macro? e+e)
                     (get-e/e/t char-list chars e+e problem-length))
                    (else (loop (cdr chars)
                                (append e+e (list (car chars)))))))))))))

(define (write-lisp char-list)
  (unless (null? char-list)
    (let ((e/e/t (expression/expectation/trailer char-list)))
      (let ((expression (car e/e/t))
            (expectation (cadr e/e/t))
            (trailer (caddr e/e/t)))
        (let ((total-length (length (append expression expectation trailer))))
          (for-each write-char expression)
          (for-each write-char (append expectation trailer))
          (write-lisp (list-tail char-list total-length)))))))

;; (define html-safe
;;   (append '(#\space #\newline)
;;           (char-set->list (char-set-intersection char-set:ascii
;;                                                  char-set:letter+digit))))

;; (define (char->html-maybe-& c)
;;   (if (member c html-safe char=?)
;;       (list c)
;;       (append '(#\& #\#)
;;               (string->list (number->string (char->integer c)))
;;               '(#\;))))

;; (define (write-char-list char-list)
;;   (for-each write-char char-list))

;; (define (write-ac-list ac-list)
;;   (let ((nil-spans '(default whitespace)))
;;     (let ((open-span (lambda (kind)
;;                        (unless (memq kind nil-spans)
;;                          (write-string (string-append "</span><span class=\"";;
;;                                                       (symbol->string kind)
;;                                                       "\">")))))
;;           (close-span (lambda (kind)
;;                         (unless (memq kind nil-spans)
;;                           (write-string "</span>")))))
;;       (let loop ((pk 'default) (rest ac-list))
;;         (if (null? rest)
;;             (close-span pk)
;;             (let ((ac (car rest)))
;;               (let ((char (adorn#get-char ac)) (kind (adorn#get-kind ac)))
;;                 (if (eq? kind pk)
;;                     (begin (write-char-list (char->html-maybe-& char))
;;                            (loop kind (cdr rest)))
;;                     (begin (close-span pk)
;;                            (open-span kind)
;;                            (write-char-list (char->html-maybe-& char))
;;                            (loop kind (cdr rest)))))))))))
