#!/usr/bin/env gsi-script

(load "adorn/adorn")

(define (file->char-list file)
  (call-with-input-file file
    (lambda (p) (read-all p read-char))))

(define (main . args)
  (let* ((txi (car args)) (char-list (file->char-list txi)))
    (display/watch-for-lisp! char-list)))

(define lisp-begin (string->list "\n@lisp\n"))
(define lisp-end (string->list "\n@end lisp\n"))
(define lisp-end-length (length lisp-end))

(define (display/watch-for-lisp! chars)
  (let ((initial-buffer (if (and (not (null? chars)) (char=? (car chars) #\@))
                            '(#\newline)
                            '())))
    (let loop ((rest chars) (buffer initial-buffer))
      (unless (null? rest)
        (let ((nc (car rest)))
          (cond ((null? buffer)
                 (display nc)
                 (loop (cdr rest) (if (char=? nc #\newline)
                                      (cons nc buffer)
                                      '())))
                ((adorn#matches? lisp-begin (reverse buffer))
                 (let ((lisp/rest (collect-lisp/rest rest)))
                   ;; (pp (car lisp/rest))
                   (display/watch-for-lisp! (cadr lisp/rest))))
                ((adorn#could-match? lisp-begin (reverse buffer))
                 (display nc)
                 (loop (cdr rest) (cons nc buffer)))
                (else (display nc)
                      (loop (cdr rest) '()))))))))

(define (collect-lisp/rest char-list)
  (let ((initial-buffer (if (char=? (car char-list) #\@) '(#\newline) '())))
    (let loop ((lisp '()) (rest char-list) (buffer initial-buffer))
      (if (null? rest)
          (list lisp '())
          (let ((nc (car rest)))
            (cond ((null? buffer)
                   (loop (cons nc lisp) (cdr rest) (if (char=? nc #\newline)
                                                       (cons nc buffer)
                                                       '())))
                  ((adorn#matches? lisp-end (reverse buffer))
                   (list (list-tail lisp lisp-end-length)
                         (append (cdr lisp-end) rest)))
                  ((adorn#could-match? lisp-end (reverse buffer))
                   (loop (cons nc lisp) (cdr rest) (cons nc buffer)))
                  (else (loop (cons nc lisp) (cdr rest) '()))))))))

(define (basename path-string)
  (let loop ((new '()) (old (reverse (string->list path-string))))
    (if (null? old)
        (list->string new)
        (let ((next (car old)))
          (if (char=? next #\/)
              (list->string new)
              (loop (cons next new) (cdr old)))))))

;; (define html-safe
;;   (append '(#\space #\newline)
;;           (char-set->list (char-set-intersection char-set:ascii
;;                                                  char-set:letter+digit))))

;; (define (char->html-maybe-& c)
;;   (if (member c html-safe char=?)
;;       (list c)
;;       (append '(#\& #\#)
;;               (string->list (number->string (char->integer c)))
;;               '(#\;))))

;; (define (write-char-list char-list)
;;   (for-each write-char char-list))

;; (define (write-ac-list ac-list)
;;   (let ((nil-spans '(default whitespace)))
;;     (let ((open-span (lambda (kind)
;;                        (unless (memq kind nil-spans)
;;                          (write-string (string-append "</span><span class=\"";;
;;                                                       (symbol->string kind)
;;                                                       "\">")))))
;;           (close-span (lambda (kind)
;;                         (unless (memq kind nil-spans)
;;                           (write-string "</span>")))))
;;       (let loop ((pk 'default) (rest ac-list))
;;         (if (null? rest)
;;             (close-span pk)
;;             (let ((ac (car rest)))
;;               (let ((char (adorn#get-char ac)) (kind (adorn#get-kind ac)))
;;                 (if (eq? kind pk)
;;                     (begin (write-char-list (char->html-maybe-& char))
;;                            (loop kind (cdr rest)))
;;                     (begin (close-span pk)
;;                            (open-span kind)
;;                            (write-char-list (char->html-maybe-& char))
;;                            (loop kind (cdr rest)))))))))))
