#!/usr/bin/env gsi-script
;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(load "adorn/adorn")
(load "write-macros+vars.scm")

(define (main . args)
  (write-annotated-texinfo (file->char-list (car args))))

(define (file->char-list file)
  (call-with-input-file file
    (lambda (p) (read-all p read-char))))

(define (write-chars char-list) (for-each write-char char-list))

(define (whitespace-char? c) (member c '(#\space #\newline #\tab) char=?))

(define (full-match? charsA charsB)
  (or (and (null? charsA) (null? charsB))
      (and (not (null? charsA))
           (not (null? charsB))
           (char=? (car charsA) (car charsB))
           (head-match? (cdr charsA) (cdr charsB)))))

(define (head-match? goal actual)
  (or (null? goal)
      (and (not (null? actual))
           (char=? (car goal) (car actual))
           (head-match? (cdr goal) (cdr actual)))))

(define (head-match-one-of goals actual)
  (and (not (null? goals))
       (let ((goal (car goals)))
         (if (head-match? goal actual)
             goal
             (head-match-one-of (cdr goals) actual)))))

(define |else | (string->list "else "))

(define (head-match-else-syntax? chars)
  (head-match? |else | chars))

(define head-match-rt-syntax
  (let ((syntax+spaces (map (lambda (l) (append l '(#\space)))
                            adorn#runtime-syntax)))
    (lambda (chars)
      (cond ((head-match-else-syntax? chars) |else |)
            (else (head-match-one-of syntax+spaces chars))))))

(define (looking-forward-to? goal actual)
  (and (not (null? actual))
       (or (head-match? goal actual)
           (and (whitespace-char? (car actual))
                (looking-forward-to? goal (cdr actual))))))

(define (looking-forward-to-one-of? goals actual)
  (and (not (null? goals))
       (or (looking-forward-to? (car goals) actual)
           (looking-forward-to-one-of? (cdr goals) actual))))

(define write-annotated-texinfo
  (let ((pre-lisp/rest
         (let* ((start-lisp (string->list "@lisp\n"))
                (start-length (length start-lisp)))
           (lambda (char-list)
             (let loop ((rest char-list) (pre-lisp '()))
               (cond ((null? rest) (list (reverse pre-lisp) rest))
                     ((and (head-match? start-lisp rest)
                           (or (null? pre-lisp) (char=? (car pre-lisp)
                                                        #\newline)))
                      (list (append (reverse pre-lisp) start-lisp)
                            (list-tail rest start-length)))
                     (else (loop (cdr rest) (cons (car rest) pre-lisp))))))))
        (lisp-body/rest
         (let ((end-lisp (string->list "\n@end lisp\n")))
           (lambda (char-list)
             (let loop ((rest char-list) (lisp '()))
               (if (head-match? end-lisp rest)
                   (list (reverse lisp) rest)
                   (loop (cdr rest) (cons (car rest) lisp))))))))
    (lambda (char-list)
      (unless (null? char-list)
        (let ((pl/r (pre-lisp/rest char-list)))
          (let ((pre-lisp (car pl/r)) (rest (cadr pl/r)))
            (write-pre-lisp pre-lisp)
            (unless (null? rest)
              (let ((lb/r (lisp-body/rest rest)))
                (let ((lisp-body (car lb/r)) (rest (cadr lb/r)))
                  (write-lisp lisp-body)
                  (write-annotated-texinfo rest))))))))))

(define (hex->char chars)
  (integer->char (string->number (list->string chars) 16)))

(define (collect-hex chars)
  (let loop ((rest (list-tail chars 3)) (chars '()))
    (let ((char (car rest)))
      (if (char=? char #\})
          (reverse chars)
          (loop (cdr rest) (cons char chars))))))

(define write-grammar
  (let ((aux-opening (string->list "@aux{"))
        (compound-opening (string->list "@compound{"))
        (syntax-opening (string->list "@syntax{")))
    (let ((rev-aux-opening (reverse aux-opening))
          (rev-compound-opening (reverse compound-opening))
          (rev-syntax-opening (reverse syntax-opening)))
      (let ((rev-compound-begin (append '(#\} #\() rev-compound-opening)))
        (letrec ((operator-position?
                  (lambda (rev-chars) ;; rev-chars ==> "reversed-chars"
                    (and (not (null? rev-chars))
                         (let ((nc (car rev-chars)))
                           (or (head-match? rev-compound-begin rev-chars)
                               (and (whitespace-char? nc)
                                    (operator-position? (cdr rev-chars)))))))))
          (lambda (chars)
            (let loop ((rest chars) (so-far '()))
              (if (null? rest)
                  (write-chars (reverse so-far))
                  (let ((nc (car rest)))
                    (cond ((member nc '(#\space #\newline #\tab #\@) char=?)
                           (loop (cdr rest) (cons nc so-far)))
                          ((member nc '(#\) #\() char=?)
                           (if (head-match? rev-compound-opening so-far)
                               (loop (cdr rest) (cons nc so-far))
                               (loop (cdr rest)
                                     (append (list #\} nc)
                                             (reverse compound-opening)
                                             so-far))))
                          ((operator-position? so-far)
                           (let ((hm (head-match-rt-syntax rest)))
                             (cond (hm (loop (list-tail rest (length hm))
                                             (append '(#\space #\})
                                                     (cdr (reverse hm))
                                                     (if (full-match?
                                                          hm |else |)
                                                         rev-aux-opening
                                                         rev-syntax-opening)
                                                     so-far)))
                                   (else (loop (cdr rest) (cons nc so-far))))))
                          ((member nc '(#\* #\+ #\|) char=?)
                           (loop (cdr rest) (append (list #\} nc #\{ #\r #\@)
                                                    so-far)))
                          (else (loop (cdr rest) (cons nc so-far)))))))))))))

(define write-pre-lisp
  (let ((aux-opening (string->list "@aux{"))
        (defparen-opening (string->list "@defparen{"))
        (hc-opening (string->list "@hc{"))
        (ht-opening (string->list "@ht{"))
        (grammar-opening (string->list "\n@example grammar\n"))
        (syntax-opening (string->list "@syntax{"))
        (atchar (string->list "@atchar{}"))
        (backslashchar (string->list "@backslashchar{}"))
        (hashchar (string->list "@hashchar{}"))
        (lbracechar (string->list "@lbracechar{}"))
        (rbracechar (string->list "@rbracechar{}"))
        (deftypefn (string->list "\n@deftypefn "))
        (deftypefnx (string->list "\n@deftypefnx "))
        (deftypeline (string->list "\n@deftypeline "))
        (grammar/rest
         (let ((end-grammar (string->list "\n@end example\n")))
           (lambda (chars)
             (let loop ((rest chars) (grammar '()))
               (if (head-match? end-grammar rest)
                   (list (reverse grammar) rest)
                   (loop (cdr rest) (cons (car rest) grammar))))))))
    (let ((atchar-length (length atchar))
          (backslashchar-length (length backslashchar))
          (hashchar-length (length hashchar))
          (bracechar-length (length lbracechar))
          (hx-opening-length (length hc-opening))
          (grammar-opening-length (length grammar-opening))
          (rev-defparen-opening (reverse defparen-opening)))
      (letrec ((operator-position?
                (let ((rev-defparen-begin (append '(#\} #\()
                                                  rev-defparen-opening)))
                  (lambda (rev-chars) ;; rev-chars ==> "reversed-chars"
                    (and (not (null? rev-chars))
                         (let ((nc (car rev-chars)))
                           (or (head-match? rev-defparen-begin rev-chars)
                               (and (whitespace-char? nc)
                                    (operator-position?
                                     (cdr rev-chars))))))))))
        (let ((lisp-expression/rest
               (lambda (chars)
                 (let loop ((rest chars) (expr '()))
                   (if (null? rest)
                       (list (reverse expr) rest)
                       (let ((nc (car rest)))
                         (cond ((char=? nc #\}) (list (reverse expr) rest))
                               ((head-match? '(#\@ #\U #\{) rest)
                                (let ((hex-chars (collect-hex rest)))
                                  (let ((skip (+ 4 (length hex-chars)))
                                        (char (hex->char hex-chars)))
                                    (loop (list-tail rest skip)
                                          (cons char expr)))))
                               ((head-match? '(#\@ #\@) rest)
                                (loop (cddr rest) (cons #\@ expr)))
                               ((head-match? '(#\@ #\{) rest)
                                (loop (cddr rest) (cons #\{ expr)))
                               ((head-match? '(#\@ #\}) rest)
                                (loop (cddr rest) (cons #\} expr)))
                               ((head-match? atchar rest)
                                (loop (list-tail rest bracechar-length)
                                      (cons #\@ expr)))
                               ((head-match? backslashchar rest)
                                (loop (list-tail rest backslashchar-length)
                                      (cons #\\ expr)))
                               ((head-match? hashchar rest)
                                (loop (list-tail rest hashchar-length)
                                      (cons #\# expr)))
                               ((head-match? lbracechar rest)
                                (loop (list-tail rest bracechar-length)
                                      (cons #\{ expr)))
                               ((head-match? rbracechar rest)
                                (loop (list-tail rest bracechar-length)
                                      (cons #\} expr)))
                               (else (loop (cdr rest) (cons nc expr)))))))))
              (def/rest
               (lambda (chars)
                 (let loop ((rest chars) (def '()))
                   (if (null? rest)
                       (list (reverse def) rest)
                       (let ((nc (car rest)))
                         (if (char=? nc #\newline)
                             (if (char=? (car def) #\@)
                                 (loop (cdr rest) (cons nc def))
                                 (list (reverse def) rest))
                             (loop (cdr rest) (cons nc def))))))))
              (write-deftypefn
               (let ((nil-arg '(#\@ #\/))
                     (write-rest
                      (lambda (chars)
                        (let loop ((rest chars))
                          (unless (null? rest)
                            (let ((nc (car rest)))
                              (cond ((member nc '(#\) #\() char=?)
                                     (write-chars defparen-opening)
                                     (write-chars (list nc #\}))
                                     (loop (cdr rest)))
                                    (else (write-char nc)
                                          (loop (cdr rest))))))))))
                 (let ((nil-arg-len (length nil-arg)))
                   (lambda (chars)
                     (write-rest chars)
                     #;(let loop ((rest chars))
                       (unless (null? rest)
                         (cond ((head-match? nil-arg rest)
                                (write-chars nil-arg)
                                (let loop ((rest (list-tail rest nil-arg-len)))
                                  (let ((hm (head-match-rt-syntax rest)))
                                    (cond (hm
                                           (write-chars (append
                                                         (if (full-match?
                                                              hm |else |)
                                                             aux-opening
                                                             syntax-opening)
                                                         (reverse
                                                          (cdr (reverse hm)))
                                                         '(#\} #\space)))
                                           (loop (list-tail rest (length hm))))
                                          (else (let ((nc (car rest)))
                                                  (if (or (char=? nc #\space)
                                                          (char=? nc #\tab))
                                                      (begin (write-char nc)
                                                             (loop (cdr rest)))
                                                      (write-rest rest))))))))
                               (else (write-char (car rest))
                                     (loop (cdr rest))))))))))
              (write-deftypeline
               (let ((rev-syntax-opening (reverse syntax-opening)))
                 (lambda (chars)
                   (let loop ((rest chars) (so-far '()))
                     (if (null? rest)
                         (write-chars (reverse so-far))
                         (let ((nc (car rest)))
                           (if (or (char=? nc #\() (char=? nc #\)))
                               (loop (cdr rest)
                                     (let loop ((opening defparen-opening)
                                                (so-far so-far))
                                       (if (null? opening)
                                           (cons #\} (cons nc so-far))
                                           (loop (cdr opening)
                                                 (cons (car opening)
                                                       so-far)))))
                               (loop (cdr rest) (cons nc so-far))))))))))
          (lambda (chars)
            (unless (null? chars)
              (cond ((head-match? grammar-opening chars)
                     (write-chars grammar-opening)
                     (let* ((trunc (list-tail chars grammar-opening-length))
                            (g/r (grammar/rest trunc)))
                       (write-grammar (car g/r))
                       (write-pre-lisp (cadr g/r))))
                    ((head-match? hc-opening chars)
                     (write-chars '(#\@ #\c #\o #\d #\e #\{))
                     (let* ((trunc (list-tail chars hx-opening-length))
                            (expr/rest (lisp-expression/rest trunc)))
                       (write-lisp (car expr/rest))
                       (write-pre-lisp (cadr expr/rest))))
                    ((head-match? ht-opening chars)
                     (write-chars '(#\@ #\t #\{))
                     (let* ((trunc (list-tail chars hx-opening-length))
                            (expr/rest (lisp-expression/rest trunc)))
                       (write-lisp (car expr/rest))
                       (write-pre-lisp (cadr expr/rest))))
                    ((head-match-one-of (list deftypefn deftypefnx) chars)
                     (write-char #\newline)
                     (let ((d/r (def/rest (cdr chars))))
                       (write-deftypefn (car d/r))
                       (write-pre-lisp (cadr d/r))))
                    ((head-match? deftypeline chars)
                     (write-char #\newline)
                     (let ((d/r (def/rest (cdr chars))))
                       (write-deftypeline (car d/r))
                       (write-pre-lisp (cadr d/r))))
                    (else (write-char (car chars))
                          (write-pre-lisp (cdr chars)))))))))))

(define write-lisp
  (let ((lisp-expression/rest/class
         (let ((andprints-opening (string->list "@andprints{"))
               (exception-opening (string->list "@exception{"))
               (lispnote-opening (string->list "@lispnote{"))
               (lispnotetext-opening (string->list "@lispnotetext{"))
               (noadorn-opening (string->list "@noadorn{"))
               (ok-opening (string->list "@ok{"))
               (output-opening (string->list "@output{"))
               (prints-opening (string->list "@prints{"))
               (problem-opening (string->list "@problem{"))
               (unspecified-opening (string->list "@unspecified{"))
               (unspecifiedtext-opening (string->list "@unspecifiedtext{"))
               (atchar (string->list "@atchar{}"))
               (lbracechar (string->list "@lbracechar{}"))
               (rbracechar (string->list "@rbracechar{}")))
           (let ((atchar-length (length atchar))
                 (bracechar-length (length lbracechar)))
             (lambda (chars)
               (let loop ((rest chars) (expr '()))
                 (cond ((null? rest) (list (reverse expr) rest 'n/a))
                       ((looking-forward-to? andprints-opening rest)
                        (list (reverse expr) rest 'and-prints))
                       ((looking-forward-to? exception-opening rest)
                        (list (reverse expr) rest 'exception))
                       ((looking-forward-to? lispnote-opening rest)
                        (list (reverse expr) rest 'lisp-note))
                       ((looking-forward-to? lispnotetext-opening rest)
                        (list (reverse expr) rest 'lisp-note))
                       ((looking-forward-to? noadorn-opening rest)
                        (list (reverse expr) rest 'no-adorn))
                       ((looking-forward-to? ok-opening rest)
                        (list (reverse expr) rest 'ok))
                       ((looking-forward-to? output-opening rest)
                        (list (reverse expr) rest 'output))
                       ((looking-forward-to? prints-opening rest)
                        (list (reverse expr) rest 'and-prints))
                       ((looking-forward-to? problem-opening rest)
                        (list (reverse expr) rest 'problem))
                       ((looking-forward-to? unspecified-opening rest)
                        (list (reverse expr) rest 'unspecified))
                       ((looking-forward-to? unspecifiedtext-opening rest)
                        (list (reverse expr) rest 'unspecified))
                       ((head-match? '(#\@ #\U #\{) rest)
                        (let ((hex-chars (collect-hex rest)))
                          (let ((skip (+ 4 (length hex-chars)))
                                (char (hex->char hex-chars)))
                            (loop (list-tail rest skip) (cons char expr)))))
                       ((head-match? '(#\@ #\@) rest)
                        (loop (cddr rest) (cons #\@ expr)))
                       ((head-match? '(#\@ #\{) rest)
                        (loop (cddr rest) (cons #\{ expr)))
                       ((head-match? '(#\@ #\}) rest)
                        (loop (cddr rest) (cons #\} expr)))
                       ((head-match? atchar rest)
                        (loop (list-tail rest atchar-length)
                              (cons #\@ expr)))
                       ((head-match? lbracechar rest)
                        (loop (list-tail rest bracechar-length)
                              (cons #\{ expr)))
                       ((head-match? rbracechar rest)
                        (loop (list-tail rest bracechar-length)
                              (cons #\} expr)))
                       (else (loop (cdr rest) (cons (car rest) expr)))))))))
        (pre-lisp-result/rest
         (lambda (chars)
           (let loop ((rest chars) (pre-result '()))
             (if (null? rest)
                 (list (reverse pre-result) rest)
                 (let ((nc (car rest)))
                   (if (whitespace-char? nc)
                       (loop (cdr rest) (cons nc pre-result))
                       (let ((extra (let loop ((rest rest) (extra '()))
                                      (if (null? rest)
                                          extra
                                          (let ((nc (car rest)))
                                            (if (char=? nc #\{)
                                                (cons nc extra)
                                                (loop (cdr rest)
                                                      (cons nc extra))))))))
                         (list (reverse (append extra pre-result))
                               (list-tail rest (length extra))))))))))
        (lisp-result/rest
         (let ((atchar (string->list "@atchar{}"))
               (lbracechar (string->list "@lbracechar{}"))
               (rbracechar (string->list "@rbracechar{}")))
           (let ((atchar-length (length atchar))
                 (bracechar-length (length lbracechar)))
             (lambda (chars)
               (let loop ((rest chars) (result '()))
                 (cond ((null? rest) (list (reverse result) rest))
                       ((head-match? '(#\@ #\U #\{) rest)
                        (let ((hex-chars (collect-hex rest)))
                          (let ((skip (+ 4 (length hex-chars)))
                                (char (hex->char hex-chars)))
                            (loop (list-tail rest skip) (cons char result)))))
                       ((head-match? '(#\@ #\@) rest)
                        (loop (cddr rest) (cons #\@ result)))
                       ((head-match? '(#\@ #\{) rest)
                        (loop (cddr rest) (cons #\{ result)))
                       ((head-match? '(#\@ #\}) rest)
                        (loop (cddr rest) (cons #\f result)))
                       ((head-match? atchar rest)
                        (loop (list-tail rest atchar-length)
                              (cons #\@ result)))
                       ((head-match? lbracechar rest)
                        (loop (list-tail rest bracechar-length)
                              (cons #\{ result)))
                       ((head-match? rbracechar rest)
                        (loop (list-tail rest bracechar-length)
                              (cons #\} result)))
                       (else (let ((nc (car rest)))
                               (if (char=? (car rest) #\})
                                   (list (reverse result) rest)
                                   (loop (cdr rest) (cons nc result)))))))))))
        (post-lisp-result/rest
         (lambda (chars)
           (let loop ((rest (cdr chars)) (post-result '(#\})))
             (if (null? rest)
                 (list (reverse post-result) rest)
                 (let ((nc (car rest)))
                   (if (whitespace-char? nc)
                       (loop (cdr rest) (cons nc post-result))
                       (list (reverse post-result) rest)))))))
        (adorn+simplify
         (lambda (chars)
           (adorn#reverse+simplify-kinds! (adorn#adorn! chars)))))
    (lambda (chars)
      (unless (null? chars)
        (let ((expr/rest/class (lisp-expression/rest/class chars)))
          (let ((expression (car expr/rest/class))
                (rest (cadr expr/rest/class))
                (class (caddr expr/rest/class)))
            (write-ac-list (adorn+simplify expression))
            (unless (null? rest)
              (let ((pre-result/rest (pre-lisp-result/rest rest)))
                (let ((pre-result (car pre-result/rest))
                      (rest (cadr pre-result/rest)))
                  (write-chars pre-result)
                  (let ((result/rest (lisp-result/rest rest)))
                    (let ((result (car result/rest))
                          (rest (cadr result/rest)))
                      (if (eq? class 'ok)
                          (write-ac-list (adorn+simplify result))
                          (write-chars result))
                      (let ((post-result/rest (post-lisp-result/rest rest)))
                        (let ((post-result (car post-result/rest))
                              (rest (cadr post-result/rest)))
                          (write-chars post-result)
                          (write-lisp rest))))))))))))))

(define write-ac-list
  (let ((char->texi-char
         (let ((texinfo-safe (append '(#\space #\newline)
                                     (char-set->list
                                      (char-set-intersection
                                       char-set:letter+digit
                                       char-set:ascii)))))
           (letrec ((zero-pad (lambda (char-list)
                                (if (> 4 (length char-list))
                                    (zero-pad (cons #\0 char-list))
                                    char-list))))
             (let ((char->texinfo-maybe-U
                    (lambda (char)
                      (if (member char texinfo-safe char=?)
                          (list char)
                          (append '(#\@ #\U #\{)
                                  (zero-pad
                                   (map char-upcase
                                        (string->list
                                         (number->string (char->integer char)
                                                         16))))
                                  '(#\}))))))
               (lambda (char)
                 (cond ((char=? char #\&) (string->list "@ampchar{}"))
                       ((char=? char #\@) (string->list "@atchar{}"))
                       ((char=? char #\\) (string->list "@backslashchar{}"))
                       ((char=? char #\,) (string->list "@comma{}"))
                       ((char=? char #\#) (string->list "@hashchar{}"))
                       ((char=? char #\{) (string->list "@lbracechar{}"))
                       ((char=? char #\}) (string->list "@rbracechar{}"))
                       ((char=? char #\ ) (string->list "@ "))
                       (else (char->texinfo-maybe-U char))))))))
        (close-macro (lambda () (write-char #\})))
        (kind->macro-open
         (lambda (kind) (append '(#\@) (kind->macro-name kind) '(#\{)))))
    (let ((open-macro (lambda (kind) (write-chars (kind->macro-open kind)))))
      (lambda (ac-list)
        (let loop ((rest ac-list) (macro #f))
          (cond ((null? rest) (when macro (close-macro)))
                (else (let ((ac (car rest)))
                        (let ((nc (adorn#get-char ac)) (k (adorn#get-kind ac)))
                          (cond ((not macro)
                                 (cond ((memq k '(default whitespace))
                                        (write-chars (char->texi-char nc))
                                        (loop (cdr rest) #f))
                                       (else
                                        (open-macro k)
                                        (write-chars (char->texi-char nc))
                                        (loop (cdr rest) k))))
                                (else (cond ((memq k (list macro 'whitespace))
                                             (write-chars (char->texi-char nc))
                                             (loop (cdr rest) macro))
                                            ((eq? k 'default)
                                             (close-macro)
                                             (write-chars (char->texi-char nc))
                                             (loop (cdr rest) #f))
                                            (else (close-macro)
                                                  (open-macro k)
                                                  (write-chars
                                                   (char->texi-char nc))
                                                  (loop (cdr rest)
                                                        k))))))))))))))
