#!/usr/bin/env gsi-script
;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define (main . args)
  (write-string "@comment Generated by write-macros+vars.scm\n\n")
  (for-each write-lisp-syntax-macro lisp-syntax-classes)
  (write-visual-divider)
  (for-each (lambda (args) (apply write-par-macro args))
            '(("parzero" "_0" "@U{2080}" "0") ("parI"   "_1" "@U{2081}" "1")
              ("parII"   "_2" "@U{2082}" "2") ("parIII" "_3" "@U{2083}" "3")
              ("parIV"   "_4" "@U{2084}" "4") ("parV"   "_5" "@U{2085}" "5")
              ("parVI"   "_6" "@U{2086}" "6") ("parVII" "_7" "@U{2087}" "7")
              ("parVIII" "_8" "@U{2088}" "8") ("parIX"  "_9" "@U{2089}" "9")
              ("pare"    "_E" "@U{2091}" "e") ("parj"   "_J" "@U{2C7C}" "j")
              ("park"    "_K" "@U{2096}" "k") ("parn"   "_N" "@U{2099}" "n")
              ("parp"    "_P" "@U{209A}" "p") ("parq"   "_Q" "@U{2093}" "q")
              ("parr"    "_R" "@U{1D63}" "r") ("pars"   "_S" "@U{209B}" "s")
              ("parv"    "_V" "@U{1D65}" "v") ("parx"   "_X" "@U{2093}" "x")
              ("parmplusone" "_M+1" "@U{2098}@U{208A}@U{2081}" "m+1")
              ("parnplusone" "_N+1" "@U{2099}@U{208A}@U{2081}" "n+1")
              ("parxplusone" "_X+1" "@U{2093}@U{208A}@U{2081}" "x+1")))
  (write-visual-divider)
  (for-each (lambda (args) (apply write-var-macro args))
            '(("varzero" "_0" "@U{2080}" "0") ("varI"   "_1" "@U{2081}" "1")
              ("varII"   "_2" "@U{2082}" "2") ("varIII" "_3" "@U{2083}" "3")
              ("varIV"   "_4" "@U{2084}" "4") ("varV"   "_5" "@U{2085}" "5")
              ("varVI"   "_6" "@U{2086}" "6") ("varVII" "_7" "@U{2087}" "7")
              ("varVIII" "_8" "@U{2088}" "8") ("varIX"  "_9" "@U{2089}" "9")
              ("vare"    "_E" "@U{2091}" "e") ("varj"   "_J" "@U{2C7C}" "j")
              ("vark"    "_K" "@U{2096}" "k") ("varn"   "_N" "@U{2099}" "n")
              ("varp"    "_P" "@U{209A}" "p") ("varq"   "_Q" "@U{2093}" "q")
              ("varr"    "_R" "@U{1D63}" "r") ("vars"   "_S" "@U{209B}" "s")
              ("varv"    "_V" "@U{1D65}" "v") ("varx"   "_X" "@U{2093}" "x")
              ("varmplusone" "_M+1" "@U{2098}@U{208A}@U{2081}" "m+1")
              ("varnplusone" "_N+1" "@U{2099}@U{208A}@U{2081}" "n+1")
              ("varxplusone" "_X+1" "@U{2093}@U{208A}@U{2081}" "x+1")))
  (write-visual-divider)
  (write-expt-macro "inverse" "@U{207B}@U{00B9}" "@minus{}1")
  (write-expt-macro "square" "@U{00B2}" "2")
  (write-lisp-result-macro "andprints"
                           (string-append "@r{@i{"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "<span class=\"unspecified\">}}"
                                          "and prints"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "</span>}}}}")
                           "and-prints")
  (write-lisp-result-macro "exception" "@arrow{}" "exception" " exception")
  (write-lisp-result-macro "lispnote" "@result{}" "lisp-note")
  (write-lisp-result-macro "ok" "@result{}" "ok")
  (write-lisp-result-macro "output"
                           (string-append "@inlinefmtifelse{html,@U{22A3},"
                                          "@print{}}")
                           "output")
  (write-lisp-result-macro "prints"
                           (string-append "@inlinefmtifelse{html,"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "<span class=\"unspecified\">}}"
                                          "@r{@i{prints}}"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "</span>}},"
                                          "@print{}}")
                           "and-prints")
  (write-lisp-result-macro "problem" "@arrow{}" "problem")
  (write-lisp-text-macro "lispnotetext" "" "lisp-note")
  (write-lisp-text-macro "unspecified" "@result{}" "unspecified")
  (write-lisp-text-macro "unspecifiedtext" "" "unspecified")
  (write-define-macro)
  (write-noadorn-macro)
  (write-visual-divider)
  (write-opt-macro)
  (write-defabbrev-macro)
  (write-defparen-macro)
  (write-hc-macro)
  (write-hs-macro)
  (write-ht-macro)
  (write-iifinfo-macro)
  (write-todo-macro)
  (write-quotedbl-macro)
  (write-quotecode-macro)
  (write-angle-macro)
  (write-nobr-macro)
  (write-nc-macro)
  (write-ns-macro)
  (write-nt-macro)
  (write-rv-macro)
  (write-sv-macro)
  (write-prosedatumlabel-macro)
  (write-prosedatumref-macro)
  (write-visual-divider)
  (write-vars))

(define write-vars
  (let ((write-acronym-initial
         (lambda (acronym meaning)
           (write-string
            (string-append
             "@set " acronym "initial "
             "@acronym{" acronym "," meaning "}\n"))))
        (write-cdspace
         (lambda ()
           (write-string
            (string-append "@set cdspace "
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"cdspace\">}"
                           "@ "
                           "@inlineraw{html,</span>},"
                           "@ }\n"))))
        (write-defdots
         (lambda ()
           (write-string
            (string-append "@set defdots "
                           "@inlinefmtifelse{html,@inlineraw{html,"
                           "<span class=\"def-dots\">}"
                           "@r{@dots{}}"
                           "@inlineraw{html,"
                           "</span>},"
                           "@dots{}}\n"))))
        (write-dnspace
         (lambda ()
           (write-string
            (string-append "@set dnspace "
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"dnspace\">}"
                           "@ "
                           "@inlineraw{html,</span>},"
                           "@ }\n"))))
        (write-greekcapitalsigma
         (lambda ()
           (write-string
            (string-append "@set capitalsigma "
                           "@inlinefmtifelse{tex,"
                           "@math{\\\\Sigma},"
                           "@U{03A3}}\n"))))
        (write-greeksmallsigma
         (lambda ()
           (write-string
            (string-append "@set smallsigma "
                           "@inlinefmtifelse{tex,"
                           "@math{\\\\sigma},"
                           "@U{03C3}}\n"))))
        (write-greekfinalsigma
         (lambda ()
           (write-string
            (string-append "@set finalsigma "
                           "@inlinefmtifelse{tex,"
                           "@math{\\\\varsigma},"
                           "@U{03C2}}\n"))))
        (write-IEEE-754-initial
         (lambda ()
           (write-string
            (string-append
             "@set " "IEEE754initial "
             "@acronym{IEEE 754,"
             "@acronym{IEEE} Standard for Floating-Point Arithmetic}\n"))))
        (write-IEEE-754-2008-initial
         (lambda ()
           (write-string
            (string-append
             "@set " "IEEE7542008initial "
             "@acronym{IEEE 754-2008,"
             "@acronym{IEEE 754}@comma{} 2008 revision}\n"))))
        (write-longarrow
         (lambda ()
           (write-string
            (string-append "@set longarrow "
                           "@inlinefmtifelse{info,@arrow{},"
                           "@inlinefmtifelse{plaintext,@arrow{},"
                           "@r{@U{27F6}}}}\n"))))
        (write-newsigma
         (lambda ()
           (write-string
            (string-append "@set newsigma "
                           "@i{new}"
                           "@inlinefmtifelse{html,@U{2009},}𝜎"
                           "\n"))))
        (write-SRFIinitial
         (lambda (number title)
           (write-string
            (string-append "@set SRFI" number "initial "
                           "@acronym{@acronym{SRFI} " number
                           ",@i{" title "}}\n"))))
        (write-SRFIitem
         (lambda (number title author year)
           (write-string
            (string-append "@set SRFI" number "item "
                           "@url{https://srfi.schemers.org/srfi-" number
                           "/,@acronym{@acronym{SRFI} " number
                           ",@i{" title "}}}@*"
                           author "@comma{} " year "\n"))))
        (write-truishsigma
         (lambda ()
           (write-string
            (string-append "@set truishsigma "
                           "@i{truish}"
                           "@inlinefmtifelse{html,@U{2009},}𝜎"
                           "\n"))))
        (write-unspecifiedsigma
         (lambda ()
           (write-string
            (string-append "@set unspecifiedsigma "
                           "@i{unspecified}"
                           "@inlinefmtifelse{html,@U{2009},}𝜎"
                           "\n"))))
        (write-r2rs
         (lambda ()
           (write-string
            (string-append "@set R2RS @acronym{RRRS}\n"))))
        (write-Revisedn
         (lambda (n superscript)
           (write-string
            (string-append "@set Revised" n
                           " @inlinefmtifelse{plaintext,Revised^" n
                           ",@inlinefmtifelse{info,Revised" superscript
                           ",Revised@sup{" (string-downcase n)
                           "}}}\n"))))
        (write-RevisednRS
         (lambda (n superscript)
           (write-string
            (string-append "@set Revised" n
                           "RS @inlinefmtifelse{plaintext,Revised^" n
                           ",@inlinefmtifelse{info,Revised" superscript
                           ",Revised@sup{" (string-downcase n)
                           "}}} "
                           "Report on the Algorithmic Language Scheme\n"))))
        (write-RnRSinitial
         (lambda (n superscript)
           (write-string
            (string-append
             "@set R" n
             "RSinitial @inlinefmtifelse{plaintext,@acronym{R" n
             "RS,@value{Revised" n "RS}},"
             "@inlinefmtifelse{info,@acronym{R" superscript
             "RS,@value{Revised" n "RS}},"
             "@inlinefmtifelse{html,@acronym{R@sup{" (string-downcase n)
             "}RS,Revised" superscript
             " Report on the Algorithmic Langugage Scheme},"
             "@acronym{R@sup{" (string-downcase n)
             "}RS}}}}\n"))))
        (write-RnRS
         (lambda (n superscript)
           (write-string
            (string-append "@set R" n
                           "RS @inlinefmtifelse{plaintext,@acronym{R" n
                           "RS},@inlinefmtifelse{info,@acronym{R" superscript
                           "RS},@acronym{R@sup{" (string-downcase n)
                           "}RS}}}\n"))))
        (write-set
         (lambda (flag/value)
           (write-string
            (string-append "@set "
                           (car flag/value)
                           " "
                           (cadr flag/value)
                           "\n"))))
        (write-syntaxindent
         (lambda ()
           (write-string
            (string-append "@set syntaxindent "
                           "@inlinefmtifelse{plaintext,@ ,"
                           "@inlinefmtifelse{info,@ ,"
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"category-def\">}"
                           "@ @ @ @ @ @ @ "
                           "@inlineraw{html,</span>},,}}}\n")))))
    (lambda ()
      (write-acronym-initial
       "ASCII" "American Standard Code for Information Interchange")
      (write-acronym-initial
       "BNF" "Backus-Naur Form")
      (write-acronym-initial
       "IEEE" "Institute of Electrical and Electronics Engineers")
      (write-acronym-initial
       "MIT" "Massachusetts Institute of Technology")
      (write-acronym-initial
       "RRRS" "@i{Revised Revised Report on Scheme}")
      (write-SRFIinitial
       "45" "Primitives for Expressing Iterative Lazy Algorithms")
      (write-acronym-initial
       "SI" "International System of Units")
      (write-acronym-initial
       "TAI" "International Atomic Time")
      (write-acronym-initial
       "UAX" "Unicode Standard Annex")
      (write-acronym-initial
       "UTC" "Coordinated Universal Time")
      (for-each (lambda (args) (apply write-SRFIitem args))
                '(("0" "Feature-based conditional expansion construct"
                   "Marc Feeley" "1999")
                  ("1" "List Library"
                   "Olin Shivers" "1999")
                  ("4" "Homogeneous Numeric Vector Datatypes"
                   "Marc Feeley" "1999")
                  ("6" "Basic Strings Ports"
                   "William Clinger" "1999")
                  ("9" "Defining Record Types"
                   "Richard Kelsey" "1999")
                  ("11" "Syntax for receiving multiple values"
                   "Lars T Hansen" "2000")
                  ("13" "String Libraries"
                   "Olin Shivers" "2000")
                  ("16" "Syntax for procedures of variable arity"
                   "Lars T Hansen" "2000")
                  ("30" "Nested Multi-line comments"
                   "Martin Gasbichler" "2002")
                  ("34" "Exception Handling for Programs"
                   "Richard Kelsey and Michael Sperber" "2002")
                  ("39" "Parameter Objects"
                   "Marc Feeley" "2003")
                  ("43" "Vector library"
                   "Taylor Campbell" "2004")
                  ("46" "Basic @t{Syntax-rules} Extensions"
                   "Taylor Campbell" "2005")
                  ("62" "S-expression comments"
                   "Taylor Campbell" "2005")
                  ("87" "@t{=>} in @t{case} clauses"
                   "Chongkai Zhu" "2006")))
      (write-cdspace)
      (write-defdots)
      (write-dnspace)
      (write-greekcapitalsigma)
      (write-greeksmallsigma)
      (write-greekfinalsigma)
      (write-IEEE-754-initial)
      (write-IEEE-754-2008-initial)
      (write-longarrow)
      (write-newsigma)
      (write-truishsigma)
      (write-unspecifiedsigma)
      (write-Revisedn "5" "@U{2075}")
      (write-Revisedn "6" "@U{2076}")
      (write-RevisednRS "3" "@U{00B3}")
      (write-RevisednRS "4" "@U{2074}")
      (write-RevisednRS "5" "@U{2075}")
      (write-RevisednRS "6" "@U{2076}")
      (write-RevisednRS "7" "@U{2077}")
      (write-r2rs)
      (write-RnRSinitial "3" "@U{00B3}")
      (write-RnRSinitial "4" "@U{2074}")
      (write-RnRSinitial "5" "@U{2075}")
      (write-RnRSinitial "6" "@U{2076}")
      (write-RnRSinitial "7" "@U{2077}")
      (write-RnRSinitial "N" "@U{207f}")
      (write-RnRS "3" "@U{00B3}")
      (write-RnRS "4" "@U{2074}")
      (write-RnRS "5" "@U{2075}")
      (write-RnRS "6" "@U{2076}")
      (write-RnRS "7" "@U{2077}")
      (write-RnRS "N" "@U{207f}")
      (for-each write-set
                '(("REVISION" "Revised")
                  ("VERSION" "4.9.5")
                  ("HOMEPAGEURL" "https://gambitscheme.org")
                  ("GITHUBURL" "https://github.com/gambit/gambit")
                  ("shy" "@inlinefmt{html,@U{00AD}}")))
      (write-syntaxindent))))

(define write-visual-divider
  (let ((cmnt "@comment "))
    (lambda (#!optional (char #\=) (full-length 79))
      (let loop ((chars '(#\newline)) (i (- full-length (string-length cmnt))))
        (if (positive? i)
            (loop (cons char chars) (- i 1))
            (write-string (string-append cmnt (list->string chars))))))))

(define lisp-syntax-classes
  '(abbrev
    atmosphere
    aux
    aux-abbrev
    aux-esc
    boolean
    box
    char
    char-body
    compound
    compound-empty
    datum-label
    datum-ref
    def-like-bind
    def-like-esc
    defsyntax
    defsyntax-esc
    defrec-name
    defrec-name-esc
    defrec-cons
    defrec-cons-esc
    defrec-param
    defrec-param-esc
    defrec-pred
    defrec-pred-esc
    defrec-field
    defrec-field-esc
    defrec-acc
    defrec-acc-esc
    defrec-mut
    defrec-mut-esc
    directive
    dot
    dsssl
    hs-begin
    hs-key
    ident
    ident-esc
    import-lib
    import-lib-ident
    import-lib-ident-esc
    import-lib-esc
    invalid
    key-bind
    key-init
    keyword
    syntax-let-bind
    syntax-let-esc
    let-like-bind
    let-like-esc
    number
    repl-ref
    serial-ref
    sharp
    shebang
    sr-ellipsis
    sr-ellipsis-esc
    sr-keyword
    sr-keyword-esc
    sr-literal
    sr-literal-esc
    sr-patvar
    sr-patvar-esc
    string
    string-esc
    syntax
    syntax-abbrev
    syntax-esc))

(define kind->macro-name
  (let ((rev-string->list (lambda (str) (reverse (string->list str)))))
    (lambda (kind)
      (let loop ((old (string->list (symbol->string kind))) (new '()))
        (if (null? old)
            (reverse new)
            (let ((next (car old)))
              (cond
               ((char=? next #\-)
                (loop (cdr old) new))
               ((char=? next #\+)
                (loop (cdr old) (append (rev-string->list "PLUS") new)))
               ((char=? next #\/)
                (loop (cdr old) (append (rev-string->list "SLASH") new)))
               ((char=? next #\~)
                (loop (cdr old) (append (rev-string->list "TILDE") new)))
               ((char=? next #\#)
                (loop (cdr old) (append (rev-string->list "OCTOTHORPE") new)))
               ((char=? next #\0)
                (loop (cdr old) (append (rev-string->list "ZERO") new)))
               ((char=? next #\1)
                (loop (cdr old) (append (rev-string->list "I") new)))
               ((char=? next #\2)
                (loop (cdr old) (append (rev-string->list "II") new)))
               ((char=? next #\3)
                (loop (cdr old) (append (rev-string->list "III") new)))
               ((char=? next #\4)
                (loop (cdr old) (append (rev-string->list "IV") new)))
               ((char=? next #\5)
                (loop (cdr old) (append (rev-string->list "V") new)))
               ((char=? next #\6)
                (loop (cdr old) (append (rev-string->list "VI") new)))
               ((char=? next #\7)
                (loop (cdr old) (append (rev-string->list "VII") new)))
               ((char=? next #\8)
                (loop (cdr old) (append (rev-string->list "VIII") new)))
               ((char=? next #\9)
                (loop (cdr old) (append (rev-string->list "IX") new)))
               (else (loop (cdr old) (cons next new))))))))))

(define (write-define-macro)
  (write-string (string-append "@macro define {text}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<dfn>\\text\\</dfn>},@dfn{\\text\\}}\n"
                               "@end macro\n")))

(define (write-lisp-syntax-macro kind)
  (write-string
   (string-append "@macro "
                  (list->string (kind->macro-name kind))
                  " {xx}\n"
                  "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                  (symbol->string kind)
                  "\">\\xx\\</span>},\\xx\\}\n"
                  "@end macro\n")))

(define (write-iifinfo-macro)
  (write-string (string-append "@macro iifinfo {xx}\n"
                               "@inlinefmtifelse{plaintext,@var{\\xx\\},"
                               "@inlinefmtifelse{info,@i{\\xx\\},"
                               "@i{\\xx\\}"
                               "}}\n@end macro\n")))

(define (write-expt-macro macro-name info-string other-string)
  (write-string (string-append "@macro "
                               macro-name
                               " {text}\n"
                               "@inlinefmtifelse{info,\\text\\"
                               info-string
                               ","
                               "\\text\\@sup{"
                               other-string
                               "}}\n@end macro\n")))

(define (write-par-macro macro-name plaintext-string info-string other-string)
  (write-string (string-append "@macro "
                               macro-name
                               " {parameter}\n"
                               "@inlinefmtifelse{plaintext,\\parameter\\"
                               info-string ; plaintext-string
                               ","
                               "@inlinefmtifelse{info,\\parameter\\"
                               info-string
                               ","
                               "\\parameter\\@sub{"
                               other-string
                               "}}}\n@end macro\n")))

(define (write-var-macro macro-name plaintext-string info-string other-string)
  (write-string (string-append "@macro "
                               macro-name
                               " {variable}\n"
                               "@inlinefmtifelse{plaintext,@var{\\variable\\"
                               info-string ; plaintext-string
                               "},"
                               "@inlinefmtifelse{info,@var{\\variable\\"
                               info-string
                               "},"
                               "@var{\\variable\\@sub{"
                               other-string
                               "}}}}\n@end macro\n")))

(define (write-lisp-text-macro macro-name pointer-glyph class)
  (write-string
   (string-append "@macro "
                  macro-name
                  "{xx}\n"
                  pointer-glyph
                  (if (positive? (string-length pointer-glyph)) " " "")
                  "@r{@i{@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                  class
                  "\">\\xx\\</span>},"
                  "\\xx\\"
                  "}}}\n@end macro\n")))

(define (write-lisp-result-macro macro-name pointer-glyph class . postfix)
  (let ((postfix (if (null? postfix) "" (car postfix))))
    (write-string
     (string-append "@macro "
                    macro-name
                    " {xx}\n"
                    pointer-glyph
                    (if (positive? (string-length pointer-glyph)) " " "")
                    "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                    class
                    "\">\\xx\\"
                    postfix
                    "</span>},\\xx\\"
                    postfix
                    "}\n@end macro\n"))))

(define (write-noadorn-macro)
  (write-string
   (string-append "@macro noadorn {xx}\n"
                  "\\xx\\"
                  "\n@end macro\n")))

(define (write-hc-macro)
  (write-string "@macro hc {xx}\n@code{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-hs-macro)
  (write-string "@macro hs {xx}\n@samp{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-ht-macro)
  (write-string "@macro ht {xx}\n@t{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-nc-macro)
  (write-string "@macro nc {xx}\n@code{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-ns-macro)
  (write-string "@macro ns {xx}\n@samp{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-nt-macro)
  (write-string "@macro nt {xx}\n@t{@nobr{\\xx\\}}\n@end macro\n"))

(define (write-defabbrev-macro)
  (write-string (string-append "@macro defabbrev {a}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-abbrev\">\\a\\</span>}"
                               ",\\a\\}\n"
                               "@end macro\n")))

(define (write-defparen-macro)
  (write-string (string-append "@macro defparen {p}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-paren\">\\p\\</span>}"
                               ",\\p\\}\n"
                               "@end macro\n")))

(define (write-angle-macro)
  (let ((left-angle-bracket "@U{2329}" )  ; @U{27E8} @U{3008}
        (right-angle-bracket "@U{232A}")) ; @U{27E9} @U{3009}
    (write-string
     (string-append "@macro angle {text}\n"
                    "@inlinefmtifelse{plaintext,"
                    "@U{003C}" "\\text\\" "@U{003E}"
                    ","
                    "@inlinefmtifelse{info,"
                    "@U{003C}" "\\text\\" "@U{003E}"
                    ","
                    "@inlinefmtifelse{html,"
                    "@inlineraw{html,<span class=\"angle-bracket\">}"
                    left-angle-bracket
                    "@inlineraw{html,</span>}"
                    "\\text\\"
                    "@inlineraw{html,<span class=\"angle-bracket\">}"
                    right-angle-bracket
                    "@inlineraw{html,</span>}"
                    ","
                    left-angle-bracket "\\text\\" right-angle-bracket
                    "}}}\n@end macro\n"))))

(define (write-rv-macro) ; rv ==> "roman variable"
  (write-string (string-append "@macro rv {v}\n"
                               "@r{@var{\\v\\}}\n"
                               "@end macro\n")))

(define (write-sv-macro) ; sv ==> "syntactic variable"
  (write-string (string-append "@macro sv {v}\n"
                               "@r{@angle{\\v\\}}\n"
                               "@end macro\n")))

(define (write-quotedbl-macro)
  (write-string
   (string-append "@macro quotedbl {text}\n"
                  "@inlinefmtifelse{tex,``\\text\\'',"
                  "@inlinefmtifelse{latex,``\\text\\'',"
                  "@quotedblleft{}\\text\\@quotedblright{}}}\n"
                  "@end macro\n")))

(define (write-quotecode-macro)
  (write-string
   (string-append "@macro quotecode {text}\n"
                  "@inlinefmtifelse{plaintext,@code{\\text\\},"
                  "@inlinefmtifelse{info,@code{\\text\\},"
                  "@quotedbl{@t{\\text\\}}}}\n"
                  "@end macro\n")))

(define (write-nobr-macro)
  (write-string
   (string-append "@macro nobr {xx}\n"
                  "@inlinefmtifelse{html,"
                  "@inlineraw{html,<span class=\"nobr\">\\xx\\</span>},"
                  "@w{\\xx\\}}"
                  "\n@end macro\n")))

(define (write-opt-macro)
  (write-string #<<EOF
@rmacro opt {arg}
@inlinefmtifelse{html,@inlineraw{html,<span class="def-bracket">[</span>}\arg\@inlineraw{html,<span class="def-bracket">]</span>},[\arg\]}
@end rmacro

EOF
))

(define (write-todo-macro)
  (write-string #<<EOF
@macro todo {t}
@inlinefmtifelse{html,@inlineraw{html,<span class="todo">@sc{TODO}:</span> \t\},@sc{TODO}: \t\}
@end macro

EOF
))


(define (write-prosedatumlabel-macro)
  (write-string (string-append "@macro prosedatumlabel {xx}\n"
                               "@inlinefmtifelse{html,"
                               "@inlineraw{html,"
                               "<span class=\"nobr\">"
                               "@hashchar{}@sv{\\xx\\}="
                               "</span>},"
                               "@hashchar{}@sv{\\xx\\}="
                               "}\n@end macro\n")))

(define (write-prosedatumref-macro)
  (write-string (string-append "@macro prosedatumref {xx}\n"
                               "@inlinefmtifelse{html,"
                               "@inlineraw{html,"
                               "<span class=\"nobr\">"
                               "@hashchar{}@sv{\\xx\\}@hashchar{}"
                               "</span>},"
                               "@hashchar{}@sv{\\xx\\}@hashchar{}"
                               "}\n@end macro\n")))

;; (define (write-prosedatumlabel-macro)
;; (write-string #<<EOF
;; @macro prosedatumlabel {n}
;; @inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}=}</span>},@t{@hashchar{}@sv{n}=}}
;; @end macro

;; EOF
;; ))

;; (define (write-prosedatumref-macro)
;; (write-string #<<EOF
;; @macro prosedatumref {n}
;; @inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}@hashchar{}}</span>},@t{@hashchar{}@sv{n}@hashchar{}}}
;; @end macro

;; EOF
;; ))
