#!/usr/bin/env gsi-script
;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define (main . args)
  (write-string "@comment Generated by write-macros+vars.scm\n\n")
  (for-each write-lisp-syntax-macro lisp-syntax-classes)
  (write-visual-divider)
  (for-each (lambda (args) (apply write-par-macro args))
            '(("pari" "1" "@U{2081}" "1")   ("parii" "2" "@U{2082}" "2")
              ("pariii" "3" "@U{2083}" "3") ("pariv" "4" "@U{2084}" "4")
              ("parv" "5" "@U{2085}" "5")   ("parvi" "6" "@U{2086}" "6")
              ("parvii" "7" "@U{2087}" "7") ("parviii" "8" "@U{2088}" "8")
              ("parix" "9" "@U{2089}" "9")  ("parj" "J" "@U{2C7C}" "j")
              ("parn" "N" "@U{2099}" "n")
              ("parnplusone" "N+1" "@U{2099}@U{208A}@U{2081}" "n+1")))
  (write-visual-divider)
  (for-each (lambda (args) (apply write-var-macro args))
            '(("vari" "1" "@U{2081}" "1")   ("varii" "2" "@U{2082}" "2")
              ("variii" "3" "@U{2083}" "3") ("variv" "4" "@U{2084}" "4")
              ("varv" "5" "@U{2085}" "5")   ("varvi" "6" "@U{2086}" "6")
              ("varvii" "7" "@U{2087}" "7") ("varviii" "8" "@U{2088}" "8")
              ("varix" "9" "@U{2089}" "9")  ("varj" "J" "@U{2C7C}" "j")
              ("varn" "N" "@U{2099}" "n")
              ("varnplusone" "N+1" "@U{2099}@U{208A}@U{2081}" "n+1")))
  (write-visual-divider)
  (write-lisp-result-macro "andprints"
                           (string-append "@r{@i{"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "<span class=\"unspecified\">}}"
                                          "and prints"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "</span>}}}}")
                           "and-prints")
  (write-lisp-result-macro "exception" "@arrow{}" "exception" " exception")
  (write-lisp-result-macro "lispnote" "@result{}" "lisp-note")
  (write-lisp-result-macro "ok" "@result{}" "ok")
  (write-lisp-result-macro "output"
                           (string-append "@inlinefmtifelse{html,@U{22A3},"
                                          "@print{}}")
                           "output")
  (write-lisp-result-macro "problem" "@arrow{}" "problem")
  (write-lisp-text-macro "lispnotetext" "" "lisp-note")
  (write-lisp-text-macro "unspecified" "@result{}" "unspecified")
  (write-lisp-text-macro "unspecifiedtext" "" "unspecified")
  (write-visual-divider)
  (write-opt-macro)
  (write-defabbrev-macro)
  (write-defdots-macro)
  (write-defparen-macro)
  (write-hc-macro)
  (write-ht-macro)
  (write-todo-macro)
  (write-quotedbl-macro)
  (write-quotecode-macro)
  (write-angle-macro)
  (write-longarrow-macro)
  (write-nobr-macro)
  (write-sv-macro)
  (write-prosedatumlabel-macro)
  (write-prosedatumref-macro)
  (write-visual-divider)
  (write-vars))

(define write-vars
  (let ((write-cdspace
         (lambda ()
           (write-string
            (string-append "@set cdspace "
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"cdspace\">}"
                           "@ "
                           "@inlineraw{html,</span>},"
                           "@ }\n"))))
        (write-dnspace
         (lambda ()
           (write-string
            (string-append "@set dnspace "
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"dnspace\">}"
                           "@ "
                           "@inlineraw{html,</span>},"
                           "@ }\n"))))
        (write-r2rs
         (lambda ()
           (write-string "@set R2RS @acronym{RRRS}\n")))
        (write-RevisednRS
         (lambda (n superscript)
           (write-string
            (string-append "@set Revised" n
                           "RS @inlinefmtifelse{plaintext,Revised^" n
                           ",@inlinefmtifelse{info,Revised" superscript
                           ",Revised@sup{" (string-downcase n)
                           "}}} "
                           "Report on the Algorithmic Language Scheme\n"))))
        (write-RnRS
         (lambda (n superscript)
           (write-string
            (string-append "@set R" n
                           "RS @inlinefmtifelse{plaintext,@acronym{R" n
                           "RS},@inlinefmtifelse{info,@acronym{R" superscript
                           "RS},@acronym{R@sup{" (string-downcase n)
                           "}RS}}}\n"))))
        (write-set
         (lambda (flag/value)
           (write-string
            (string-append "@set "
                           (car flag/value)
                           " "
                           (cadr flag/value)
                           "\n"))))
        (write-syntaxindent
         (lambda ()
           (write-string
            (string-append "@set syntaxindent "
                           "@inlinefmtifelse{plaintext,@ ,"
                           "@inlinefmtifelse{info,@ ,"
                           "@inlinefmtifelse{html,"
                           "@inlineraw{html,<span class=\"category-def\">}"
                           "@ @ @ @ @ @ @ "
                           "@inlineraw{html,</span>},,}}}\n")))))
    (lambda ()
      (write-cdspace)
      (write-dnspace)
      (write-RevisednRS "3" "@U{00B3}")
      (write-RevisednRS "4" "@U{2074}")
      (write-RevisednRS "5" "@U{2075}")
      (write-RevisednRS "6" "@U{2076}")
      (write-RevisednRS "7" "@U{2077}")
      (write-r2rs)
      (write-RnRS "3" "@U{00B3}")
      (write-RnRS "4" "@U{2074}")
      (write-RnRS "5" "@U{2075}")
      (write-RnRS "6" "@U{2076}")
      (write-RnRS "7" "@U{2077}")
      (write-RnRS "N" "@U{207f}")
      (for-each write-set
                '(("REVISION" "Revised")
                  ("VERSION" "4.9.5")
                  ("HOMEPAGEURL" "https://gambitscheme.org")
                  ("GITHUBURL" "https://github.com/gambit/gambit")
                  ("shy" "@inlinefmt{html,@U{00AD}}")))
      (write-syntaxindent))))

(define write-visual-divider
  (let ((cmnt "@comment "))
    (lambda (#!optional (char #\=) (full-length 79))
      (let loop ((chars '(#\newline)) (i (- full-length (string-length cmnt))))
        (if (positive? i)
            (loop (cons char chars) (- i 1))
            (write-string (string-append cmnt (list->string chars))))))))

(define lisp-syntax-classes
  '(abbrev
    atmosphere
    boolean
    box
    char
    char-body
    compound
    compound-empty
    datum-label
    datum-ref
    def-like-bind
    def-like-esc
    directive
    dot
    dsssl
    hs-begin
    hs-key
    ident
    ident-esc
    invalid
    key-bind
    key-init
    keyword
    let-like-bind
    let-like-esc
    number
    repl-ref
    serial-ref
    sharp
    shebang
    string
    string-esc
    syntax
    syntax-esc))

(define kind->macro-name
  (let ((rev-string->list (lambda (str) (reverse (string->list str)))))
    (lambda (kind)
      (let loop ((old (string->list (symbol->string kind))) (new '()))
        (if (null? old)
            (reverse new)
            (let ((next (car old)))
              (cond
               ((char=? next #\-)
                (loop (cdr old) new))
               ((char=? next #\+)
                (loop (cdr old) (append (rev-string->list "PLUS") new)))
               ((char=? next #\/)
                (loop (cdr old) (append (rev-string->list "SLASH") new)))
               ((char=? next #\~)
                (loop (cdr old) (append (rev-string->list "TILDE") new)))
               ((char=? next #\#)
                (loop (cdr old) (append (rev-string->list "OCTOTHORPE") new)))
               ((char=? next #\0)
                (loop (cdr old) (append (rev-string->list "ZERO") new)))
               ((char=? next #\1)
                (loop (cdr old) (append (rev-string->list "I") new)))
               ((char=? next #\2)
                (loop (cdr old) (append (rev-string->list "II") new)))
               ((char=? next #\3)
                (loop (cdr old) (append (rev-string->list "III") new)))
               ((char=? next #\4)
                (loop (cdr old) (append (rev-string->list "IV") new)))
               ((char=? next #\5)
                (loop (cdr old) (append (rev-string->list "V") new)))
               ((char=? next #\6)
                (loop (cdr old) (append (rev-string->list "VI") new)))
               ((char=? next #\7)
                (loop (cdr old) (append (rev-string->list "VII") new)))
               ((char=? next #\8)
                (loop (cdr old) (append (rev-string->list "VIII") new)))
               ((char=? next #\9)
                (loop (cdr old) (append (rev-string->list "IX") new)))
               (else (loop (cdr old) (cons next new))))))))))

(define (write-lisp-syntax-macro kind)
  (write-string
   (string-append "@macro "
                  (list->string (kind->macro-name kind))
                  " {xx}\n"
                  "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                  (symbol->string kind)
                  "\">\\xx\\</span>},\\xx\\}\n"
                  "@end macro\n")))

(define (write-par-macro macro-name plaintext-string info-string other-string)
  (write-string
   (string-append "@macro "
                  macro-name
                  " {param}\n"
                  "@inlinefmtifelse{plaintext,\\param\\"
                  plaintext-string
                  ",@inlinefmtifelse{info,\\param\\"
                  info-string
                  ",\\param\\@sub{"
                  other-string
                  "}}}\n"
                  "@end macro\n")))

(define (write-var-macro macro-name plaintext-string info-string other-string)
  (write-string
   (string-append "@macro "
                  macro-name
                  " {var}\n"
                  "@inlinefmtifelse{info,@var{\\var\\"
                  plaintext-string
                  "},@inlinefmtifelse{plaintext,@var{\\var\\_"
                  info-string
                  "},@var{\\var\\@sub{"
                  other-string
                  "}}}}\n"
                  "@end macro\n")))

(define (write-lisp-text-macro macro-name pointer-glyph class)
  (write-string
   (string-append "@macro "
                  macro-name
                  "{xx}\n"
                  pointer-glyph
                  (if (positive? (string-length pointer-glyph)) " " "")
                  "@r{@i{@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                  class
                  "\">\\xx\\</span>},\\xx\\}}}\n"
                  "@end macro\n")))

(define (write-lisp-result-macro macro-name pointer-glyph class . postfix)
  (let ((postfix (if (null? postfix) "" (car postfix))))
    (write-string
     (string-append "@macro "
                    macro-name
                    " {xx}\n"
                    pointer-glyph
                    (if (positive? (string-length pointer-glyph)) " " "")
                    "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                    class
                    "\">\\xx\\"
                    postfix
                    "</span>},\\xx\\"
                    postfix
                    "}\n@end macro\n"))))

(define (write-hc-macro)
  (write-string "@macro hc {xx}\n@code{\\xx\\}\n@end macro\n"))

(define (write-ht-macro)
  (write-string "@macro ht {xx}\n@t{\\xx\\}\n@end macro\n"))

(define (write-defabbrev-macro)
  (write-string (string-append "@macro defabbrev {a}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-abbrev\">\\a\\</span>}"
                               ",\\a\\}\n"
                               "@end macro\n")))

(define (write-defdots-macro)
  (write-string (string-append "@macro defdots {}\n"
                               "@r{@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-dots\">...</span>}"
                               ",@dots{}}}\n"
                               "@end macro\n")))

(define (write-defparen-macro)
  (write-string (string-append "@macro defparen {p}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-paren\">\\p\\</span>}"
                               ",\\p\\}\n"
                               "@end macro\n")))

(define (write-angle-macro)
  (let ((left-angle-bracket "@U{2329}" #;"@U{3008}")
        (right-angle-bracket "@U{232A}" #;"@U{3009}"))
    (write-string
     (string-append "@macro angle {text}\n"
                    "@inlinefmtifelse{plaintext,"
                    "@U{003C}" "\\text\\" "@U{003E}"
                    ","
                    "@inlinefmtifelse{info,"
                    "@U{003C}" "\\text\\" "@U{003E}"
                    ","
                    "@inlinefmtifelse{html,"
                    "@inlineraw{html,<span class=\"angle-bracket\">}"
                    left-angle-bracket
                    "@inlineraw{html,</span>}"
                    "\\text\\"
                    "@inlineraw{html,<span class=\"angle-bracket\">}"
                    right-angle-bracket
                    "@inlineraw{html,</span>}"
                    ","
                    left-angle-bracket "\\text\\" right-angle-bracket
                    "}}}\n@end macro\n"))))

(define (write-longarrow-macro)
  (write-string (string-append "@macro longarrow {}\n"
                               "@inlinefmtifelse{info,==>,"
                               "@inlinefmtifelse{plaintext,==>,"
                               "@U{27F6}}}\n"
                               "@end macro\n")))

(define (write-sv-macro) ; sv ==> "syntactic variable"
  (write-string (string-append "@macro sv {v}\n"
                               "@r{@angle{\\v\\}}\n"
                               "@end macro\n")))

(define (write-quotedbl-macro)
  (write-string
   (string-append "@macro quotedbl {text}\n"
                  "@inlinefmtifelse{tex,``\\text\\'',"
                  "@inlinefmtifelse{latex,``\\text\\'',"
                  "@quotedblleft{}\\text\\@quotedblright{}}}\n"
                  "@end macro\n")))

(define (write-quotecode-macro)
  (write-string
   (string-append "@macro quotecode {text}\n"
                  "@inlinefmtifelse{plaintext,@code{\\text\\},"
                  "@inlinefmtifelse{info,@code{\\text\\},"
                  "@quotedbl{@t{\\text\\}}}}\n"
                  "@end macro\n")))

(define (write-nobr-macro)
  (write-string
   (string-append "@macro nobr {xx}\n"
                  "@inlinefmtifelse{html,"
                  "@inlineraw{html,<span class=\"nobr\">\\xx\\</span>},"
                  "@w{\\xx\\}}"
                  "\n@end macro\n")))

(define (write-opt-macro)
  (write-string #<<EOF
@rmacro opt {arg}
@inlinefmtifelse{html,@inlineraw{html,<span class="def-bracket">[</span>}\arg\@inlineraw{html,<span class="def-bracket">]</span>},[\arg\]}
@end rmacro

EOF
))

(define (write-todo-macro)
  (write-string #<<EOF
@macro todo {t}
@inlinefmtifelse{html,@inlineraw{html,<span class="todo">@sc{TODO}:</span> \t\},@sc{TODO}: \t\}
@end macro

EOF
))

(define (write-prosedatumlabel-macro)
(write-string #<<EOF
@macro prosedatumlabel {n}
@inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}=}</span>},@t{@hashchar{}@sv{n}=}}
@end macro

EOF
))

(define (write-prosedatumref-macro)
(write-string #<<EOF
@macro prosedatumref {n}
@inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}@hashchar{}}</span>},@t{@hashchar{}@sv{n}@hashchar{}}}
@end macro

EOF
))
