#!/usr/bin/env gsi-script
;; Copyright (c) 2024 by Macon Gambill, all rights reserved.

(define (main . args)
  (write-string "@comment Generated by write-macros+vars.scm\n\n")
  (for-each write-lisp-syntax-macro lisp-syntax-classes)
  (write-visual-divider)
  (for-each (lambda (args) (apply write-par-macro args))
            '(("pari" "1") ("parii" "2") ("pariii" "3") ("pariv" "4")
              ("parv" "5") ("parvi" "6") ("parvii" "7") ("parviii" "8")
              ("parix" "9") ("parj" "j") ("parn" "n") ("parnplusone" "n+1")))
  (write-visual-divider)
  (for-each (lambda (args) (apply write-var-macro args))
            '(("vari" "1") ("varii" "2") ("variii" "3") ("variv" "4")
              ("varv" "5") ("varvi" "6") ("varvii" "7") ("varviii" "8")
              ("varix" "9") ("varj" "j") ("varn" "n") ("varnplusone" "n+1")))
  (write-visual-divider)
  (write-lisp-result-macro "exception" "@arrow{}" "exception" " exception")
  (write-lisp-result-macro "ok" "@result{}" "ok")
  (write-lisp-result-macro "lispnote" "@result{}" "lisp-note")
  (write-lisp-result-macro "andprints"
                           (string-append "@r{@i{"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "<span class=\"unspecified\">}}"
                                          "and prints"
                                          "@inlinefmt{html,@inlineraw{html,"
                                          "</span>}}}}")
                           "and-prints")
  (write-lisp-result-macro "problem" "@arrow{}" "problem")
  (write-lisp-result-macro "unspecified" "@result{}" "unspecified")
  (write-lisp-result-macro "unspecifiedtext" "" "unspecified")
  (write-visual-divider)
  (write-opt-macro)
  (write-defabbrev-macro)
  (write-defdots-macro)
  (write-defparen-macro)
  (write-hc-macro)
  (write-ht-macro)
  (write-todo-macro)
  (write-quotedbl-macro)
  (write-angle-macro)
  (write-longarrow-macro)
  (write-nobr-macro)
  (write-sv-macro)
  (write-prosedatumlabel-macro)
  (write-prosedatumref-macro)
  (write-visual-divider)
  (write-vars))

(define write-vars
  (let ((write-set
         (lambda (flag/value)
           (write-string
            (string-append "@set "
                           (car flag/value)
                           " "
                           (cadr flag/value)
                           "\n"))))
        (write-rnrs
         (lambda (n)
           (write-string
            (string-append "@set R" n
                           "RS @inlinefmtifelse{info,@acronym{R" n
                           "RS},@inlinefmtifelse{plaintext,@acronym{R" n
                           "RS},@acronym{R@sup{" (string-downcase n)
                           "}RS}}}\n"))))
        (write-r2rs
         (lambda ()
           (write-string "@set R2RS @acronym{RRRS}\n"))))
    (lambda ()
      (for-each write-set
                '(("REVISION" "Revised")
                  ("VERSION" "4.9.5")
                  ("HOMEPAGEURL" "https://gambitscheme.org")
                  ("GITHUBURL" "https://github.com/gambit/gambit")
                  ("shy" "@inlinefmt{html,@U{00AD}}")))
      (for-each write-rnrs '("7" "6" "5" "4" "3" "N"))
      (write-r2rs))))

(define write-visual-divider 
  (let ((cmnt "@comment "))
    (lambda (#!optional (char #\=) (full-length 79))
      (let loop ((chars '(#\newline)) (i (- full-length (string-length cmnt))))
        (if (positive? i)
            (loop (cons char chars) (- i 1))
            (write-string (string-append cmnt (list->string chars))))))))

(define lisp-syntax-classes
  '(abbrev
    atmosphere
    boolean
    box
    char
    char-body
    compound
    compound-empty
    datum-label
    datum-ref
    def-like-bind
    def-like-esc
    directive
    dot
    dsssl
    hs-begin
    hs-key
    ident
    ident-esc
    invalid
    key-bind
    key-init
    keyword
    let-like-bind
    let-like-esc
    number
    repl-ref
    serial-ref
    sharp
    shebang
    string
    string-esc
    syntax
    syntax-esc))

(define kind->macro-name
  (let ((rev-string->list (lambda (str) (reverse (string->list str)))))
    (lambda (kind)
      (let loop ((old (string->list (symbol->string kind))) (new '()))
        (if (null? old)
            (reverse new)
            (let ((next (car old)))
              (cond
               ((char=? next #\-)
                (loop (cdr old) new))
               ((char=? next #\+)
                (loop (cdr old) (append (rev-string->list "PLUS") new)))
               ((char=? next #\/)
                (loop (cdr old) (append (rev-string->list "SLASH") new)))
               ((char=? next #\~)
                (loop (cdr old) (append (rev-string->list "TILDE") new)))
               ((char=? next #\#)
                (loop (cdr old) (append (rev-string->list "OCTOTHORPE") new)))
               ((char=? next #\0)
                (loop (cdr old) (append (rev-string->list "ZERO") new)))
               ((char=? next #\1)
                (loop (cdr old) (append (rev-string->list "I") new)))
               ((char=? next #\2)
                (loop (cdr old) (append (rev-string->list "II") new)))
               ((char=? next #\3)
                (loop (cdr old) (append (rev-string->list "III") new)))
               ((char=? next #\4)
                (loop (cdr old) (append (rev-string->list "IV") new)))
               ((char=? next #\5)
                (loop (cdr old) (append (rev-string->list "V") new)))
               ((char=? next #\6)
                (loop (cdr old) (append (rev-string->list "VI") new)))
               ((char=? next #\7)
                (loop (cdr old) (append (rev-string->list "VII") new)))
               ((char=? next #\8)
                (loop (cdr old) (append (rev-string->list "VIII") new)))
               ((char=? next #\9)
                (loop (cdr old) (append (rev-string->list "IX") new)))
               (else (loop (cdr old) (cons next new))))))))))

(define (write-lisp-syntax-macro kind)
  (write-string
   (string-append "@macro "
                  (list->string (kind->macro-name kind))
                  " {xx}\n"
                  "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                  (symbol->string kind)
                  "\">\\xx\\</span>},\\xx\\}\n"
                  "@end macro\n")))

(define (write-par-macro macro-name number-string)
  (write-string
   (string-append "@macro "
                  macro-name
                  " {param}\n"
                  "@inlinefmtifelse{info,\\param\\"
                  number-string
                  ",@inlinefmtifelse{plaintext,\\param\\"
                  number-string
                  ",\\param\\@sub{"
                  number-string
                  "}}}\n"
                  "@end macro\n")))

(define (write-var-macro macro-name number-string)
  (write-string
   (string-append "@macro "
                  macro-name
                  " {var}\n"
                  "@inlinefmtifelse{info,@var{\\var\\"
                  number-string
                  "},@inlinefmtifelse{plaintext,@var{\\var\\"
                  number-string
                  "},@var{\\var\\@sub{"
                  number-string
                  "}}}}\n"
                  "@end macro\n")))

(define (write-lisp-result-macro macro-name pointer-glyph class . postfix)
  (let ((postfix (if (null? postfix) "" (car postfix))))
    (write-string
     (string-append "@macro "
                    macro-name
                    " {xx}\n"
                    pointer-glyph
                    (if (positive? (string-length pointer-glyph)) " " "")
                    "@inlinefmtifelse{html,@inlineraw{html,<span class=\""
                    class
                    "\">\\xx\\"
                    postfix
                    "</span>},\\xx\\"
                    postfix
                    "}\n@end macro\n"))))

(define (write-hc-macro)
  (write-string "@macro hc {xx}\n@code{\\xx\\}\n@end macro\n"))

(define (write-ht-macro)
  (write-string "@macro ht {xx}\n@t{\\xx\\}\n@end macro\n"))

(define (write-defabbrev-macro)
  (write-string (string-append "@macro defabbrev {a}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-abbrev\">\\a\\</span>}"
                               ",\\a\\}\n"
                               "@end macro\n")))

(define (write-defdots-macro)
  (write-string (string-append "@macro defdots {}\n"
                               "@r{@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-dots\">...</span>}"
                               ",@dots{}}}\n"
                               "@end macro\n")))

(define (write-defparen-macro)
  (write-string (string-append "@macro defparen {p}\n"
                               "@inlinefmtifelse{html,@inlineraw{html,"
                               "<span class=\"def-paren\">\\p\\</span>}"
                               ",\\p\\}\n"
                               "@end macro\n")))

(define (write-opt-macro)
  (write-string #<<EOF
@rmacro opt {arg}
@inlinefmtifelse{html,@inlineraw{html,<span class="def-bracket">[</span>}\arg\@inlineraw{html,<span class="def-bracket">]</span>},[\arg\]}
@end rmacro

EOF
))

(define (write-todo-macro)
  (write-string #<<EOF
@macro todo {t}
@inlinefmtifelse{html,@inlineraw{html,<span class="todo">@sc{TODO}:</span> \t\},@sc{TODO}: \t\}
@end macro

EOF
))

(define (write-quotedbl-macro)
  (write-string #<<EOF
@macro quotedbl {text}
@inlinefmtifelse{tex,``\text\'',@quotedblleft{}\text\@quotedblright{}}
@end macro

EOF
))

(define (write-angle-macro)
  (write-string #<<EOF
@macro angle {text}
@inlinefmtifelse{info,<\text\>,@inlinefmtifelse{plaintext,<\text\>,@U{3008}\text\@U{3009}}}
@end macro

EOF
))

(define (write-longarrow-macro)
  (write-string (string-append "@macro longarrow {}\n"
                               "@inlinefmtifelse{info,==>,"
                               "@inlinefmtifelse{plaintext,==>,"
                               "@U{27F6}}}\n"
                               "@end macro\n")))

(define (write-sv-macro) ; sv ==> "syntactic variable"
  (write-string (string-append "@macro sv {v}\n"
                               "@r{@angle{\\v\\}}\n"
                               "@end macro\n")))

(define (write-nobr-macro)
(write-string #<<EOF
@macro nobr {xx}
@inlinefmtifelse{html,@inlineraw{html,<span class="nobr">\xx\</span>},@w{\xx\}}
@end macro

EOF
))

(define (write-prosedatumlabel-macro)
(write-string #<<EOF
@macro prosedatumlabel {n}
@inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}=}</span>},@t{@hashchar{}@sv{n}=}}
@end macro

EOF
))

(define (write-prosedatumref-macro)
(write-string #<<EOF
@macro prosedatumref {n}
@inlinefmtifelse{html,@inlineraw{html,<span class="nobr">@t{@hashchar{}@sv{n}@hashchar{}}</span>},@t{@hashchar{}@sv{n}@hashchar{}}}
@end macro

EOF
))
